import type { Strings } from "../i18n";

export const editorStrings: Strings = {
  en: {
    "editor.cmd.toggleSpellcheck": "Toggle spellcheck",
    "editor.cmd.insertSceneBreak": "Insert scene break",
    "editor.spellcheckOn": "Spellcheck on",
    "editor.spellcheckOff": "Spellcheck off",
    "editor.spellcheckNotOnDemand": "“Spellcheck only on demand” is off in Escrita's settings, so Obsidian's own spellcheck setting is in charge.",
    "editor.noBreakInProperties": "Scene breaks go in the text, not in the properties.",
    "editor.chapterFailed": "Couldn't create the next chapter: {error}",
    "editor.chapterOpenFailed": "Created “{name}”, but couldn't open it.",
    "editor.cmd.toggleDialogueFocus": "Toggle dialogue focus",
    "editor.dialogueFocusOn": "Dialogue focus on",
    "editor.dialogueFocusOff": "Dialogue focus off",
    "editor.dialogueFocusReading": "Dialogue focus on. It shows in the editor (Live Preview or Source), not in Reading view.",
    "editor.cmd.moveParagraphUp": "Move paragraph up",
    "editor.cmd.moveParagraphDown": "Move paragraph down",
    "editor.cmd.moveSceneUp": "Move scene up",
    "editor.cmd.moveSceneDown": "Move scene down",
    "editor.move.properties": "The properties stay put. Put the cursor in the text to move a paragraph or scene.",
    "editor.move.noBlock": "Put the cursor in a paragraph or scene to move it.",
    "editor.move.inUnit": "The cursor is inside a beat, comment, code or math block, which doesn't move. Put it in a paragraph.",
    "editor.move.unsafe": "Couldn't move this without changing how the note reads, so nothing moved.",
  },
  "pt-BR": {
    "editor.cmd.toggleSpellcheck": "Ligar/desligar corretor",
    "editor.cmd.insertSceneBreak": "Inserir quebra de cena",
    "editor.spellcheckOn": "Corretor ligado",
    "editor.spellcheckOff": "Corretor desligado",
    "editor.spellcheckNotOnDemand": "A opção “Corretor só quando pedir” está desligada nas configurações do Escrita, então quem manda é o corretor do próprio Obsidian.",
    "editor.noBreakInProperties": "Quebras de cena vão no texto, não nas propriedades.",
    "editor.chapterFailed": "Não deu para criar o próximo capítulo: {error}",
    "editor.chapterOpenFailed": "“{name}” foi criado, mas não deu para abri-lo.",
    "editor.cmd.toggleDialogueFocus": "Ligar/desligar foco no diálogo",
    "editor.dialogueFocusOn": "Foco no diálogo ligado",
    "editor.dialogueFocusOff": "Foco no diálogo desligado",
    "editor.dialogueFocusReading": "Foco no diálogo ligado. Ele aparece no editor (Visualização ao vivo ou Código-fonte), não no modo de leitura.",
    "editor.cmd.moveParagraphUp": "Mover parágrafo para cima",
    "editor.cmd.moveParagraphDown": "Mover parágrafo para baixo",
    "editor.cmd.moveSceneUp": "Mover cena para cima",
    "editor.cmd.moveSceneDown": "Mover cena para baixo",
    "editor.move.properties": "As propriedades ficam onde estão. Ponha o cursor no texto para mover um parágrafo ou uma cena.",
    "editor.move.noBlock": "Ponha o cursor num parágrafo ou numa cena para movê-lo.",
    "editor.move.inUnit": "O cursor está dentro de uma batida, comentário, código ou bloco de matemática, que não se movem. Ponha-o num parágrafo.",
    "editor.move.unsafe": "Não deu para mover sem mudar como a nota é lida, então nada foi movido.",
  },
};
