import type { Strings } from "../i18n";

export const submissionsStrings: Strings = {
  en: {
    "submissions.command": "Record a submission",
    "submissions.menu": "Record a submission…",
    "submissions.title": "Record a submission",
    "submissions.work": "Work",
    "submissions.market": "Where to",
    "submissions.market.placeholder": "A magazine, a contest, an editor",
    "submissions.recent": "Recent places",
    "submissions.sent": "Sent on",
    "submissions.where": "Creates {path} with {work}, {result}.",
    "submissions.cancel": "Cancel",
    "submissions.record": "Record",
    "submissions.recorded": "Submission recorded: {work} → {market}.",
    "submissions.notice.open": "Open a story or a book to record a submission.",
    "submissions.notice.noStage": "“{title}” isn't a work: give it a stage to record a submission.",
    "submissions.notice.untracked": "\"{title}\" is outside the folders Escrita tracks, so it isn't a work.",
    "submissions.notice.error": "Couldn't record the submission. Nothing was changed; see the developer console.",
    "submissions.settings.heading": "Submissions",
    "submissions.settings.folder": "Submissions folder",
    "submissions.settings.folder.desc": "One note per submission. Notes here are never counted by goals and never become works. Changing this doesn't move existing notes.",
    "submissions.settings.results": "Result values",
    "submissions.settings.results.desc": "Separated by commas. The first one is “pending”: a new submission starts with it, and the home block counts the submissions that still have it.",
    "submissions.settings.propWork": "Work property",
    "submissions.settings.propWork.desc": "The property in a submission note that links to the work.",
    "submissions.settings.propMarket": "Market property",
    "submissions.settings.propMarket.desc": "The property that holds where the work was sent.",
    "submissions.settings.propSent": "Sent date property",
    "submissions.settings.propSent.desc": "The property that holds the day it was sent.",
    "submissions.settings.propResult": "Result property",
    "submissions.settings.propResult.desc": "The property that holds the result (the values are set above).",
    "submissions.settings.propResponded": "Response date property",
    "submissions.settings.propResponded.desc": "The property that holds the day the answer came. Left empty in a new note.",
    "settings.features.off.submissions.one": "Submissions off. The {n} submission note stays in {folder}.",
    "settings.features.off.submissions.other": "Submissions off. The {n} submission notes stay in {folder}.",
    "settings.features.off.submissions.none": "Submissions off.",
  },
  "pt-BR": {
    "submissions.command": "Registrar envio",
    "submissions.menu": "Registrar envio…",
    "submissions.title": "Registrar envio",
    "submissions.work": "Obra",
    "submissions.market": "Para onde",
    "submissions.market.placeholder": "Uma revista, um concurso, um editor",
    "submissions.recent": "Lugares recentes",
    "submissions.sent": "Enviado em",
    "submissions.where": "Cria {path} com {work}, {result}.",
    "submissions.cancel": "Cancelar",
    "submissions.record": "Registrar",
    "submissions.recorded": "Envio registrado: {work} → {market}.",
    "submissions.notice.open": "Abra um conto ou um livro para registrar um envio.",
    "submissions.notice.noStage": "“{title}” não é uma obra: dê a ela um estágio para registrar um envio.",
    "submissions.notice.untracked": "\"{title}\" está fora das pastas que o Escrita acompanha, então não é uma obra.",
    "submissions.notice.error": "Não foi possível registrar o envio. Nada foi alterado; veja o console do desenvolvedor.",
    "submissions.settings.heading": "Envios",
    "submissions.settings.folder": "Pasta dos envios",
    "submissions.settings.folder.desc": "Uma nota por envio. As notas desta pasta nunca entram nas metas e nunca viram obras. Mudar esta opção não move as notas existentes.",
    "submissions.settings.results": "Valores do resultado",
    "submissions.settings.results.desc": "Separados por vírgula. O primeiro é “pendente”: um envio novo começa com ele, e o bloco de obras conta os envios que ainda o têm.",
    "submissions.settings.propWork": "Propriedade da obra",
    "submissions.settings.propWork.desc": "A propriedade da nota de envio que liga à obra.",
    "submissions.settings.propMarket": "Propriedade do destino",
    "submissions.settings.propMarket.desc": "A propriedade que guarda para onde a obra foi enviada.",
    "submissions.settings.propSent": "Propriedade da data de envio",
    "submissions.settings.propSent.desc": "A propriedade que guarda o dia do envio.",
    "submissions.settings.propResult": "Propriedade do resultado",
    "submissions.settings.propResult.desc": "A propriedade que guarda o resultado (os valores são definidos acima).",
    "submissions.settings.propResponded": "Propriedade da data da resposta",
    "submissions.settings.propResponded.desc": "A propriedade que guarda o dia da resposta. Fica vazia numa nota nova.",
    "settings.features.off.submissions.one": "Envios desligados. A {n} nota de envio continua em {folder}.",
    "settings.features.off.submissions.other": "Envios desligados. As {n} notas de envio continuam em {folder}.",
    "settings.features.off.submissions.none": "Envios desligados.",
  },
};
