import type { Strings } from "../i18n";

// Task 3.5 registers these in main.ts (registerStrings(exportStrings)). Copy follows
// the approved boards 26 and 27 (pt-BR); the English is the same sentence.
export const exportStrings: Strings = {
  en: {
    "export.command": "Export…",
    "export.againCommand": "Export again",
    "export.menu": "Export…",

    "export.title": "Export “{title}”",
    "export.what": "What",
    "export.what.note": "This note",
    "export.what.chapter": "This chapter",
    "export.what.book": "The whole book",
    "export.chapters": "Chapters",
    "export.chapters.all": "All ({n})",
    "export.chapters.from": "From",
    "export.chapters.fromLabel": "From chapter",
    "export.chapters.toLabel": "To chapter",
    "export.chapters.to": "to",
    "export.chapters.pick": "Choose…",
    "export.chapters.picked": "{n} of {total} chosen",
    "export.chapters.left.one": "{n} chapter is always left out: {names} ({property}: false).",
    "export.chapters.left.other": "{n} chapters are always left out: {names} ({property}: false).",
    "export.chapters.none": "No chapter is chosen.",
    "export.picker.all": "All",
    "export.picker.none": "None",
    "export.picker.ok": "OK",
    "export.format": "Format",
    "export.format.docx": "DOCX",
    "export.format.md": "Markdown",
    "export.format.epub": "EPUB",
    "export.preset": "Template",
    "export.preset.shunn": "Shunn",
    "export.preset.shunn.hint": "Letter, English",
    "export.preset.ptbr": "pt-BR",
    "export.preset.ptbr.hint": "A4, dialogue dash",

    "export.where": "Writes {path}.",
    "export.where.note": "Short story: the title opens the first page, below the contact, with {count}.",
    "export.where.book": "Title page with {count}.",
    "export.where.bookFront": "Title page with {count}, {front} from the book note.",
    "export.where.epub": "A reading column: title page, contents and one page per chapter. No word count.",
    "export.where.epubCover": "A reading column: cover, title page, contents and one page per chapter. No word count.",
    "export.where.front.dedication": "dedication",
    "export.where.front.epigraph": "epigraph",
    "export.where.front.both": "dedication and epigraph",
    "export.about.words": "about {n} words",
    "export.about.characters": "about {n} characters",
    "export.about.characters-no-spaces": "about {n} characters, no spaces",
    "export.last": "Last export: {summary} · {when} · ",
    "export.last.chapters.one": "{n} chapter",
    "export.last.chapters.other": "{n} chapters",
    "export.last.gone": "(file moved or gone)",

    "export.again": "Export again",
    "export.cancel": "Cancel",
    "export.previewButton": "Preview",
    "export.button": "Export",
    "export.buttonAnyway": "Export anyway",
    "export.reading": "Reading the text…",
    "export.readError": "Couldn't read the text to export. Nothing was written; see the developer console.",

    "export.warn.title": "Before you send",
    "export.warn.placeholders.one": "{n} {marker} marker is left in the text",
    "export.warn.placeholders.other": "{n} {marker} markers are left in the text",
    "export.warn.unclosedComment": "A %% comment never closes: the rest of the note disappears",
    "export.warn.unclosedHtmlComment": "A <!-- comment never closes: the rest of the note disappears",
    "export.warn.unwrittenBeats.one": "{n} beat has no prose after it",
    "export.warn.unwrittenBeats.other": "{n} beats have no prose after them",
    "export.warn.emptyBody": "The note has no text",
    "export.warn.cover": "The cover “{names}” is missing, can’t be read or isn’t a JPEG or PNG: the EPUB goes without a cover",
    "export.warn.embeds.one": "{n} embedded item is left out ({names})",
    "export.warn.embeds.other": "{n} embedded items are left out ({names})",
    "export.warn.line": "line {line}",
    "export.warn.lineIn": "{where}, line {line}",
    "export.warn.go": "Go to line {line} of {where}",
    "export.warn.more": "+{n}",

    "export.preview.crumbOptions": "Options",
    "export.preview.crumb": "Preview",
    "export.preview.back": "Back",
    "export.preview.hint": "Click a paragraph to open the note there.",
    "export.preview.tip": "Open {where}, line {line}",
    "export.preview.zone.dedication": "dedication",
    "export.preview.zone.epigraph": "epigraph",
    "export.preview.zone.text": "text",
    "export.preview.zone.cover": "cover",
    "export.preview.zone.contents": "contents",
    "export.preview.label": "Export preview",
    "export.preview.summary": "{format} · {preset}",

    "export.exists.title": "The file already exists",
    "export.exists.body": "{path} is from {date}.",
    "export.exists.cancel": "Cancel",
    "export.exists.both": "Keep both",
    "export.exists.replace": "Replace",
    "export.where.title": "Where to write",
    "export.where.ask": "The last export is not where it was written. Write {path}?",
    "export.where.write": "Write",

    "export.done": "Exported: {name}.",
    "export.done.show": "Show in the file explorer",
    "export.error": "Couldn't write the export. Nothing was changed; see the developer console.",
    "export.errorFolder": "Couldn't write the export: {path} is a folder.",
    "export.notExportable": "Open a Markdown note to export it.",
    "export.noLast": "This work has no export to repeat yet.",

    "export.settings.heading": "Export",
    "export.settings.folder": "Export folder",
    "export.settings.folder.desc": "Where exported manuscripts are written. Notes in it are never counted or treated as works.",
    "export.settings.compile": "Left-out property",
    "export.settings.compile.desc": "A chapter whose property is false stays out of an export. For example, compile: false.",
    "export.settings.dedication": "Dedication property",
    "export.settings.dedication.desc": "On the book note: a link to the note whose text becomes the dedication page.",
    "export.settings.epigraph": "Epigraph property",
    "export.settings.epigraph.desc": "On the book note: a link to the note whose text becomes the epigraph page.",
    "export.settings.authorProperty": "Author property",
    "export.settings.authorProperty.desc": "A property on the work that names its author on the title page. When a work has it, its value overrides the author name below.",
    "export.settings.heading.format.placeholder": "Empty: the template's heading",
    "export.settings.authorName": "Author name",
    "export.settings.authorName.desc": "On the title page. An author property on a note or book overrides it.",
    "export.settings.authorSurname": "Surname for the header",
    "export.settings.authorSurname.desc": "The manuscript header reads Surname / Title / page. Empty uses the last word of the name.",
    "export.settings.contact": "Contact lines",
    "export.settings.contact.desc": "Address, email, phone: one line each, at the top of the title page.",
    "export.settings.heading.format": "Chapter heading",
    "export.settings.heading.format.desc": "Use {n} for the number and {title} for the title. Empty uses the template's own.",
    "export.settings.cover": "Cover property",
    "export.settings.cover.desc": "On the book note, or on a note exported alone: a link to a JPEG or PNG image in the vault, used as the EPUB cover.",
    "export.settings.epubBreak": "EPUB scene break",
    "export.settings.epubBreak.desc": "The line an EPUB shows between scenes, never at the start or end of a chapter. Not the template's # (that one is for manuscripts).",
    "export.settings.collection": "Collection property",
    "export.settings.collection.desc": "A note with this property, a list of links to short stories in reading order, exports like a book.",
  },
  "pt-BR": {
    "export.command": "Exportar…",
    "export.againCommand": "Exportar de novo",
    "export.menu": "Exportar…",

    "export.title": "Exportar “{title}”",
    "export.what": "O quê",
    "export.what.note": "Esta nota",
    "export.what.chapter": "Este capítulo",
    "export.what.book": "O livro inteiro",
    "export.chapters": "Capítulos",
    "export.chapters.all": "Todos ({n})",
    "export.chapters.from": "Do",
    "export.chapters.fromLabel": "Do capítulo",
    "export.chapters.toLabel": "Ao capítulo",
    "export.chapters.to": "ao",
    "export.chapters.pick": "Escolher…",
    "export.chapters.picked": "{n} de {total} escolhidos",
    "export.chapters.left.one": "{n} capítulo fica de fora sempre: {names} ({property}: false).",
    "export.chapters.left.other": "{n} capítulos ficam de fora sempre: {names} ({property}: false).",
    "export.chapters.none": "Nenhum capítulo escolhido.",
    "export.picker.all": "Todos",
    "export.picker.none": "Nenhum",
    "export.picker.ok": "OK",
    "export.format": "Formato",
    "export.format.docx": "DOCX",
    "export.format.md": "Markdown",
    "export.format.epub": "EPUB",
    "export.preset": "Modelo",
    "export.preset.shunn": "Shunn",
    "export.preset.shunn.hint": "Carta, inglês",
    "export.preset.ptbr": "pt-BR",
    "export.preset.ptbr.hint": "A4, travessão",

    "export.where": "Grava {path}.",
    "export.where.note": "Conto: o título abre a primeira página, abaixo do contato, com {count}.",
    "export.where.book": "Folha de rosto com {count}.",
    "export.where.bookFront": "Folha de rosto com {count}, {front} da nota do livro.",
    "export.where.epub": "Uma coluna de leitura: folha de rosto, sumário e uma página por capítulo. Sem contagem de palavras.",
    "export.where.epubCover": "Uma coluna de leitura: capa, folha de rosto, sumário e uma página por capítulo. Sem contagem de palavras.",
    "export.where.front.dedication": "dedicatória",
    "export.where.front.epigraph": "epígrafe",
    "export.where.front.both": "dedicatória e epígrafe",
    "export.about.words": "cerca de {n} palavras",
    "export.about.characters": "cerca de {n} caracteres",
    "export.about.characters-no-spaces": "cerca de {n} caracteres, sem espaços",
    "export.last": "Última exportação: {summary} · {when} · ",
    "export.last.chapters.one": "{n} capítulo",
    "export.last.chapters.other": "{n} capítulos",
    "export.last.gone": "(arquivo movido ou apagado)",

    "export.again": "Exportar de novo",
    "export.cancel": "Cancelar",
    "export.previewButton": "Prévia",
    "export.button": "Exportar",
    "export.buttonAnyway": "Exportar mesmo assim",
    "export.reading": "Lendo o texto…",
    "export.readError": "Não deu para ler o texto a exportar. Nada foi gravado; veja o console do desenvolvedor.",

    "export.warn.title": "Antes de enviar",
    "export.warn.placeholders.one": "{n} marcador {marker} ficou no texto",
    "export.warn.placeholders.other": "{n} marcadores {marker} ficaram no texto",
    "export.warn.unclosedComment": "Um comentário %% sem fechamento: o resto da nota some",
    "export.warn.unclosedHtmlComment": "Um <!-- sem fechamento: o resto da nota some",
    "export.warn.unwrittenBeats.one": "{n} beat sem texto depois",
    "export.warn.unwrittenBeats.other": "{n} beats sem texto depois",
    "export.warn.emptyBody": "A nota não tem texto",
    "export.warn.cover": "A capa “{names}” não existe, não abre ou não é JPEG nem PNG: o EPUB sai sem capa",
    "export.warn.embeds.one": "{n} item incorporado fica de fora ({names})",
    "export.warn.embeds.other": "{n} itens incorporados ficam de fora ({names})",
    "export.warn.line": "linha {line}",
    "export.warn.lineIn": "{where}, linha {line}",
    "export.warn.go": "Ir para a linha {line} de {where}",
    "export.warn.more": "+{n}",

    "export.preview.crumbOptions": "Opções",
    "export.preview.crumb": "Prévia",
    "export.preview.back": "Voltar",
    "export.preview.hint": "Clique num parágrafo para abrir a nota nele.",
    "export.preview.tip": "Abrir {where}, linha {line}",
    "export.preview.zone.dedication": "dedicatória",
    "export.preview.zone.epigraph": "epígrafe",
    "export.preview.zone.text": "texto",
    "export.preview.zone.cover": "capa",
    "export.preview.zone.contents": "sumário",
    "export.preview.label": "Prévia da exportação",
    "export.preview.summary": "{format} · {preset}",

    "export.exists.title": "O arquivo já existe",
    "export.exists.body": "{path} é de {date}.",
    "export.exists.cancel": "Cancelar",
    "export.exists.both": "Manter os dois",
    "export.exists.replace": "Substituir",
    "export.where.title": "Onde gravar",
    "export.where.ask": "A última exportação não está onde foi gravada. Gravar {path}?",
    "export.where.write": "Gravar",

    "export.done": "Exportado: {name}.",
    "export.done.show": "Abrir a pasta",
    "export.error": "Não deu para gravar a exportação. Nada foi alterado; veja o console do desenvolvedor.",
    "export.errorFolder": "Não deu para gravar a exportação: {path} é uma pasta.",
    "export.notExportable": "Abra uma nota Markdown para exportar.",
    "export.noLast": "Esta obra ainda não tem exportação para repetir.",

    "export.settings.heading": "Exportação",
    "export.settings.folder": "Pasta das exportações",
    "export.settings.folder.desc": "Onde os manuscritos exportados são gravados. Notas dentro dela nunca são contadas nem tratadas como obras.",
    "export.settings.compile": "Propriedade que deixa de fora",
    "export.settings.compile.desc": "Um capítulo cuja propriedade é false fica fora da exportação. Por exemplo, compile: false.",
    "export.settings.dedication": "Propriedade da dedicatória",
    "export.settings.dedication.desc": "Na nota do livro: um link para a nota cujo texto vira a página de dedicatória.",
    "export.settings.epigraph": "Propriedade da epígrafe",
    "export.settings.epigraph.desc": "Na nota do livro: um link para a nota cujo texto vira a página de epígrafe.",
    "export.settings.authorProperty": "Propriedade do autor",
    "export.settings.authorProperty.desc": "Uma propriedade da obra que dá o nome do autor na folha de rosto. Quando a obra a tem, o valor dela substitui o nome do autor abaixo.",
    "export.settings.heading.format.placeholder": "Vazio: o título do modelo",
    "export.settings.authorName": "Nome do autor",
    "export.settings.authorName.desc": "Na folha de rosto. Uma propriedade author na nota ou no livro tem preferência.",
    "export.settings.authorSurname": "Sobrenome do cabeçalho",
    "export.settings.authorSurname.desc": "O cabeçalho do manuscrito é Sobrenome / Título / página. Vazio usa a última palavra do nome.",
    "export.settings.contact": "Linhas de contato",
    "export.settings.contact.desc": "Endereço, e-mail, telefone: uma por linha, no topo da folha de rosto.",
    "export.settings.heading.format": "Título do capítulo",
    "export.settings.heading.format.desc": "Use {n} para o número e {title} para o título. Vazio usa o do modelo.",
    "export.settings.cover": "Propriedade da capa",
    "export.settings.cover.desc": "Na nota do livro, ou numa nota exportada sozinha: um link para uma imagem JPEG ou PNG do cofre, usada como capa do EPUB.",
    "export.settings.epubBreak": "Quebra de cena do EPUB",
    "export.settings.epubBreak.desc": "A linha que o EPUB mostra entre cenas, nunca no começo nem no fim de um capítulo. Não é o # do modelo (esse é para manuscritos).",
    "export.settings.collection": "Propriedade da coletânea",
    "export.settings.collection.desc": "Uma nota com esta propriedade, uma lista de links para contos na ordem de leitura, é exportada como um livro.",
  },
};
