import type { Strings } from "../i18n";

export const placeholdersStrings: Strings = {
  en: {
    "placeholders.cmd.insert": "Insert placeholder",
    "placeholders.cmd.next": "Next placeholder in this note",
    "placeholders.cmd.prev": "Previous placeholder in this note",
    "placeholders.cmd.open": "Open placeholders",
    "placeholders.view.title": "Placeholders",
    "placeholders.scope.book": "This book",
    "placeholders.scope.all": "All notes",
    "placeholders.scope.label": "Show placeholders from",
    "placeholders.scope.noBook": "Open a chapter to see its book",
    "placeholders.indexing": "Looking for placeholders…",
    "placeholders.noNote": "No note",
    "placeholders.line": "Line {n}",
    "placeholders.resolve": "Resolve (removes the placeholder)",
    "placeholders.empty.book": "No placeholders in {book}.",
    "placeholders.empty.all": "No placeholders in your notes.",
    "placeholders.empty.how": "To leave a note for later without stopping, open the command palette (⌘/Ctrl+P) and run “Insert placeholder”. It adds %% {marker}: … %% where you are.",
    "placeholders.empty.howMobile": "To leave a note for later without stopping, open the command palette and run “Insert placeholder”. It adds %% {marker}: … %% where you are. Tip: add it to the mobile toolbar in Settings → Toolbar.",
    "placeholders.empty.hotkey": "Tip: bind it to a hotkey such as Ctrl/Cmd+Shift+X in Settings → Hotkeys.",
    "placeholders.noneInNote": "No placeholders in this note.",
    "placeholders.moved": "This placeholder has moved or changed. The list is being updated.",
    "placeholders.notFound": "This placeholder isn't where it was anymore, so nothing was changed.",
    "placeholders.openFailed": "Couldn't open this note. Check the console for details.",
  },
  "pt-BR": {
    "placeholders.cmd.insert": "Inserir marcador",
    "placeholders.cmd.next": "Próximo marcador nesta nota",
    "placeholders.cmd.prev": "Marcador anterior nesta nota",
    "placeholders.cmd.open": "Abrir marcadores",
    "placeholders.view.title": "Marcadores",
    "placeholders.scope.book": "Este livro",
    "placeholders.scope.all": "Todas as notas",
    "placeholders.scope.label": "Mostrar marcadores de",
    "placeholders.scope.noBook": "Abra um capítulo para ver o livro dele",
    "placeholders.indexing": "Procurando marcadores…",
    "placeholders.noNote": "Sem nota",
    "placeholders.line": "Linha {n}",
    "placeholders.resolve": "Resolver (remove o marcador)",
    "placeholders.empty.book": "Nenhum marcador em {book}.",
    "placeholders.empty.all": "Nenhum marcador nas suas notas.",
    "placeholders.empty.how": "Para deixar um lembrete sem parar de escrever, abra a paleta de comandos (⌘/Ctrl+P) e rode “Inserir marcador”. Ele coloca %% {marker}: … %% onde você está.",
    "placeholders.empty.howMobile": "Para deixar um lembrete sem parar de escrever, abra a paleta de comandos e rode “Inserir marcador”. Ele coloca %% {marker}: … %% onde você está. Dica: adicione o comando à barra de ferramentas em Configurações → Barra de ferramentas.",
    "placeholders.empty.hotkey": "Dica: associe um atalho, como Ctrl/Cmd+Shift+X, em Configurações → Teclas de atalho.",
    "placeholders.noneInNote": "Nenhum marcador nesta nota.",
    "placeholders.moved": "Este marcador mudou de lugar ou foi alterado. A lista está sendo atualizada.",
    "placeholders.notFound": "Este marcador não está mais onde estava, então nada foi alterado.",
    "placeholders.openFailed": "Não foi possível abrir esta nota. Veja o console para detalhes.",
  },
};
