import type { Strings } from "../i18n";

// The revision lens: command names, rule names, panel and notice texts (task 4.2).
export const lensStrings: Strings = {
  en: {
    "lens.cmd.toggle": "Toggle revision lens",
    "lens.cmd.createLists": "Create the word lists note",
    "lens.cmd.next": "Next revision lens match",
    "lens.cmd.prev": "Previous revision lens match",
    "lens.rule.echo": "Echoes",
    "lens.rule.adverb": "Adverbs",
    "lens.rule.gerund": "Gerunds",
    "lens.rule.gerund.en": "Started to",
    "lens.rule.crutch": "Crutch words",
    "lens.rule.name": "Name variants",
    "lens.rule.long": "Long sentences",
    "lens.view.title": "Revision lens",
    "lens.view.subtitle.one": "{name} · {n} word",
    "lens.view.subtitle.other": "{name} · {n} words",
    "lens.selection.one": "Selection · {n} word",
    "lens.selection.other": "Selection · {n} words",
    "lens.measure.dialogue": "Dialogue",
    "lens.measure.scene": "Scene {n}",
    "lens.measure.readability": "Readability",
    "lens.measure.perSentence": "{asl} words per sentence · {asw} syllables per word",
    "lens.measure.short": "Needs at least {words} words and {sentences} sentences.",
    "lens.rules.heading": "Rules · whole note",
    "lens.rate.header": "per 1,000 words",
    "lens.ruleOne.echo": "Echo",
    "lens.ruleOne.adverb": "Adverb",
    "lens.ruleOne.gerund": "Gerund",
    "lens.ruleOne.gerund.en": "Started to",
    "lens.ruleOne.crutch": "Crutch word",
    "lens.ruleOne.name": "Name variant",
    "lens.ruleOne.long": "Long sentence",
    "lens.step.prev.echo": "Previous echo",
    "lens.step.next.echo": "Next echo",
    "lens.step.prev.adverb": "Previous adverb",
    "lens.step.next.adverb": "Next adverb",
    "lens.step.prev.gerund": "Previous gerund",
    "lens.step.next.gerund": "Next gerund",
    "lens.step.prev.crutch": "Previous crutch word",
    "lens.step.next.crutch": "Next crutch word",
    "lens.step.prev.name": "Previous name variant",
    "lens.step.next.name": "Next name variant",
    "lens.step.prev.long": "Previous long sentence",
    "lens.step.next.long": "Next long sentence",
    "lens.step.counter": "{n} / {of}",
    "lens.step.ignore": "Ignore here",
    "lens.menu.ignore": "Ignore here",
    "lens.menu.header": "{rule}: {word}",
    "lens.menu.addCrutch": "Add to crutch words",
    "lens.menu.addNames": "Add to names",
    "lens.menu.addIgnore": "Always ignore",
    "lens.notice.added.crutch": "Added to crutch words: «{word}»",
    "lens.notice.added.names": "Added to names: «{word}»",
    "lens.notice.added.ignore": "Added to ignored words: «{word}»",
    "lens.notice.already": "Already in the list",
    "lens.rule.newName": "Names without an entry",
    "lens.ruleOne.newName": "Name without an entry",
    "lens.step.prev.newName": "Previous name without an entry",
    "lens.step.next.newName": "Next name without an entry",
    "lens.newName.inNote.one": "{n} in the note",
    "lens.newName.inNote.other": "{n} in the note",
    "lens.newName.inWorks.one": "{n} work",
    "lens.newName.inWorks.other": "{n} works",
    "lens.newName.create": "Create entry",
    "lens.newName.create.label": "Create an entry for {name}",
    "lens.newName.dismiss": "Dismiss",
    "lens.newName.dismiss.label": "Dismiss {name}: it is not a name",
    "lens.newName.list": "Names without an entry",
    "lens.newName.counting": "counting in the other works…",
    "lens.newName.needsUniverse": "Needs the universe. Turn on a universe mode in settings.",
    "lens.notice.notName": "«{word}» added to Not names",
    "lens.notice.notNameAlready": "Already in Not names",
    "settings.lens.rule.newName.desc": "Capitalized names that come back and have no entry in your universe. Off until you turn it on; it needs a universe mode.",
    "settings.lens.notNames": "Not names",
    "settings.lens.notNames.desc": "Words the names rule never marks, one per line. Dismissing a name in the lens panel adds it here.",
    "lens.empty.off": "The lens is off for this note. It only suggests: it never changes your text.",
    "lens.empty.turnOn": "Turn on",
    "lens.empty.notMarkdown": "Open a note to see the lens.",
    "lens.empty.noLang": "Choose a language in settings for echoes, adverbs, gerunds and readability.",
    "lens.empty.openSettings": "Open settings",
    "lens.lists.add": "Add a word lists note.",
    "lens.lists.create": "Create",
    "lens.lists.missing": "Word lists note not found: {path}",
    "lens.ignored.one": "{n} ignored",
    "lens.ignored.other": "{n} ignored",
    "lens.ignored.clear": "Clear",
    "lens.confirm.one": "Show the ignored match in this note again?",
    "lens.confirm.other": "Show the {n} ignored matches in this note again?",
    "lens.confirm.cancel": "Cancel",
    "lens.confirm.show": "Show",
    "lens.notice.reading": "The revision lens works in editing mode. Leave Reading view to use it.",
    "lens.notice.listsExists": "The word lists note already exists: {path}. Opening it.",
    "lens.notice.listsCreated": "Word lists note created: {path}. Write your words under each heading.",
    "lens.notice.step": "{rule} · {n} / {of}",
    "lens.notice.listsFailed": "Couldn't create the word lists note: {path}",
    "lens.band.pt.veryEasy": "very easy",
    "lens.band.pt.veryEasy.meaning": "Short sentences and common words. Reads in one breath.",
    "lens.band.pt.easy": "easy",
    "lens.band.pt.easy.meaning": "Medium sentences and words. Reads without effort.",
    "lens.band.pt.hard": "difficult",
    "lens.band.pt.hard.meaning": "Long sentences or long words. The reader has to slow down.",
    "lens.band.pt.veryHard": "very difficult",
    "lens.band.pt.veryHard.meaning": "Dense text. Expect to reread.",
    "lens.band.en.veryEasy": "very easy",
    "lens.band.en.veryEasy.meaning": "Short sentences and plain words.",
    "lens.band.en.easy": "easy",
    "lens.band.en.easy.meaning": "Conversational. Reads without effort.",
    "lens.band.en.fairlyEasy": "fairly easy",
    "lens.band.en.fairlyEasy.meaning": "Plain and clear, with some longer sentences.",
    "lens.band.en.standard": "standard",
    "lens.band.en.standard.meaning": "Average difficulty for adult readers.",
    "lens.band.en.fairlyHard": "fairly difficult",
    "lens.band.en.fairlyHard.meaning": "Longer sentences or words. Needs some attention.",
    "lens.band.en.hard": "difficult",
    "lens.band.en.hard.meaning": "Dense. The reader has to slow down.",
    "lens.band.en.veryHard": "very difficult",
    "lens.band.en.veryHard.meaning": "Very dense text. Expect to reread.",
  },
  "pt-BR": {
    "lens.cmd.toggle": "Ativar ou desativar a lente de revisão",
    "lens.cmd.createLists": "Criar a nota de listas de palavras",
    "lens.cmd.next": "Próxima ocorrência da lente de revisão",
    "lens.cmd.prev": "Ocorrência anterior da lente de revisão",
    "lens.rule.echo": "Ecos",
    "lens.rule.adverb": "Advérbios",
    "lens.rule.gerund": "Gerúndios",
    "lens.rule.gerund.en": "Started to",
    "lens.rule.crutch": "Vícios",
    "lens.rule.name": "Variantes de nome",
    "lens.rule.long": "Frases longas",
    "lens.view.title": "Lente de revisão",
    "lens.view.subtitle.one": "{name} · {n} palavra",
    "lens.view.subtitle.other": "{name} · {n} palavras",
    "lens.selection.one": "Seleção · {n} palavra",
    "lens.selection.other": "Seleção · {n} palavras",
    "lens.measure.dialogue": "Diálogo",
    "lens.measure.scene": "Cena {n}",
    "lens.measure.readability": "Legibilidade",
    "lens.measure.perSentence": "{asl} palavras por frase · {asw} sílabas por palavra",
    "lens.measure.short": "Precisa de pelo menos {words} palavras e {sentences} frases.",
    "lens.rules.heading": "Regras · na nota inteira",
    "lens.rate.header": "por 1.000 palavras",
    "lens.ruleOne.echo": "Eco",
    "lens.ruleOne.adverb": "Advérbio",
    "lens.ruleOne.gerund": "Gerúndio",
    "lens.ruleOne.gerund.en": "Started to",
    "lens.ruleOne.crutch": "Vício",
    "lens.ruleOne.name": "Variante de nome",
    "lens.ruleOne.long": "Frase longa",
    "lens.step.prev.echo": "Eco anterior",
    "lens.step.next.echo": "Próximo eco",
    "lens.step.prev.adverb": "Advérbio anterior",
    "lens.step.next.adverb": "Próximo advérbio",
    "lens.step.prev.gerund": "Gerúndio anterior",
    "lens.step.next.gerund": "Próximo gerúndio",
    "lens.step.prev.crutch": "Vício anterior",
    "lens.step.next.crutch": "Próximo vício",
    "lens.step.prev.name": "Variante anterior",
    "lens.step.next.name": "Próxima variante",
    "lens.step.prev.long": "Frase longa anterior",
    "lens.step.next.long": "Próxima frase longa",
    "lens.step.counter": "{n} / {of}",
    "lens.step.ignore": "Ignorar aqui",
    "lens.menu.ignore": "Ignorar aqui",
    "lens.menu.header": "{rule}: {word}",
    "lens.menu.addCrutch": "Adicionar aos vícios",
    "lens.menu.addNames": "Adicionar aos nomes",
    "lens.menu.addIgnore": "Ignorar sempre",
    "lens.notice.added.crutch": "Adicionado aos vícios: «{word}»",
    "lens.notice.added.names": "Adicionado aos nomes: «{word}»",
    "lens.notice.added.ignore": "Adicionado às palavras ignoradas: «{word}»",
    "lens.notice.already": "Já está na lista",
    "lens.rule.newName": "Nomes sem entrada",
    "lens.ruleOne.newName": "Nome sem entrada",
    "lens.step.prev.newName": "Nome sem entrada anterior",
    "lens.step.next.newName": "Próximo nome sem entrada",
    "lens.newName.inNote.one": "{n} na nota",
    "lens.newName.inNote.other": "{n} na nota",
    "lens.newName.inWorks.one": "{n} obra",
    "lens.newName.inWorks.other": "{n} obras",
    "lens.newName.create": "Criar entrada",
    "lens.newName.create.label": "Criar uma entrada para {name}",
    "lens.newName.dismiss": "Dispensar",
    "lens.newName.dismiss.label": "Dispensar {name}: não é um nome",
    "lens.newName.list": "Nomes sem entrada",
    "lens.newName.counting": "contando nas outras obras…",
    "lens.newName.needsUniverse": "Precisa do universo. Ative um modo de universo nas configurações.",
    "lens.notice.notName": "«{word}» adicionada a Não são nomes",
    "lens.notice.notNameAlready": "Já está em Não são nomes",
    "settings.lens.rule.newName.desc": "Nomes com inicial maiúscula que voltam e não têm entrada no universo. Desligada até você ativar; precisa de um modo de universo.",
    "settings.lens.notNames": "Não são nomes",
    "settings.lens.notNames.desc": "Palavras que a regra de nomes nunca marca, uma por linha. Dispensar um nome no painel da lente o adiciona aqui.",
    "lens.empty.off": "A lente está desligada nesta nota. Ela só sugere: nunca muda o texto.",
    "lens.empty.turnOn": "Ligar",
    "lens.empty.notMarkdown": "Abra uma nota para ver a lente.",
    "lens.empty.noLang": "Escolha um idioma nas configurações para ecos, advérbios, gerúndios e legibilidade.",
    "lens.empty.openSettings": "Abrir configurações",
    "lens.lists.add": "Adicione uma nota de listas de palavras.",
    "lens.lists.create": "Criar",
    "lens.lists.missing": "Nota de listas não encontrada: {path}",
    "lens.ignored.one": "{n} ignorada",
    "lens.ignored.other": "{n} ignoradas",
    "lens.ignored.clear": "Limpar",
    "lens.confirm.one": "Voltar a mostrar a ocorrência ignorada nesta nota?",
    "lens.confirm.other": "Voltar a mostrar as {n} ocorrências ignoradas nesta nota?",
    "lens.confirm.cancel": "Cancelar",
    "lens.confirm.show": "Mostrar",
    "lens.notice.reading": "A lente de revisão funciona no modo de edição. Saia do modo de leitura para usá-la.",
    "lens.notice.listsExists": "A nota de listas já existe: {path}. Abrindo a nota.",
    "lens.notice.listsCreated": "Nota de listas criada: {path}. Escreva suas palavras sob cada título.",
    "lens.notice.step": "{rule} · {n} / {of}",
    "lens.notice.listsFailed": "Não foi possível criar a nota de listas: {path}",
    "lens.band.pt.veryEasy": "muito fácil",
    "lens.band.pt.veryEasy.meaning": "Frases curtas e palavras comuns. Lê-se de uma vez.",
    "lens.band.pt.easy": "fácil",
    "lens.band.pt.easy.meaning": "Frases e palavras de tamanho médio. Lê-se sem esforço.",
    "lens.band.pt.hard": "difícil",
    "lens.band.pt.hard.meaning": "Frases ou palavras longas. O leitor precisa desacelerar.",
    "lens.band.pt.veryHard": "muito difícil",
    "lens.band.pt.veryHard.meaning": "Texto denso. Espere reler.",
    "lens.band.en.veryEasy": "muito fácil",
    "lens.band.en.veryEasy.meaning": "Frases curtas e palavras simples.",
    "lens.band.en.easy": "fácil",
    "lens.band.en.easy.meaning": "Tom de conversa. Lê-se sem esforço.",
    "lens.band.en.fairlyEasy": "razoavelmente fácil",
    "lens.band.en.fairlyEasy.meaning": "Claro e simples, com algumas frases mais longas.",
    "lens.band.en.standard": "padrão",
    "lens.band.en.standard.meaning": "Dificuldade média para leitores adultos.",
    "lens.band.en.fairlyHard": "razoavelmente difícil",
    "lens.band.en.fairlyHard.meaning": "Frases ou palavras mais longas. Pede alguma atenção.",
    "lens.band.en.hard": "difícil",
    "lens.band.en.hard.meaning": "Denso. O leitor precisa desacelerar.",
    "lens.band.en.veryHard": "muito difícil",
    "lens.band.en.veryHard.meaning": "Texto muito denso. Espere reler.",
  },
};
