import type { Strings } from "../i18n";

export const darlingsStrings: Strings = {
  en: {
    "darlings.cmd.move": "Move selection to darlings",
    "darlings.cmd.open": "Open darlings",
    "darlings.menu.move": "Move to darlings",
    "darlings.view.title": "Darlings",
    "darlings.intro": "Passages cut while revising, kept safe. Restore them from the Darlings panel.",
    "darlings.openNote": "Open the darlings note",
    "darlings.count": "{n} darlings",
    "darlings.count.one": "1 darling",
    "darlings.empty": "No darlings yet",
    "darlings.empty.hint": "Select a passage you can't bear to delete and choose “Move selection to darlings” from the command palette or the editor's context menu (on mobile, add it to the toolbar). It waits here, ready to go back where it was.",
    "darlings.emptyPassage": "(empty passage)",
    "darlings.restore": "Restore",
    "darlings.openSource": "Open source",
    "darlings.delete": "Delete",
    "darlings.cancel": "Cancel",
    "darlings.notice.moved": "Moved to darlings — restore it from the Darlings panel.",
    "darlings.notice.changed": "The text changed while saving, so the passage was copied to darlings but left in place.",
    "darlings.notice.changedNothing": "The text changed while saving, so nothing was moved. Select the passage and try again.",
    "darlings.notice.alreadyThere": "The passage was already back in “{title}”, so it was only removed from darlings.",
    "darlings.notice.notRemoved": "Restored to “{title}”, but it couldn't be removed from the darlings note. Delete it there so it isn't restored twice.",
    "darlings.notice.actionFailed": "Something went wrong: {error}",
    "darlings.notice.sameNote": "This is already the darlings note.",
    "darlings.notice.failed": "Couldn't save to darlings, nothing was removed: {error}",
    "darlings.notice.restored": "Restored to “{title}”.",
    "darlings.notice.restoredEnd": "The text around it has changed, so it went at the end of “{title}”.",
    "darlings.notice.gone": "This darling is no longer in the darlings note.",
    "darlings.notice.sourceMissing": "“{title}” no longer exists. Open the note you want to paste it into, then try again.",
    "darlings.notice.noEditor": "Open a note to paste it into, then try again.",
    "darlings.notice.error": "Couldn't restore the darling: {error}",
    "darlings.error.notAFile": "{path} is a folder, not a note.",
    "darlings.error.notAFolder": "{path} is a file, not a folder.",
    "darlings.missing.title": "Source note not found",
    "darlings.missing.body": "“{title}” no longer exists. Paste the passage at the cursor in “{active}” instead?",
    "darlings.missing.paste": "Paste here",
    "darlings.delete.title": "Delete this darling?",
    "darlings.delete.body": "The passage cut from “{title}” will be removed from the darlings note. If the core File recovery plugin is on, it can still bring it back.",
    "darlings.delete.confirm": "Delete",
  },
  "pt-BR": {
    "darlings.cmd.move": "Mover seleção para os darlings",
    "darlings.cmd.open": "Abrir darlings",
    "darlings.menu.move": "Mover para os darlings",
    "darlings.view.title": "Darlings",
    "darlings.intro": "Trechos cortados na revisão, guardados com carinho. Restaure-os pelo painel Darlings.",
    "darlings.openNote": "Abrir a nota de darlings",
    "darlings.count": "{n} darlings",
    "darlings.count.one": "1 darling",
    "darlings.empty": "Nenhum darling por enquanto",
    "darlings.empty.hint": "Selecione um trecho que você não tem coragem de apagar e escolha “Mover seleção para os darlings” na paleta de comandos ou no menu de contexto do editor (no celular, adicione-o à barra de ferramentas). Ele fica guardado aqui, pronto para voltar para onde estava.",
    "darlings.emptyPassage": "(trecho vazio)",
    "darlings.restore": "Restaurar",
    "darlings.openSource": "Abrir origem",
    "darlings.delete": "Excluir",
    "darlings.cancel": "Cancelar",
    "darlings.notice.moved": "Movido para os darlings — restaure pelo painel Darlings.",
    "darlings.notice.changed": "O texto mudou enquanto salvava: o trecho foi copiado para os darlings, mas continua no lugar.",
    "darlings.notice.changedNothing": "O texto mudou enquanto salvava, então nada foi movido. Selecione o trecho e tente de novo.",
    "darlings.notice.alreadyThere": "O trecho já tinha voltado para “{title}”, então só foi retirado dos darlings.",
    "darlings.notice.notRemoved": "Restaurado em “{title}”, mas não deu para retirá-lo da nota de darlings. Exclua-o lá para não restaurar duas vezes.",
    "darlings.notice.actionFailed": "Algo deu errado: {error}",
    "darlings.notice.sameNote": "Esta já é a nota de darlings.",
    "darlings.notice.failed": "Não deu para salvar nos darlings, nada foi removido: {error}",
    "darlings.notice.restored": "Restaurado em “{title}”.",
    "darlings.notice.restoredEnd": "O texto em volta mudou, então o trecho foi para o fim de “{title}”.",
    "darlings.notice.gone": "Este darling não está mais na nota de darlings.",
    "darlings.notice.sourceMissing": "“{title}” não existe mais. Abra a nota onde quer colar o trecho e tente de novo.",
    "darlings.notice.noEditor": "Abra uma nota para colar o trecho e tente de novo.",
    "darlings.notice.error": "Não deu para restaurar o darling: {error}",
    "darlings.error.notAFile": "{path} é uma pasta, não uma nota.",
    "darlings.error.notAFolder": "{path} é um arquivo, não uma pasta.",
    "darlings.missing.title": "Nota de origem não encontrada",
    "darlings.missing.body": "“{title}” não existe mais. Colar o trecho no cursor de “{active}”?",
    "darlings.missing.paste": "Colar aqui",
    "darlings.delete.title": "Excluir este darling?",
    "darlings.delete.body": "O trecho cortado de “{title}” será removido da nota de darlings. Se o plugin Recuperação de arquivos estiver ativado, ainda dá para trazê-lo de volta.",
    "darlings.delete.confirm": "Excluir",
  },
};
