import type { Strings } from "../i18n";

// The setup (1.0, task 2.2): the first-run notice, the command, the two-step modal, the
// run's notices, and the plan's reason lines (`setup.reason.*`, the keys setup/plan.ts
// emits). Keys under `setup.` only; the layout's are in layout-strings.ts (`setup.layout.`),
// so the modal's own layout cards are `setup.screen.*`.
// The pt-BR text is boards 35 and 36's wording; the English matches it, in sentence case.
export const setupStrings: Strings = {
  en: {
    "setup.command": "Set up a writing vault",
    "setup.notice.text": "Escrita is ready. Want to set this vault up for writing? I show everything before I create it.",
    "setup.notice.setup": "Set up…",
    "setup.notice.later": "Not now",

    "setup.title": "Set up a writing vault",
    "setup.step.one": "1 · Choices",
    "setup.step.two": "2 · What I'll create",
    "setup.writes.q": "What do you write?",
    "setup.writes.stories": "Short fiction",
    "setup.writes.books": "A novel",
    "setup.writes.both": "Both",
    "setup.language.q": "Language of the defaults",
    "setup.language.hint": "Follows Obsidian's language. Statuses, folders and lists in that language.",
    "setup.language.en": "English",
    "setup.language.pt-BR": "Português (Brasil)",
    "setup.preset.q": "Starting point",
    "setup.preset.essentials": "Essentials",
    "setup.preset.writer": "Writer",
    "setup.preset.everything": "Everything",
    "setup.preset.custom": "Custom",
    "setup.preset.essentials.text": "Outline and beats, goals, placeholders, typing, the lens, darlings, snapshots, export, the home block. {n} of 19.",
    "setup.preset.writer.text": "Essentials plus dialogue focus, moving blocks, templates, publish and submissions. {n} of 19.",
    "setup.preset.everything.text": "All {n}, with spellcheck on demand, threads and the universe.",
    "setup.preset.hint": "A starting point, not a mode: afterwards every switch is yours, in Settings › Escrita › Features.",
    "setup.preset.count": "{preset} ({n} of 19)",
    "setup.world.q": "Shared world",
    "setup.world.off": "Off",
    "setup.world.perBook": "Per book",
    "setup.world.universe": "Universe",
    "setup.world.hint": "Characters and places. You can decide later.",
    "setup.btn.cancel": "Cancel",
    "setup.btn.preview": "See what I'll create",
    "setup.btn.back": "Back",
    "setup.btn.create": "Create",
    "setup.btn.close": "Close",

    "setup.preview.title": "What I'll create",
    "setup.group.folder": "Folders",
    "setup.group.example": "Examples",
    "setup.group.setting": "Settings",
    "setup.group.home": "Home note",
    "setup.group.layout": "Layout",
    "setup.mark.new": "New",
    "setup.mark.kept": "Stays as it is",
    "setup.mark.setting": "Setting",
    "setup.pill.example": "example",
    "setup.pill.kept": "stays",
    "setup.tick": "Include: {name}",
    "setup.screen.title": "Arrange the screen once",
    "setup.screen.hint": "After that the layout is yours; Escrita doesn't touch it again.",
    "setup.screen.desk": "Writing desk",
    "setup.screen.desk.text": "The home note in front. On the right, the outline with its beats on top and the lens below{universe}.",
    "setup.screen.desk.universe": "; the universe on the left",
    "setup.screen.focus": "Writing mode",
    "setup.screen.focus.text": "Only the home note, and today's goal below if Goals is on. Bars and tabs hidden. Leave with the button or the command.",
    "setup.summary.note": "No existing note changes. A folder that already exists is used as it is.",
    "setup.summary.count": "I'll create {items} and change {settings}.",
    "setup.summary.items.one": "{n} item",
    "setup.summary.items.other": "{n} items",
    "setup.summary.settings.one": "{n} setting",
    "setup.summary.settings.other": "{n} settings",
    "setup.summary.nothing": "Everything you chose already exists. Nothing to do.",
    "setup.summary.noneTicked": "Nothing is ticked. Tick a row to create or change it.",

    "setup.setting.defaultsLanguage": "Language of the defaults",
    "setup.setting.stages": "Statuses",
    "setup.setting.chaptersFolder": "Chapters folder",
    "setup.setting.unnumberedTitles": "Unnumbered chapter titles",
    "setup.setting.submissionResults": "Submission results",
    "setup.setting.exportFolder": "Export folder",
    "setup.setting.submissionsFolder": "Submissions folder",
    "setup.setting.darlingsNote": "Darlings note",
    "setup.setting.globalDarlingsNote": "Global darlings note",
    "setup.setting.universeNote": "Universe note",
    "setup.setting.entryTypes": "Entry types",
    "setup.setting.formValues": "Form values",
    "setup.setting.threadKeyword": "Thread keyword",
    "setup.setting.threadClosedWord": "Closed-thread word",
    "setup.setting.trackFolders": "Folders that count",
    "setup.setting.lensLanguage": "Writing language",
    "setup.setting.homeNote": "Home note",
    "setup.setting.openHomeOnStartup": "Open the home note on startup",
    "setup.setting.universeMode": "Shared world",
    "setup.setting.features": "Features",
    "setup.setting.layout": "Arrange the screen once",

    "setup.reason.folderNew": "New. It counts for goals.",
    "setup.reason.folderHasWorks": "Unticked: you already have works. Tick to create it. It would count for goals.",
    "setup.reason.folderExists": "Already exists, stays. {count} notes. Used as it is.",
    "setup.reason.exists": "Already exists, stays.",
    "setup.reason.exampleNew": "An example you can delete without fear.",
    "setup.reason.exampleHasWorks": "Unticked: the vault already has works to show each feature.",
    "setup.reason.homeNew": "With the works block. What to write today, and where you left off.",
    "setup.reason.settingSame": "Already set this way.",
    "setup.reason.settingOwn": "You already saved this one; it stays.",
    "setup.reason.settingChange": "Set for the language you chose.",
    "setup.reason.settingHasWorks": "Unticked: you already have works. Tick to change it.",
    "setup.reason.trackAll": "Your whole vault counts, so every folder already does.",
    "setup.reason.trackAddHasWorks": "Unticked: tick to add {folders} to what you already have.",
    "setup.reason.universeChoice": "The shared world you chose.",
    "setup.reason.trackAdd": "Adds {folders} to what you already have.",
    "setup.reason.featuresSame": "Already on {preset}.",
    "setup.reason.featuresChange": "Turns the features to match {preset}. The Features page shows the same button.",
    "setup.reason.featuresHasWorks": "Unticked: tick to change your switches to {preset}. The Features page shows the same button.",
    "setup.reason.layoutNew": "Opens the home note and puts the panels where they go.",
    "setup.reason.layoutTabs": "Unticked: you already have {leaves} tabs and panels open.",
    "setup.reason.layoutHasWorks": "Unticked: you already have a layout.",

    "setup.done.ok": "Done. I created {items} and changed {settings}.",
    "setup.done.home": " The home note is open.",
    "setup.done.partial": "I created {made} of {total} items. I couldn't create {path}: {error}.",
    "setup.done.more": " {n} more failed.",
    "setup.done.settingsSkipped": " The settings weren't changed.",
    "setup.done.layoutFailed": " I couldn't arrange the screen: {error}.",
    "setup.done.saveFailed": " I couldn't save the settings: {error}.",
    "setup.done.kept": " The rest stayed created; nothing was undone. Run the command again after fixing it.",
  },
  "pt-BR": {
    "setup.command": "Preparar o cofre para escrever",
    "setup.notice.text": "Escrita está pronto. Quer preparar este cofre para escrever? Mostro tudo antes de criar.",
    "setup.notice.setup": "Preparar…",
    "setup.notice.later": "Agora não",

    "setup.title": "Preparar o cofre para escrever",
    "setup.step.one": "1 · Escolhas",
    "setup.step.two": "2 · O que vou criar",
    "setup.writes.q": "O que você escreve?",
    "setup.writes.stories": "Contos e ensaios",
    "setup.writes.books": "Um romance",
    "setup.writes.both": "Os dois",
    "setup.language.q": "Idioma dos padrões",
    "setup.language.hint": "Vem do idioma do Obsidian. Status, pastas e listas nesse idioma.",
    "setup.language.en": "English",
    "setup.language.pt-BR": "Português (Brasil)",
    "setup.preset.q": "Ponto de partida",
    "setup.preset.essentials": "Essencial",
    "setup.preset.writer": "Escritor",
    "setup.preset.everything": "Tudo",
    "setup.preset.custom": "Personalizado",
    "setup.preset.essentials.text": "Esboço e beats, metas, marcadores, digitação, a lente, darlings, versões, exportar, nota inicial. {n} de 19.",
    "setup.preset.writer.text": "Essencial mais o foco no diálogo, mover blocos, modelos, publicar e envios. {n} de 19.",
    "setup.preset.everything.text": "Os {n}, com ortografia sob demanda, fios e o universo.",
    "setup.preset.hint": "Um ponto de partida, não um modo: depois, cada interruptor é seu, em Configurações › Escrita › Recursos.",
    "setup.preset.count": "{preset} ({n} de 19)",
    "setup.world.q": "Mundo compartilhado",
    "setup.world.off": "Desligado",
    "setup.world.perBook": "Por livro",
    "setup.world.universe": "Universo",
    "setup.world.hint": "Personagens e lugares. Pode decidir depois.",
    "setup.btn.cancel": "Cancelar",
    "setup.btn.preview": "Ver o que vou criar",
    "setup.btn.back": "Voltar",
    "setup.btn.create": "Criar",
    "setup.btn.close": "Fechar",

    "setup.preview.title": "O que vou criar",
    "setup.group.folder": "Pastas",
    "setup.group.example": "Exemplos",
    "setup.group.setting": "Configurações",
    "setup.group.home": "Nota inicial",
    "setup.group.layout": "Layout",
    "setup.mark.new": "Novo",
    "setup.mark.kept": "Fica como está",
    "setup.mark.setting": "Configuração",
    "setup.pill.example": "exemplo",
    "setup.pill.kept": "fica",
    "setup.tick": "Incluir: {name}",
    "setup.screen.title": "Arrumar a tela uma vez",
    "setup.screen.hint": "Depois disso o layout é seu; o Escrita não mexe de novo.",
    "setup.screen.desk": "Mesa de escrita",
    "setup.screen.desk.text": "A nota inicial na frente. À direita, o esboço com os beats em cima e a lente embaixo{universe}.",
    "setup.screen.desk.universe": "; o universo à esquerda",
    "setup.screen.focus": "Modo escrita",
    "setup.screen.focus.text": "Só a nota inicial, e a meta do dia embaixo se Metas estiver ligado. Barras e abas escondidas. Sai pelo botão ou pelo comando.",
    "setup.summary.note": "Nenhuma nota existente muda. Uma pasta que já existe é usada como está.",
    "setup.summary.count": "Vou criar {items} e mudar {settings}.",
    "setup.summary.items.one": "{n} item",
    "setup.summary.items.other": "{n} itens",
    "setup.summary.settings.one": "{n} configuração",
    "setup.summary.settings.other": "{n} configurações",
    "setup.summary.nothing": "Tudo o que você escolheu já existe. Nada a fazer.",
    "setup.summary.noneTicked": "Nada marcado. Marque uma linha para criar ou mudar.",

    "setup.setting.defaultsLanguage": "Idioma dos padrões",
    "setup.setting.stages": "Status",
    "setup.setting.chaptersFolder": "Pasta de capítulos",
    "setup.setting.unnumberedTitles": "Títulos de capítulo sem número",
    "setup.setting.submissionResults": "Resultados dos envios",
    "setup.setting.exportFolder": "Pasta de exportações",
    "setup.setting.submissionsFolder": "Pasta de envios",
    "setup.setting.darlingsNote": "Nota de darlings",
    "setup.setting.globalDarlingsNote": "Nota global de darlings",
    "setup.setting.universeNote": "Nota do universo",
    "setup.setting.entryTypes": "Tipos de entrada",
    "setup.setting.formValues": "Valores de forma",
    "setup.setting.threadKeyword": "Palavra dos fios",
    "setup.setting.threadClosedWord": "Palavra de fio fechado",
    "setup.setting.trackFolders": "Pastas que contam",
    "setup.setting.lensLanguage": "Idioma da escrita",
    "setup.setting.homeNote": "Nota inicial",
    "setup.setting.openHomeOnStartup": "Abrir a nota inicial ao iniciar",
    "setup.setting.universeMode": "Mundo compartilhado",
    "setup.setting.features": "Recursos",
    "setup.setting.layout": "Arrumar a tela uma vez",

    "setup.reason.folderNew": "Nova. Conta para as metas.",
    "setup.reason.folderHasWorks": "Desmarcada: você já tem obras. Marque para criar. Ela contaria para as metas.",
    "setup.reason.folderExists": "Já existe, fica. {count} notas. Usada como está.",
    "setup.reason.exists": "Já existe, fica.",
    "setup.reason.exampleNew": "Um exemplo para apagar sem medo.",
    "setup.reason.exampleHasWorks": "Desmarcado: o cofre já tem obras para mostrar cada recurso.",
    "setup.reason.homeNew": "Com o bloco de obras. Diz o que escrever hoje e leva aonde você parou.",
    "setup.reason.settingSame": "Já está assim.",
    "setup.reason.settingOwn": "Você já salvou esta; ela fica.",
    "setup.reason.settingChange": "Definida para o idioma que você escolheu.",
    "setup.reason.settingHasWorks": "Desmarcado: você já tem obras. Marque para mudar.",
    "setup.reason.trackAll": "O cofre inteiro conta, então toda pasta já conta.",
    "setup.reason.trackAddHasWorks": "Desmarcado: marque para acrescentar {folders} ao que você já tem.",
    "setup.reason.universeChoice": "O mundo compartilhado que você escolheu.",
    "setup.reason.trackAdd": "Acrescenta {folders} ao que você já tem.",
    "setup.reason.featuresSame": "Já está em {preset}.",
    "setup.reason.featuresChange": "Troca os recursos para combinar com {preset}. A página Recursos mostra o mesmo botão.",
    "setup.reason.featuresHasWorks": "Desmarcado: marque para trocar seus interruptores por {preset}. A página Recursos mostra o mesmo botão.",
    "setup.reason.layoutNew": "Abre a nota inicial e põe os painéis no lugar.",
    "setup.reason.layoutTabs": "Desmarcado: você já tem {leaves} abas e painéis abertos.",
    "setup.reason.layoutHasWorks": "Desmarcado: você já tem um layout.",

    "setup.done.ok": "Pronto. Criei {items} e mudei {settings}.",
    "setup.done.home": " A nota inicial está aberta.",
    "setup.done.partial": "Criei {made} de {total} itens. Não consegui criar {path}: {error}.",
    "setup.done.more": " Mais {n} falharam.",
    "setup.done.settingsSkipped": " As configurações não foram alteradas.",
    "setup.done.layoutFailed": " Não consegui arrumar a tela: {error}.",
    "setup.done.saveFailed": " Não consegui salvar as configurações: {error}.",
    "setup.done.kept": " O resto ficou criado; nada foi desfeito. Rode o comando de novo depois de resolver.",
  },
};
