import type { Strings } from "../i18n";

// The desk: the home block's rendering, the home note command and its confirm.
export const deskStrings: Strings = {
  en: {
    "desk.cmd.openHome": "Open the home note",
    "desk.notice.missing": "“{path}” is not in the vault any more.",
    "desk.notice.createFailed": "Could not create “{path}”.",
    "desk.confirm.title": "Create the home note?",
    "desk.confirm.body": "“{path}” does not exist. Create it with an empty works block?",
    "desk.confirm.bodyUnset": "No home note is set. Create {path} with the works block? The path is in Settings › Escrita.",
    "desk.confirm.create": "Create",
    "desk.confirm.cancel": "Cancel",
    "desk.loading": "Reading the vault…",
    "desk.heading.writing": "Writing",
    "desk.heading.revising": "Revising",
    "desk.count.idea.one": "{n} idea",
    "desk.count.idea.other": "{n} ideas",
    "desk.count.ready.one": "{n} ready",
    "desk.count.ready.other": "{n} ready",
    "desk.count.pending.one": "{n} pending",
    "desk.count.pending.other": "{n} pending",
    "desk.count.published.one": "{n} published",
    "desk.count.published.other": "{n} published",
    "desk.count.none.one": "{n} without a stage",
    "desk.count.none.other": "{n} without a stage",
    "desk.fact.ofMax": "{n} / max. {limit}",
    "desk.fact.max": "max. {limit}",
    "desk.fact.deadline": "due {day}",
    "desk.fact.chaptersReady.one": "{done} of {total} chapter ready",
    "desk.fact.chaptersReady.other": "{done} of {total} chapters ready",
    "desk.unit.characters": "characters",
    "desk.unit.charactersNoSpaces": "characters (no spaces)",
    "desk.empty.noWorks": "No works yet. A work is a tracked note with status {words}.",
    "desk.empty.nothing": "Nothing in {draft} or {revision}.",
    "desk.empty.noFolder": "No folder “{folder}”.",
    "desk.empty.noneInFolder": "No works in “{folder}”.",
  },
  "pt-BR": {
    "desk.cmd.openHome": "Abrir a nota inicial",
    "desk.notice.missing": "“{path}” não está mais no cofre.",
    "desk.notice.createFailed": "Não foi possível criar “{path}”.",
    "desk.confirm.title": "Criar a nota inicial?",
    "desk.confirm.body": "“{path}” não existe. Criar com um bloco de obras vazio?",
    "desk.confirm.bodyUnset": "Nenhuma nota inicial está definida. Criar {path} com o bloco de obras? O caminho fica em Configurações › Escrita.",
    "desk.confirm.create": "Criar",
    "desk.confirm.cancel": "Cancelar",
    "desk.loading": "Lendo o cofre…",
    "desk.heading.writing": "Escrevendo",
    "desk.heading.revising": "Revisando",
    "desk.count.idea.one": "{n} ideia",
    "desk.count.idea.other": "{n} ideias",
    "desk.count.ready.one": "{n} pronto",
    "desk.count.ready.other": "{n} prontos",
    "desk.count.pending.one": "{n} pendente",
    "desk.count.pending.other": "{n} pendentes",
    "desk.count.published.one": "{n} publicado",
    "desk.count.published.other": "{n} publicados",
    "desk.count.none.one": "{n} sem estágio",
    "desk.count.none.other": "{n} sem estágio",
    "desk.fact.ofMax": "{n} / máx. {limit}",
    "desk.fact.max": "máx. {limit}",
    "desk.fact.deadline": "prazo {day}",
    "desk.fact.chaptersReady.one": "{done} de {total} capítulo pronto",
    "desk.fact.chaptersReady.other": "{done} de {total} capítulos prontos",
    "desk.unit.characters": "caracteres",
    "desk.unit.charactersNoSpaces": "caracteres sem espaços",
    "desk.empty.noWorks": "Nenhuma obra ainda. Uma obra é uma nota acompanhada com status {words}.",
    "desk.empty.nothing": "Nada em {draft} ou {revision}.",
    "desk.empty.noFolder": "Nenhuma pasta “{folder}”.",
    "desk.empty.noneInFolder": "Nenhuma obra em “{folder}”.",
  },
};
