import type { Strings } from "./i18n";

// Shared strings: settings tab and anything used by more than one module.
export const coreStrings: Strings = {
  en: {
    "settings.books": "Books",
    "settings.chaptersFolder": "Chapters folder name",
    "settings.chaptersFolder.desc": "A note is a book when a folder with the same name sits next to it and holds this subfolder. Example: Novels/My Book.md + Novels/My Book/Chapters/.",
    "settings.chapterTemplate": "Chapter template",
    "settings.chapterTemplate.desc": "Note used as the starting content of new chapters. {{title}}, {{date}} (YYYY-MM-DD) and {{time}} (HH:mm) are filled in. Leave empty for a blank chapter.",
    "settings.numberPadding": "Chapter number digits",
    "settings.numberPadding.desc": "Minimum digits in chapter file names (01 Arrival.md). More are used when a book has more chapters than that allows.",
    "settings.statusProperty": "Status and summary properties",
    "settings.statusProperty.desc": "Frontmatter properties read from each chapter for the outline.",
    "settings.statusColors": "Status colors",
    "settings.statusColors.desc": "One per line: value = color. Colors the dot next to each chapter in the outline.",
    "settings.goals": "Goals",
    "settings.dailyGoal": "Daily word goal",
    "settings.dayEndsAt": "The writing day ends at",
    "settings.dayEndsAt.desc": "Words written after midnight but before this hour count toward the day before.",
    "settings.trackFolders": "Folders to track",
    "settings.trackFolders.desc": "One per line. Only writing in these folders counts toward goals. Leave empty to track the whole vault.",
    "settings.excludeFolders": "Folders to ignore",
    "settings.ignoreJumpsOver": "Ignore jumps over",
    "settings.ignoreJumpsOver.desc": "A single change adding or removing more words than this (a paste, an import, a sync) is not counted as writing.",
    "settings.sprintMinutes": "Default sprint",
    "settings.sprintMinutes.desc": "Minutes, then target words, for new sprints.",
    "settings.showStatusBar": "Show progress in the status bar",
    "settings.targetProperty": "Target property",
    "settings.limitProperty": "Limit property",
    "settings.unitProperty": "Unit property",
    "settings.pieceProperties.desc": "Any note can have its own length target, a hard limit (for a contest, say) and the unit they're counted in: words, characters (with spaces) or characters-no-spaces. The deadline uses the deadline property, like books.",
    "settings.weekdaysOff": "Weekdays off",
    "settings.weekdaysOff.desc": "Days off never break your streak, and pacing toward a deadline counts only writing days. Writing on a day off still counts.",
    "settings.datesOff": "Dates off",
    "settings.datesOff.desc": "Specific days off, one per line, as YYYY-MM-DD.",
    "settings.datesOff.invalid": "Not a date, ignored: {dates}",
    "settings.publishing": "Publishing",
    "settings.publishedValue": "Published value",
    "settings.publishedValue.desc": "The status property value (see Books) that means a note is published.",
    "settings.unpublishedValue": "Unpublished value",
    "settings.unpublishedValue.desc": "Status set when you unpublish a note whose earlier status isn't known.",
    "settings.dateProperty": "Date property",
    "settings.dateProperty.desc": "Set to the publication date when you publish.",
    "settings.recommendedProperties": "Recommended properties",
    "settings.recommendedProperties.desc": "One per line. Publishing warns when one of these is empty. Leave empty to skip the check.",
    "settings.outline": "Outline",
    "settings.ghostBeats": "Ghost beats",
    "settings.ghostBeats.desc": "Show outline beats inside chapters as gray placeholder text until you write the scene.",
    "settings.placeholders": "Placeholders",
    "settings.placeholderMarker": "Placeholder marker",
    "settings.placeholderMarker.desc": "Word used in %% XXX: … %% placeholders.",
    "settings.showExplorerDots": "Mark files with placeholders in the file explorer",
    "settings.darlings": "Darlings",
    "settings.darlingsNote": "Darlings note inside a book",
    "settings.darlingsNote.desc": "Path relative to the book's folder, e.g. Darlings.md or Notes/Darlings.md.",
    "settings.globalDarlingsNote": "Darlings note for everything else",
    "settings.editor": "Editor",
    "settings.enterFlow": "Enter, Enter, Enter",
    "settings.enterFlow.desc": "In chapters and other tracked notes, pressing Enter on empty lines past a normal paragraph gap (see the next setting) makes a scene break. In a chapter, one more Enter after a scene break at the end starts the next chapter.",
    "settings.paragraphStyle": "Paragraphs are separated by",
    "settings.paragraphStyle.desc": "Tells Enter, Enter, Enter how many empty lines are normal.",
    "settings.paragraphStyle.blank": "A blank line (standard Markdown)",
    "settings.paragraphStyle.single": "A single line break",
    "settings.smartTypography": "Smart typography",
    "settings.smartTypography.desc": "-- becomes —, ... becomes …, straight quotes curl as you type.",
    "settings.typographyScope": "Where smart typography applies",
    "settings.scope.books": "Only in book chapters",
    "settings.scope.all": "In every note",
    "settings.quoteStyle": "Quotes",
    "settings.quoteStyle.off": "Leave quotes alone",
    "settings.dialogueDash": "Dialogue dash",
    "settings.dialogueDash.desc": "-- at the start of a line becomes an em dash, for dialogue in Portuguese, Spanish, French and others.",
    "settings.spellcheckOnDemand": "Spellcheck only on demand",
    "settings.spellcheckOnDemand.desc": "Hide spelling squiggles while writing. Use the “Toggle spellcheck” command when you're ready to check.",
    "common.untitled": "Untitled",
    "common.words": "{n} words",
  },
  "pt-BR": {
    "settings.books": "Livros",
    "settings.chaptersFolder": "Nome da pasta de capítulos",
    "settings.chaptersFolder.desc": "Uma nota é um livro quando existe, ao lado dela, uma pasta com o mesmo nome contendo esta subpasta. Exemplo: Romances/Meu Livro.md + Romances/Meu Livro/Capítulos/.",
    "settings.chapterTemplate": "Modelo de capítulo",
    "settings.chapterTemplate.desc": "Nota usada como conteúdo inicial dos capítulos novos. {{title}}, {{date}} (AAAA-MM-DD) e {{time}} (HH:mm) são preenchidos. Deixe vazio para um capítulo em branco.",
    "settings.numberPadding": "Dígitos do número do capítulo",
    "settings.numberPadding.desc": "Mínimo de dígitos nos nomes dos capítulos (01 Chegada.md). Usa mais quando o livro tem mais capítulos do que isso comporta.",
    "settings.statusProperty": "Propriedades de status e resumo",
    "settings.statusProperty.desc": "Propriedades lidas de cada capítulo para o esboço.",
    "settings.statusColors": "Cores de status",
    "settings.statusColors.desc": "Uma por linha: valor = cor. Colore o ponto ao lado de cada capítulo no esboço.",
    "settings.goals": "Metas",
    "settings.dailyGoal": "Meta diária de palavras",
    "settings.dayEndsAt": "O dia de escrita termina às",
    "settings.dayEndsAt.desc": "Palavras escritas depois da meia-noite e antes desta hora contam para o dia anterior.",
    "settings.trackFolders": "Pastas acompanhadas",
    "settings.trackFolders.desc": "Uma por linha. Só o que você escreve nestas pastas conta para as metas. Vazio acompanha o cofre inteiro.",
    "settings.excludeFolders": "Pastas ignoradas",
    "settings.ignoreJumpsOver": "Ignorar saltos acima de",
    "settings.ignoreJumpsOver.desc": "Uma única mudança que adiciona ou remove mais palavras do que isso (colar, importar, sincronizar) não conta como escrita.",
    "settings.sprintMinutes": "Sprint padrão",
    "settings.sprintMinutes.desc": "Minutos e, depois, meta de palavras dos sprints novos.",
    "settings.showStatusBar": "Mostrar o progresso na barra de status",
    "settings.targetProperty": "Propriedade da meta",
    "settings.limitProperty": "Propriedade do limite",
    "settings.unitProperty": "Propriedade da unidade",
    "settings.pieceProperties.desc": "Qualquer nota pode ter sua própria meta de tamanho, um limite máximo (de um concurso, por exemplo) e a unidade em que são contados: words (palavras), characters (caracteres com espaços) ou characters-no-spaces (sem espaços). O prazo usa a propriedade deadline, como nos livros.",
    "settings.weekdaysOff": "Dias de folga na semana",
    "settings.weekdaysOff.desc": "Folgas nunca quebram a sequência, e o ritmo até o prazo conta só os dias de escrita. O que você escreve numa folga conta do mesmo jeito.",
    "settings.datesOff": "Datas de folga",
    "settings.datesOff.desc": "Dias de folga específicos, um por linha, no formato AAAA-MM-DD.",
    "settings.datesOff.invalid": "Não é uma data, ignorado: {dates}",
    "settings.publishing": "Publicação",
    "settings.publishedValue": "Valor de publicado",
    "settings.publishedValue.desc": "O valor da propriedade de status (veja Livros) que indica que a nota está publicada.",
    "settings.unpublishedValue": "Valor de despublicado",
    "settings.unpublishedValue.desc": "Status usado ao despublicar uma nota quando o status anterior não é conhecido.",
    "settings.dateProperty": "Propriedade de data",
    "settings.dateProperty.desc": "Recebe a data de publicação quando você publica.",
    "settings.recommendedProperties": "Propriedades recomendadas",
    "settings.recommendedProperties.desc": "Uma por linha. Publicar avisa quando alguma delas está vazia. Deixe vazio para não verificar.",
    "settings.outline": "Esboço",
    "settings.ghostBeats": "Beats fantasmas",
    "settings.ghostBeats.desc": "Mostra os beats do esboço dentro dos capítulos como texto cinza até você escrever a cena.",
    "settings.placeholders": "Marcadores",
    "settings.placeholderMarker": "Palavra do marcador",
    "settings.placeholderMarker.desc": "Palavra usada nos marcadores %% XXX: … %%.",
    "settings.showExplorerDots": "Marcar no explorador os arquivos com marcadores",
    "settings.darlings": "Darlings",
    "settings.darlingsNote": "Nota de darlings dentro de um livro",
    "settings.darlingsNote.desc": "Caminho relativo à pasta do livro, por exemplo Darlings.md ou Notas/Darlings.md.",
    "settings.globalDarlingsNote": "Nota de darlings para o resto",
    "settings.editor": "Editor",
    "settings.enterFlow": "Enter, Enter, Enter",
    "settings.enterFlow.desc": "Nos capítulos e nas outras notas acompanhadas, Enter em linhas vazias além do espaço normal entre parágrafos (veja a próxima opção) cria uma quebra de cena. Num capítulo, mais um Enter depois de uma quebra de cena no fim começa o capítulo seguinte.",
    "settings.paragraphStyle": "Parágrafos são separados por",
    "settings.paragraphStyle.desc": "Diz ao Enter, Enter, Enter quantas linhas vazias são normais.",
    "settings.paragraphStyle.blank": "Uma linha em branco (Markdown padrão)",
    "settings.paragraphStyle.single": "Uma única quebra de linha",
    "settings.smartTypography": "Tipografia inteligente",
    "settings.smartTypography.desc": "-- vira —, ... vira …, aspas retas se curvam enquanto você digita.",
    "settings.typographyScope": "Onde a tipografia inteligente vale",
    "settings.scope.books": "Só nos capítulos de livros",
    "settings.scope.all": "Em todas as notas",
    "settings.quoteStyle": "Aspas",
    "settings.quoteStyle.off": "Não mexer nas aspas",
    "settings.dialogueDash": "Travessão de diálogo",
    "settings.dialogueDash.desc": "-- no começo da linha vira travessão, para diálogos.",
    "settings.spellcheckOnDemand": "Corretor só quando pedir",
    "settings.spellcheckOnDemand.desc": "Esconde os sublinhados de ortografia enquanto você escreve. Use o comando “Ligar/desligar corretor” quando quiser revisar.",
    "common.untitled": "Sem título",
    "common.words": "{n} palavras",
  },
};
