import type { Strings } from "./i18n";

// Shared strings: settings tab and anything used by more than one module.
export const coreStrings: Strings = {
  en: {
    "features.offNotice": "This feature is off. Turn it on in Escrita's settings.",
    "settings.books": "Books",
    "settings.features": "Features",
    "settings.features.desc": "Turn off what you don't use. A feature that is off doesn't load: no commands, panels, menus or background work. Your data stays, and comes back when you turn it on again.",
    "settings.language": "Writing language",
    "settings.language.desc": "The revision lens and the universe read this language to recognize words and names.",
    "settings.language.auto": "Automatic",
    "settings.language.pt": "Português (Brasil)",
    "settings.language.en": "English",
    "settings.features.group.writing": "Writing",
    "settings.features.group.revision": "Revision",
    "settings.features.group.desk": "The desk",
    "settings.features.group.publishing": "Publishing",
    "settings.features.group.world": "The world",
    "settings.features.alwaysOn": "always on",
    "settings.features.stages": "Stages",
    "settings.features.stages.desc": "Idea, draft, revision, ready, published, read from your status. The outline, the Works tab and publish read the stages, so they can't be turned off.",
    "settings.features.goals": "Goals and sprints",
    "settings.features.goals.desc": "Daily goals, sprints and the count in the status bar.",
    "settings.features.outline": "Outline and ghost beats",
    "settings.features.outline.desc": "The panel of chapters and scenes, and the beats still waiting for prose.",
    "settings.features.placeholders": "Placeholders",
    "settings.features.placeholders.desc": "Notes like %% {marker}: … %% for what is missing; they hold back publishing.",
    "settings.features.typing": "Enter flow and smart typography",
    "settings.features.typing.desc": "Paragraphs with Enter, dashes and proper quotes as you type.",
    "settings.features.dialogueFocus": "Dialogue focus",
    "settings.features.dialogueFocus.desc": "Dims the narration so you read only the speech.",
    "settings.features.moveBlocks": "Move a paragraph or scene",
    "settings.features.moveBlocks.desc": "Takes a block to another place in the note or to another note.",
    "settings.features.templates": "Insert from a template",
    "settings.features.templates.desc": "Inserts the text of a template note at the cursor.",
    "settings.features.spellcheck": "Spellcheck on demand",
    "settings.features.spellcheck.desc": "Turns spellcheck on and off with a command, so you can write without squiggles.",
    "settings.features.explorerCounts": "Word counts in the explorer",
    "settings.features.explorerCounts.desc": "Words and progress next to each note and folder.",
    "settings.features.lens": "Revision lens",
    "settings.features.lens.desc": "Echoes, adverbs, crutch words and long sentences, only when you open the lens.",
    "settings.features.snapshots": "Snapshots",
    "settings.features.snapshots.desc": "Copies of a note to compare word by word.",
    "settings.features.snapshots.off": "\"Snapshot at each stage\" pauses until Snapshots is back. Saved snapshots stay where they are.",
    "settings.features.off.snapshots.one": "Snapshots off. The {n} saved snapshot stays in {folder}.",
    "settings.features.off.snapshots.other": "Snapshots off. The {n} saved snapshots stay in {folder}.",
    "settings.features.off.darlings": "Darlings off. The cut passages stay in your notes; turn it back on to restore them.",
    "settings.features.off.goals.one": "Goals off. {n} day of writing history stays in Escrita's data.",
    "settings.features.off.goals.other": "Goals off. {n} days of writing history stay in Escrita's data.",
    "settings.features.off.lens": "Revision off. Your word lists stay in {note}.",
    "settings.features.off.desk.one": "Desk off. Where you left off in {n} note stays in Escrita's data.",
    "settings.features.off.desk.other": "Desk off. Where you left off in {n} notes stays in Escrita's data.",
    "settings.features.darlings": "Darlings",
    "settings.features.darlings.desc": "Cut passages kept, to return to where they were.",
    "settings.features.stageSnapshot": "Snapshot at each stage",
    "settings.features.stageSnapshot.desc": "Keeps a snapshot when a work changes stage.",
    "settings.features.uses.snapshots": "uses Snapshots",
    "settings.features.needs.snapshots": "needs Snapshots",
    "settings.features.needs.snapshots.desc": "Needs Snapshots, which is off.",
    "settings.features.turnOn.snapshots": "Turn on Snapshots",
    "settings.features.desk": "Works block and where you left off",
    "settings.features.desk.desc": "What to write today, in the home note, and one click back to where you stopped.",
    "settings.features.publish": "Publish check",
    "settings.features.publish.desc": "Checks the note before setting status and date.",
    "settings.features.export": "Export",
    "settings.features.export.desc": "DOCX, EPUB and Markdown in manuscript format, for a note, a book or a collection.",
    "settings.features.submissions": "Submissions",
    "settings.features.submissions.desc": "Where you sent each work, and what came back.",
    "settings.features.universe": "Shared universe",
    "settings.features.universe.desc": "The mode is the switch: Off loads no panel and no commands.",
    "settings.features.threads": "Threads",
    "settings.features.threads.desc": "%% {keyword}: … %% marks a loose end. Works in any mode.",
    "settings.shared": "Properties and folders",
    "settings.shared.desc": "The property names Escrita reads from your notes, and where it counts your writing. Several features share them, so they are always shown.",
    "settings.povProperty": "Point of view property",
    "settings.povProperty.desc": "On a chapter: whose point of view it is, a link or plain text. The outline shows it.",
    "settings.chapterTargetProperty": "Chapter target property",
    "settings.chapterTargetProperty.desc": "In a book's note: the default word target of each of its chapters when it has none of its own.",
    "settings.chaptersFolder": "Chapters folder name",
    "settings.chaptersFolder.desc": "A note is a book when a folder with the same name sits next to it and holds this subfolder. Example: Novels/My Book.md + Novels/My Book/Chapters/.",
    "settings.chapterTemplate": "Chapter template",
    "settings.templatesFolder": "Templates folder",
    "settings.templatesFolder.desc": "Notes in this folder are offered by the command Insert from a template. {{title}}, {{date}} (YYYY-MM-DD) and {{time}} (HH:mm) are filled in, and the template's properties are added to the note where it lacks them. Leave empty to turn it off.",
    "settings.chapterTemplate.desc": "Note used as the starting content of new chapters. {{title}}, {{date}} (YYYY-MM-DD) and {{time}} (HH:mm) are filled in. Leave empty for a blank chapter.",
    "settings.unnumberedTitles": "Chapters without a number",
    "settings.unnumberedTitles.desc": "Titles that never get a chapter number in export and the outline, separated by commas. Number every file as usual; a chapter whose title is listed (or starts with it, like \"Interlude: the letter\") exports with its title alone and is not counted, so 01 Prologue, 02 Arrival, 03 Interlude, 04 The cellar gives Prologue, Chapter 1, Interlude, Chapter 2. Case and accents are ignored.",
    "settings.numberPadding": "Chapter number digits",
    "settings.numberPadding.desc": "Minimum digits in chapter file names (01 Arrival.md). More are used when a book has more chapters than that allows.",
    "settings.statusProperty": "Status and summary properties",
    "settings.statusProperty.desc": "Frontmatter properties read from each chapter, book and note: the status says which stage a work is in (see Stages), the summary shows in the outline.",
    "stage.idea": "Idea",
    "stage.draft": "Draft",
    "stage.revision": "Revision",
    "stage.ready": "Ready",
    "stage.published": "Published",
    "settings.stages": "Stages",
    "settings.stages.desc": "The five stages of a work and the status words you use for each. The first word is the one Escrita writes; the others count too. Separate with commas.",
    "settings.draftNewNotes": "New notes start as draft",
    "settings.draftNewNotes.desc": "New chapters, and notes you create in a tracked folder, get \"{word}\" as their status, unless they already have one. Only the properties change.",
    "settings.stages.duplicate": "\"{word}\" is in {stages}. The first one wins: {first}.",
    "settings.stages.words": "Words for {stage}",
    "settings.stages.color": "Color for {stage}",
    "settings.stages.noColor": "No color",
    "settings.stages.clear": "Remove the color",
    "settings.otherStatusColors": "Other status colors",
    "settings.otherStatusColors.desc": "For statuses that are not a stage, such as chapter ones. One per line: word: color.",
    "settings.homeNoteHeading": "Home note",
    "settings.homeNote": "Home note",
    "settings.homeNote.desc": "The note that holds the works block. The \"Open the home note\" command opens it.",
    "settings.lens": "Revision",
    "settings.lens.desc": "The revision lens underlines what is worth rereading. It only suggests: it never changes your text, and everything is computed on your device.",
    "settings.lens.lists": "Word lists note",
    "settings.lens.lists.desc": "Crutch words, names and words to ignore, under the headings ## Crutch words, ## Names and ## Ignore.",
    "settings.lens.lists.create": "Create",
    "settings.lens.echoWindow": "Echo window",
    "settings.lens.echoWindow.desc": "How many words back an echo looks. It starts over at each scene and heading.",
    "settings.lens.longSentence": "Long sentence",
    "settings.lens.longSentence.desc": "A sentence with more words than this is marked.",
    "settings.lens.words": "words",
    "settings.lens.skipQuotes": "Skip quotes",
    "settings.lens.skipQuotes.desc": "Lines that start with > are not read.",
    "settings.lens.rules": "Rules",
    "settings.lens.rule.echo.desc": "The same word, or one of the same family, too close.",
    "settings.lens.rule.adverb.pt-BR.desc": "Words ending in -mente.",
    "settings.lens.rule.adverb.en.desc": "Words ending in -ly.",
    "settings.lens.rule.adverb.none.desc": "Words ending in -mente or -ly.",
    "settings.lens.rule.gerund.desc": "Gerunds, gerundismo (vou estar ligando) and three or more in one sentence.",
    "settings.lens.rule.gerund.en.desc": "Phrases like started to and began to.",
    "settings.lens.rule.crutch.desc": "The words and phrases in your word lists note.",
    "settings.lens.rule.name.desc": "A capitalized word almost equal to a name in the list: Maira for Maria.",
    "settings.lens.rule.long.desc": "",
    "settings.lens.measures": "Measures",
    "settings.lens.showDialogue": "Show dialogue share",
    "settings.lens.showReadability": "Show readability",
    "settings.lens.showReadability.desc": "Flesch adapted to Portuguese (Martins, 1996), or Flesch for English.",
    "settings.openHomeOnStartup": "Open on startup",
    "settings.openHomeOnStartup.desc": "Opens the home note in the active tab when Obsidian starts, replacing the restored tab.",
    "settings.goals": "Goals",
    "settings.dailyGoal": "Daily word goal",
    "settings.dayEndsAt": "The writing day ends at",
    "settings.dayEndsAt.desc": "Words written after midnight but before this hour count toward the day before.",
    "settings.trackFolders": "Folders to track",
    "settings.trackFolders.desc": "One per line. Only writing in these folders counts toward goals. Leave empty to track the whole vault.",
    "settings.excludeFolders": "Folders to ignore",
    "settings.ignoreJumpsOver": "Ignore jumps over",
    "settings.ignoreJumpsOver.desc": "A single change adding or removing more words than this (a paste, an import, a sync) is not counted as writing.",
    "settings.sprintMinutes": "Default sprint",
    "settings.sprintMinutes.desc": "Minutes, then target words, for new sprints.",
    "settings.showStatusBar": "Show progress in the status bar",
    "settings.explorerFolderTotals": "Show folder totals",
    "settings.explorerFolderTotals.desc": "Other folders show the words in the tracked notes inside them. Books always show their total.",
    "settings.explorerShowTarget": "Show the target next to the count",
    "settings.explorerShowTarget.desc": "For notes with a target or limit, for example 4,210 / 5,000.",
    "settings.targetProperty": "Target property",
    "settings.limitProperty": "Limit property",
    "settings.unitProperty": "Unit property",
    "settings.deadlineProperty": "Deadline property",
    "settings.goalProperty": "Book goal property",
    "settings.goalProperty.desc": "The property in a book's note that holds its word goal: 80000, or \"80,000\" / \"80.000\" in quotes (unquoted, 80.000 is the decimal number 80).",
    "settings.pieceProperties.desc": "Any note can have its own length target, a hard limit (for a contest, say) and the unit they're counted in: words, characters (with spaces) or characters-no-spaces. Write amounts as 15000, or quote them with separators (\"15.000\"). Books and notes read their deadline from the deadline property.",
    "settings.weekdaysOff": "Weekdays off",
    "settings.weekdaysOff.desc": "Days off never break your streak, and pacing toward a deadline counts only writing days. Writing on a day off still counts.",
    "settings.datesOff": "Dates off",
    "settings.datesOff.desc": "Specific days off, one per line, as YYYY-MM-DD.",
    "settings.datesOff.invalid": "Not a date, ignored: {dates}",
    "settings.publishing": "Publishing",
    "settings.dateProperty": "Date property",
    "settings.dateProperty.desc": "Set to the publication date when you publish.",
    "settings.recommendedProperties": "Recommended properties",
    "settings.recommendedProperties.desc": "One per line. Publishing warns when one of these is empty. Leave empty to skip the check.",
    "settings.snapshots": "Snapshots",
    "settings.snapshotsFolder": "Snapshots folder",
    "settings.snapshotsFolder.desc": "One folder per note, with plain text files (.txt) and an index.json, so search, graph and links ignore them. Obsidian Sync copies them only with “Sync all other types” turned on; git, iCloud, Dropbox and Syncthing copy them as they are. Folders starting with a dot are hidden, but Obsidian Sync skips them. Changing this doesn't move existing snapshots.",
    "settings.snapshotsFolder.invalid": "Not saved. Choose a folder outside {folder}.",
    "settings.snapshotsFolder.notes": "Not saved: {folder} already has notes. Choose a folder that holds only snapshots.",
    "settings.folderProblem.path": "Not saved. That is not a plain folder inside the vault (no “..” or “.”).",
    "settings.folderProblem.outside": "Not saved. Choose a folder outside {folder}.",
    "settings.folderProblem.holdsBook": "Not saved. {folder} holds a book; choose a folder without books inside.",
    "settings.folderProblem.overlap": "Not saved. Escrita's folders can't hold each other: it overlaps {folder}.",
    "settings.folderProblem.notes": "Not saved: {folder} already has files. Choose a folder with none of your files.",
    "settings.snapshotsFolder.path": "Not saved. Choose a folder inside the vault, without “..”.",
    "settings.snapshotBeforeFirstEdit": "Snapshot before the first edit of each day",
    "settings.snapshotBeforeFirstEdit.desc": "The first time you change a tracked note on a writing day, Escrita saves its text as it was.",
    "settings.snapshotsKeepAuto": "Automatic snapshots to keep per note",
    "settings.snapshotsKeepAuto.desc": "Older automatic snapshots go to the trash. Snapshots you take yourself are never removed.",
    "settings.outline": "Outline",
    "settings.ghostBeats": "Ghost beats",
    "settings.ghostBeats.desc": "Show outline beats inside chapters as gray placeholder text until you write the scene.",
    "settings.placeholders": "Placeholders",
    "settings.placeholderMarker": "Placeholder marker",
    "settings.placeholderMarker.desc": "Word used in %% {marker}: … %% placeholders.",
    "settings.showExplorerDots": "Mark files with placeholders in the file explorer",
    "settings.darlings": "Darlings",
    "settings.darlingsNote": "Darlings note inside a book",
    "settings.darlingsNote.desc": "Path relative to the book's folder, e.g. Darlings.md or Notes/Darlings.md.",
    "settings.globalDarlingsNote": "Darlings note for everything else",
    "settings.editor": "Editor",
    "settings.enterFlow": "Enter, Enter, Enter",
    "settings.enterFlow.desc": "In chapters and other tracked notes, pressing Enter on empty lines past a normal paragraph gap (see the next setting) makes a scene break. In a chapter, one more Enter after a scene break at the end starts the next chapter.",
    "settings.paragraphStyle": "Paragraphs are separated by",
    "settings.paragraphStyle.desc": "Tells Enter, Enter, Enter how many empty lines are normal.",
    "settings.paragraphStyle.blank": "A blank line (standard Markdown)",
    "settings.paragraphStyle.single": "A single line break",
    "settings.smartTypography": "Smart typography",
    "settings.smartTypography.desc": "-- becomes —, ... becomes …, straight quotes curl as you type.",
    "settings.typographyScope": "Where smart typography applies",
    "settings.scope.books": "Only in book chapters",
    "settings.scope.all": "In every note",
    "settings.quoteStyle": "Quotes",
    "settings.quoteStyle.off": "Leave quotes alone",
    "settings.dialogueDash": "Dialogue dash",
    "settings.dialogueDash.desc": "-- at the start of a line becomes an em dash, for dialogue in Portuguese, Spanish, French and others.",
    "common.untitled": "Untitled",
    "common.unit.words.one": "{n} word",
    "common.unit.words.other": "{n} words",
    "common.unit.characters.one": "{n} character",
    "common.unit.characters.other": "{n} characters",
    "common.unit.charactersNoSpaces.one": "{n} character (no spaces)",
    "common.unit.charactersNoSpaces.other": "{n} characters (no spaces)",
  },
  "pt-BR": {
    "features.offNotice": "Este recurso está desligado. Ligue-o nas configurações do Escrita.",
    "settings.books": "Livros",
    "settings.features": "Recursos",
    "settings.features.desc": "Desligue o que você não usa. Um recurso desligado não carrega: sem comandos, painéis, menus nem trabalho em segundo plano. Os dados ficam, e voltam quando você liga de novo.",
    "settings.language": "Idioma da escrita",
    "settings.language.desc": "A lente de revisão e o universo leem este idioma para reconhecer palavras e nomes.",
    "settings.language.auto": "Automático",
    "settings.language.pt": "Português (Brasil)",
    "settings.language.en": "English",
    "settings.features.group.writing": "Escrita",
    "settings.features.group.revision": "Revisão",
    "settings.features.group.desk": "Acompanhamento",
    "settings.features.group.publishing": "Publicação",
    "settings.features.group.world": "O mundo",
    "settings.features.alwaysOn": "sempre ligado",
    "settings.features.stages": "Estágios",
    "settings.features.stages.desc": "Ideia, rascunho, revisão, pronto, publicado, lidos do seu status. O esboço, a aba Obras e a publicação leem os estágios, então eles não desligam.",
    "settings.features.goals": "Metas e sprints",
    "settings.features.goals.desc": "Metas diárias, sprints e a contagem na barra de status.",
    "settings.features.outline": "Esboço e beats fantasmas",
    "settings.features.outline.desc": "O painel de capítulos e cenas, e os beats que ainda esperam prosa.",
    "settings.features.placeholders": "Marcadores",
    "settings.features.placeholders.desc": "Notas como %% {marker}: … %% para o que falta; seguram a publicação.",
    "settings.features.typing": "Enter e tipografia",
    "settings.features.typing.desc": "Parágrafos com Enter, travessões e aspas certas enquanto você digita.",
    "settings.features.dialogueFocus": "Foco no diálogo",
    "settings.features.dialogueFocus.desc": "Esmaece a narração para você ler só as falas.",
    "settings.features.moveBlocks": "Mover parágrafo ou cena",
    "settings.features.moveBlocks.desc": "Leva um bloco para outro lugar da nota ou para outra nota.",
    "settings.features.templates": "Inserir de um modelo",
    "settings.features.templates.desc": "Insere o texto de uma nota modelo onde está o cursor.",
    "settings.features.spellcheck": "Ortografia sob demanda",
    "settings.features.spellcheck.desc": "Liga e desliga a correção ortográfica por um comando, para escrever sem sublinhados.",
    "settings.features.explorerCounts": "Contagens no explorador",
    "settings.features.explorerCounts.desc": "Palavras e progresso ao lado de cada nota e pasta.",
    "settings.features.lens": "Lente de revisão",
    "settings.features.lens.desc": "Ecos, advérbios, muletas e frases longas, só quando você abre a lente.",
    "settings.features.snapshots": "Versões",
    "settings.features.snapshots.desc": "Cópias de uma nota para comparar palavra por palavra.",
    "settings.features.snapshots.off": "\"Versão a cada estágio\" fica parada até Versões voltar. As versões guardadas continuam onde estão.",
    "settings.features.off.snapshots.one": "Versões desligadas. A {n} versão guardada continua em {folder}.",
    "settings.features.off.snapshots.other": "Versões desligadas. As {n} versões guardadas continuam em {folder}.",
    "settings.features.off.darlings": "Darlings desligados. Os trechos cortados continuam nas suas notas; ligue de novo para devolvê-los.",
    "settings.features.off.goals.one": "Metas desligadas. {n} dia de histórico de escrita continua nos dados do Escrita.",
    "settings.features.off.goals.other": "Metas desligadas. {n} dias de histórico de escrita continuam nos dados do Escrita.",
    "settings.features.off.lens": "Revisão desligada. Suas listas de palavras continuam em {note}.",
    "settings.features.off.desk.one": "Mesa desligada. O ponto onde você parou em {n} nota continua nos dados do Escrita.",
    "settings.features.off.desk.other": "Mesa desligada. O ponto onde você parou em {n} notas continua nos dados do Escrita.",
    "settings.features.darlings": "Darlings",
    "settings.features.darlings.desc": "Trechos cortados guardados, para devolver onde estavam.",
    "settings.features.stageSnapshot": "Versão a cada estágio",
    "settings.features.stageSnapshot.desc": "Guarda uma versão quando a obra muda de estágio.",
    "settings.features.uses.snapshots": "usa Versões",
    "settings.features.needs.snapshots": "precisa de Versões",
    "settings.features.needs.snapshots.desc": "Precisa de Versões, que está desligado.",
    "settings.features.turnOn.snapshots": "Ligar Versões",
    "settings.features.desk": "Bloco de obras e onde você parou",
    "settings.features.desk.desc": "O que escrever hoje, na nota inicial, e um clique para voltar aonde parou.",
    "settings.features.publish": "Checagem de publicação",
    "settings.features.publish.desc": "Confere a nota antes de marcar status e data.",
    "settings.features.export": "Exportar",
    "settings.features.export.desc": "DOCX, EPUB e Markdown no formato de manuscrito, para uma nota, um livro ou uma coleção.",
    "settings.features.submissions": "Envios",
    "settings.features.submissions.desc": "Para onde você mandou cada obra, e o que voltou.",
    "settings.features.universe": "Universo compartilhado",
    "settings.features.universe.desc": "O modo é o interruptor: Desligado não carrega painel nem comandos.",
    "settings.features.threads": "Fios",
    "settings.features.threads.desc": "%% {keyword}: … %% marca uma ponta solta. Vale em qualquer modo.",
    "settings.shared": "Propriedades e pastas",
    "settings.shared.desc": "Os nomes de propriedades que o Escrita lê das suas notas e as pastas onde ele conta a sua escrita. Vários recursos usam, então ficam sempre à vista.",
    "settings.povProperty": "Propriedade do ponto de vista",
    "settings.povProperty.desc": "Num capítulo: de quem é o ponto de vista, um link ou texto simples. O esboço mostra.",
    "settings.chapterTargetProperty": "Propriedade da meta dos capítulos",
    "settings.chapterTargetProperty.desc": "Na nota de um livro: a meta de palavras de cada capítulo, quando ele não tem a sua.",
    "settings.chaptersFolder": "Nome da pasta de capítulos",
    "settings.chaptersFolder.desc": "Uma nota é um livro quando existe, ao lado dela, uma pasta com o mesmo nome contendo esta subpasta. Exemplo: Romances/Meu Livro.md + Romances/Meu Livro/Capítulos/.",
    "settings.chapterTemplate": "Modelo de capítulo",
    "settings.templatesFolder": "Pasta de modelos",
    "settings.templatesFolder.desc": "As notas desta pasta são oferecidas pelo comando Inserir de um modelo. {{title}}, {{date}} (AAAA-MM-DD) e {{time}} (HH:mm) são preenchidos, e as propriedades do modelo são acrescentadas à nota onde ela não as tem. Deixe vazio para desligar.",
    "settings.chapterTemplate.desc": "Nota usada como conteúdo inicial dos capítulos novos. {{title}}, {{date}} (AAAA-MM-DD) e {{time}} (HH:mm) são preenchidos. Deixe vazio para um capítulo em branco.",
    "settings.unnumberedTitles": "Capítulos sem número",
    "settings.unnumberedTitles.desc": "Títulos que nunca recebem número de capítulo na exportação e no esboço, separados por vírgulas. Numere todos os arquivos como de costume; um capítulo cujo título está na lista (ou começa com ele, como \"Interlúdio: a carta\") é exportado só com o título e não é contado: 01 Prólogo, 02 A chegada, 03 Interlúdio, 04 O porão dá Prólogo, Capítulo 1, Interlúdio, Capítulo 2. Maiúsculas e acentos são ignorados.",
    "settings.numberPadding": "Dígitos do número do capítulo",
    "settings.numberPadding.desc": "Mínimo de dígitos nos nomes dos capítulos (01 Chegada.md). Usa mais quando o livro tem mais capítulos do que isso comporta.",
    "settings.statusProperty": "Propriedades de status e resumo",
    "settings.statusProperty.desc": "Propriedades lidas de cada capítulo, livro e nota: o status diz em que estágio está uma obra (veja Estágios), o resumo aparece no esboço.",
    "stage.idea": "Ideia",
    "stage.draft": "Rascunho",
    "stage.revision": "Revisão",
    "stage.ready": "Pronto",
    "stage.published": "Publicado",
    "settings.stages": "Estágios",
    "settings.stages.desc": "Os cinco estágios de uma obra e as palavras de status que você usa para cada um. A primeira palavra é a que o Escrita escreve; as outras também valem. Separe com vírgulas.",
    "settings.draftNewNotes": "Notas novas começam como rascunho",
    "settings.draftNewNotes.desc": "Capítulos novos, e notas que você cria numa pasta contada, recebem \"{word}\" como status, a menos que já tenham um. Só as propriedades mudam.",
    "settings.stages.duplicate": "\"{word}\" está em {stages}. Vale o primeiro: {first}.",
    "settings.stages.words": "Palavras para {stage}",
    "settings.stages.color": "Cor de {stage}",
    "settings.stages.noColor": "Sem cor",
    "settings.stages.clear": "Tirar a cor",
    "settings.otherStatusColors": "Outras cores de status",
    "settings.otherStatusColors.desc": "Para status que não são estágio, como os de capítulo. Uma por linha: palavra: cor.",
    "settings.homeNoteHeading": "Nota inicial",
    "settings.homeNote": "Nota inicial",
    "settings.homeNote.desc": "A nota com o bloco de obras. O comando \"Abrir a nota inicial\" abre esta nota.",
    "settings.lens": "Revisão",
    "settings.lens.desc": "A lente de revisão sublinha o que vale a pena reler. Ela só sugere: nunca muda o texto, e tudo é calculado no seu aparelho.",
    "settings.lens.lists": "Nota de listas de palavras",
    "settings.lens.lists.desc": "Vícios, nomes e palavras a ignorar, sob os títulos ## Vícios, ## Nomes e ## Ignorar.",
    "settings.lens.lists.create": "Criar",
    "settings.lens.echoWindow": "Janela dos ecos",
    "settings.lens.echoWindow.desc": "Quantas palavras para trás um eco procura. Recomeça a cada cena e título.",
    "settings.lens.longSentence": "Frase longa",
    "settings.lens.longSentence.desc": "Uma frase com mais palavras que isto é marcada.",
    "settings.lens.words": "palavras",
    "settings.lens.skipQuotes": "Pular citações",
    "settings.lens.skipQuotes.desc": "Linhas que começam com > não são lidas.",
    "settings.lens.rules": "Regras",
    "settings.lens.rule.echo.desc": "A mesma palavra, ou da mesma família, perto demais.",
    "settings.lens.rule.adverb.pt-BR.desc": "Palavras em -mente.",
    "settings.lens.rule.adverb.en.desc": "Palavras em -ly.",
    "settings.lens.rule.adverb.none.desc": "Palavras em -mente ou -ly.",
    "settings.lens.rule.gerund.desc": "Gerúndios, gerundismo (vou estar ligando) e três ou mais numa frase.",
    "settings.lens.rule.gerund.en.desc": "Construções como started to e began to.",
    "settings.lens.rule.crutch.desc": "As palavras e expressões da sua nota de listas.",
    "settings.lens.rule.name.desc": "Uma palavra com maiúscula quase igual a um nome da lista: Maira por Maria.",
    "settings.lens.rule.long.desc": "",
    "settings.lens.measures": "Medidas",
    "settings.lens.showDialogue": "Mostrar a parte de diálogo",
    "settings.lens.showReadability": "Mostrar a legibilidade",
    "settings.lens.showReadability.desc": "Flesch adaptado ao português (Martins, 1996) ou Flesch em inglês.",
    "settings.openHomeOnStartup": "Abrir ao iniciar",
    "settings.openHomeOnStartup.desc": "Abre a nota inicial na aba ativa quando o Obsidian abre, no lugar da aba restaurada.",
    "settings.goals": "Metas",
    "settings.dailyGoal": "Meta diária de palavras",
    "settings.dayEndsAt": "O dia de escrita termina às",
    "settings.dayEndsAt.desc": "Palavras escritas depois da meia-noite e antes desta hora contam para o dia anterior.",
    "settings.trackFolders": "Pastas acompanhadas",
    "settings.trackFolders.desc": "Uma por linha. Só o que você escreve nestas pastas conta para as metas. Vazio acompanha o cofre inteiro.",
    "settings.excludeFolders": "Pastas ignoradas",
    "settings.ignoreJumpsOver": "Ignorar saltos acima de",
    "settings.ignoreJumpsOver.desc": "Uma única mudança que adiciona ou remove mais palavras do que isso (colar, importar, sincronizar) não conta como escrita.",
    "settings.sprintMinutes": "Sprint padrão",
    "settings.sprintMinutes.desc": "Minutos e, depois, meta de palavras dos sprints novos.",
    "settings.showStatusBar": "Mostrar o progresso na barra de status",
    "settings.explorerFolderTotals": "Mostrar o total das pastas",
    "settings.explorerFolderTotals.desc": "As outras pastas mostram as palavras das notas acompanhadas que estão nelas. Os livros sempre mostram o total.",
    "settings.explorerShowTarget": "Mostrar a meta ao lado da contagem",
    "settings.explorerShowTarget.desc": "Nas notas com meta ou limite, por exemplo 4.210 / 5.000.",
    "settings.targetProperty": "Propriedade da meta",
    "settings.limitProperty": "Propriedade do limite",
    "settings.unitProperty": "Propriedade da unidade",
    "settings.deadlineProperty": "Propriedade do prazo",
    "settings.goalProperty": "Propriedade da meta do livro",
    "settings.goalProperty.desc": "A propriedade na nota do livro que guarda a meta de palavras: 80000, ou \"80.000\" / \"80,000\" entre aspas (sem aspas, 80.000 é o número decimal 80).",
    "settings.pieceProperties.desc": "Qualquer nota pode ter sua própria meta de tamanho, um limite máximo (de um concurso, por exemplo) e a unidade em que são contados: words (palavras), characters (caracteres com espaços) ou characters-no-spaces (sem espaços). Escreva as quantidades como 15000, ou entre aspas com separador (\"15.000\"). Livros e notas leem o prazo da propriedade de prazo.",
    "settings.weekdaysOff": "Dias de folga na semana",
    "settings.weekdaysOff.desc": "Folgas nunca quebram a sequência, e o ritmo até o prazo conta só os dias de escrita. O que você escreve numa folga conta do mesmo jeito.",
    "settings.datesOff": "Datas de folga",
    "settings.datesOff.desc": "Dias de folga específicos, um por linha, no formato AAAA-MM-DD.",
    "settings.datesOff.invalid": "Não é uma data, ignorado: {dates}",
    "settings.publishing": "Publicação",
    "settings.dateProperty": "Propriedade de data",
    "settings.dateProperty.desc": "Recebe a data de publicação quando você publica.",
    "settings.recommendedProperties": "Propriedades recomendadas",
    "settings.recommendedProperties.desc": "Uma por linha. Publicar avisa quando alguma delas está vazia. Deixe vazio para não verificar.",
    "settings.snapshots": "Versões",
    "settings.snapshotsFolder": "Pasta das versões",
    "settings.snapshotsFolder.desc": "Uma pasta por nota, com arquivos de texto simples (.txt) e um index.json, para que a busca, o grafo e os links os ignorem. O Obsidian Sync só os copia com “Sincronizar todos os outros tipos” ativado; git, iCloud, Dropbox e Syncthing copiam normalmente. Pastas que começam com ponto ficam ocultas, mas o Obsidian Sync não as sincroniza. Mudar esta opção não move as versões existentes.",
    "settings.snapshotsFolder.invalid": "Não salvo. Escolha uma pasta fora de {folder}.",
    "settings.snapshotsFolder.notes": "Não salvo: {folder} já tem notas. Escolha uma pasta só para as versões.",
    "settings.folderProblem.path": "Não salvo. Isso não é uma pasta simples dentro do cofre (sem “..” nem “.”).",
    "settings.folderProblem.outside": "Não salvo. Escolha uma pasta fora de {folder}.",
    "settings.folderProblem.holdsBook": "Não salvo. {folder} tem um livro dentro; escolha uma pasta sem livros.",
    "settings.folderProblem.overlap": "Não salvo. As pastas do Escrita não podem conter umas às outras: esta se sobrepõe a {folder}.",
    "settings.folderProblem.notes": "Não salvo: {folder} já tem arquivos. Escolha uma pasta sem nenhum arquivo seu.",
    "settings.snapshotsFolder.path": "Não salvo. Escolha uma pasta dentro do cofre, sem “..”.",
    "settings.snapshotBeforeFirstEdit": "Versão antes da primeira edição do dia",
    "settings.snapshotBeforeFirstEdit.desc": "Na primeira vez que você altera uma nota acompanhada num dia de escrita, o Escrita guarda o texto como estava.",
    "settings.snapshotsKeepAuto": "Versões automáticas por nota",
    "settings.snapshotsKeepAuto.desc": "As automáticas mais antigas vão para a lixeira. As que você salva nunca são removidas.",
    "settings.outline": "Esboço",
    "settings.ghostBeats": "Beats fantasmas",
    "settings.ghostBeats.desc": "Mostra os beats do esboço dentro dos capítulos como texto cinza até você escrever a cena.",
    "settings.placeholders": "Marcadores",
    "settings.placeholderMarker": "Palavra do marcador",
    "settings.placeholderMarker.desc": "Palavra usada nos marcadores %% {marker}: … %%.",
    "settings.showExplorerDots": "Marcar no explorador os arquivos com marcadores",
    "settings.darlings": "Darlings",
    "settings.darlingsNote": "Nota de darlings dentro de um livro",
    "settings.darlingsNote.desc": "Caminho relativo à pasta do livro, por exemplo Darlings.md ou Notas/Darlings.md.",
    "settings.globalDarlingsNote": "Nota de darlings para o resto",
    "settings.editor": "Editor",
    "settings.enterFlow": "Enter, Enter, Enter",
    "settings.enterFlow.desc": "Nos capítulos e nas outras notas acompanhadas, Enter em linhas vazias além do espaço normal entre parágrafos (veja a próxima opção) cria uma quebra de cena. Num capítulo, mais um Enter depois de uma quebra de cena no fim começa o capítulo seguinte.",
    "settings.paragraphStyle": "Parágrafos são separados por",
    "settings.paragraphStyle.desc": "Diz ao Enter, Enter, Enter quantas linhas vazias são normais.",
    "settings.paragraphStyle.blank": "Uma linha em branco (Markdown padrão)",
    "settings.paragraphStyle.single": "Uma única quebra de linha",
    "settings.smartTypography": "Tipografia inteligente",
    "settings.smartTypography.desc": "-- vira —, ... vira …, aspas retas se curvam enquanto você digita.",
    "settings.typographyScope": "Onde a tipografia inteligente vale",
    "settings.scope.books": "Só nos capítulos de livros",
    "settings.scope.all": "Em todas as notas",
    "settings.quoteStyle": "Aspas",
    "settings.quoteStyle.off": "Não mexer nas aspas",
    "settings.dialogueDash": "Travessão de diálogo",
    "settings.dialogueDash.desc": "-- no começo da linha vira travessão, para diálogos.",
    "common.untitled": "Sem título",
    "common.unit.words.one": "{n} palavra",
    "common.unit.words.other": "{n} palavras",
    "common.unit.characters.one": "{n} caractere",
    "common.unit.characters.other": "{n} caracteres",
    "common.unit.charactersNoSpaces.one": "{n} caractere sem espaços",
    "common.unit.charactersNoSpaces.other": "{n} caracteres sem espaços",
  },
};
