import type { Strings } from "./i18n";

// Shared strings: settings tab and anything used by more than one module.
export const coreStrings: Strings = {
  en: {
    "settings.books": "Books",
    "settings.chaptersFolder": "Chapters folder name",
    "settings.chaptersFolder.desc": "A note is a book when a folder with the same name sits next to it and holds this subfolder. Example: Novels/My Book.md + Novels/My Book/Chapters/.",
    "settings.chapterTemplate": "Chapter template",
    "settings.chapterTemplate.desc": "Note used as the starting content of new chapters. {{title}} and {{date}} are filled in. Leave empty for a blank chapter.",
    "settings.statusProperty": "Status and summary properties",
    "settings.statusProperty.desc": "Frontmatter properties read from each chapter for the outline.",
    "settings.statusColors": "Status colors",
    "settings.statusColors.desc": "One per line: value = color. Colors the dot next to each chapter in the outline.",
    "settings.goals": "Goals",
    "settings.dailyGoal": "Daily word goal",
    "settings.dayEndsAt": "The writing day ends at",
    "settings.dayEndsAt.desc": "Words written after midnight but before this hour count toward the day before.",
    "settings.trackFolders": "Folders to track",
    "settings.trackFolders.desc": "One per line. Only writing in these folders counts toward goals. Leave empty to track the whole vault.",
    "settings.excludeFolders": "Folders to ignore",
    "settings.ignoreJumpsOver": "Ignore jumps over",
    "settings.ignoreJumpsOver.desc": "A single change adding or removing more words than this (a paste, an import, a sync) is not counted as writing.",
    "settings.showStatusBar": "Show progress in the status bar",
    "settings.outline": "Outline",
    "settings.ghostBeats": "Ghost beats",
    "settings.ghostBeats.desc": "Show outline beats inside chapters as gray placeholder text until you write the scene.",
    "settings.placeholders": "Placeholders",
    "settings.placeholderMarker": "Placeholder marker",
    "settings.placeholderMarker.desc": "Word used in %% XXX: … %% placeholders.",
    "settings.showExplorerDots": "Mark files with placeholders in the file explorer",
    "settings.darlings": "Darlings",
    "settings.darlingsNote": "Darlings note inside a book",
    "settings.darlingsNote.desc": "Path relative to the book's folder, e.g. Darlings.md or Notes/Darlings.md.",
    "settings.globalDarlingsNote": "Darlings note for everything else",
    "settings.editor": "Editor",
    "settings.enterFlow": "Enter, Enter, Enter",
    "settings.enterFlow.desc": "In chapters, pressing Enter on empty lines makes a scene break, then a new chapter.",
    "settings.paragraphStyle": "Paragraphs are separated by",
    "settings.paragraphStyle.desc": "Tells Enter, Enter, Enter how many empty lines are normal.",
    "settings.paragraphStyle.blank": "A blank line (standard Markdown)",
    "settings.paragraphStyle.single": "A single line break",
    "settings.smartTypography": "Smart typography",
    "settings.smartTypography.desc": "-- becomes —, ... becomes …, straight quotes curl as you type.",
    "settings.typographyScope": "Where smart typography applies",
    "settings.scope.books": "Only in book chapters",
    "settings.scope.all": "In every note",
    "settings.quoteStyle": "Quotes",
    "settings.quoteStyle.off": "Leave quotes alone",
    "settings.dialogueDash": "Dialogue dash",
    "settings.dialogueDash.desc": "-- at the start of a line becomes an em dash, for dialogue in Portuguese, Spanish, French and others.",
    "settings.spellcheckOnDemand": "Spellcheck only on demand",
    "settings.spellcheckOnDemand.desc": "Hide spelling squiggles while writing. Use the “Toggle spellcheck” command when you're ready to check.",
    "common.untitled": "Untitled",
    "common.words": "{n} words",
  },
  "pt-BR": {
    "settings.books": "Livros",
    "settings.chaptersFolder": "Nome da pasta de capítulos",
    "settings.chaptersFolder.desc": "Uma nota é um livro quando existe, ao lado dela, uma pasta com o mesmo nome contendo esta subpasta. Exemplo: Romances/Meu Livro.md + Romances/Meu Livro/Capítulos/.",
    "settings.chapterTemplate": "Modelo de capítulo",
    "settings.chapterTemplate.desc": "Nota usada como conteúdo inicial dos capítulos novos. {{title}} e {{date}} são preenchidos. Deixe vazio para um capítulo em branco.",
    "settings.statusProperty": "Propriedades de status e resumo",
    "settings.statusProperty.desc": "Propriedades lidas de cada capítulo para o esboço.",
    "settings.statusColors": "Cores de status",
    "settings.statusColors.desc": "Uma por linha: valor = cor. Colore o ponto ao lado de cada capítulo no esboço.",
    "settings.goals": "Metas",
    "settings.dailyGoal": "Meta diária de palavras",
    "settings.dayEndsAt": "O dia de escrita termina às",
    "settings.dayEndsAt.desc": "Palavras escritas depois da meia-noite e antes desta hora contam para o dia anterior.",
    "settings.trackFolders": "Pastas acompanhadas",
    "settings.trackFolders.desc": "Uma por linha. Só o que você escreve nestas pastas conta para as metas. Vazio acompanha o cofre inteiro.",
    "settings.excludeFolders": "Pastas ignoradas",
    "settings.ignoreJumpsOver": "Ignorar saltos acima de",
    "settings.ignoreJumpsOver.desc": "Uma única mudança que adiciona ou remove mais palavras do que isso (colar, importar, sincronizar) não conta como escrita.",
    "settings.showStatusBar": "Mostrar o progresso na barra de status",
    "settings.outline": "Esboço",
    "settings.ghostBeats": "Beats fantasmas",
    "settings.ghostBeats.desc": "Mostra os beats do esboço dentro dos capítulos como texto cinza até você escrever a cena.",
    "settings.placeholders": "Marcadores",
    "settings.placeholderMarker": "Palavra do marcador",
    "settings.placeholderMarker.desc": "Palavra usada nos marcadores %% XXX: … %%.",
    "settings.showExplorerDots": "Marcar no explorador os arquivos com marcadores",
    "settings.darlings": "Darlings",
    "settings.darlingsNote": "Nota de darlings dentro de um livro",
    "settings.darlingsNote.desc": "Caminho relativo à pasta do livro, por exemplo Darlings.md ou Notas/Darlings.md.",
    "settings.globalDarlingsNote": "Nota de darlings para o resto",
    "settings.editor": "Editor",
    "settings.enterFlow": "Enter, Enter, Enter",
    "settings.enterFlow.desc": "Nos capítulos, Enter em linhas vazias cria uma quebra de cena e depois um capítulo novo.",
    "settings.paragraphStyle": "Parágrafos são separados por",
    "settings.paragraphStyle.desc": "Diz ao Enter, Enter, Enter quantas linhas vazias são normais.",
    "settings.paragraphStyle.blank": "Uma linha em branco (Markdown padrão)",
    "settings.paragraphStyle.single": "Uma única quebra de linha",
    "settings.smartTypography": "Tipografia inteligente",
    "settings.smartTypography.desc": "-- vira —, ... vira …, aspas retas se curvam enquanto você digita.",
    "settings.typographyScope": "Onde a tipografia inteligente vale",
    "settings.scope.books": "Só nos capítulos de livros",
    "settings.scope.all": "Em todas as notas",
    "settings.quoteStyle": "Aspas",
    "settings.quoteStyle.off": "Não mexer nas aspas",
    "settings.dialogueDash": "Travessão de diálogo",
    "settings.dialogueDash.desc": "-- no começo da linha vira travessão, para diálogos.",
    "settings.spellcheckOnDemand": "Corretor só quando pedir",
    "settings.spellcheckOnDemand.desc": "Esconde os sublinhados de ortografia enquanto você escreve. Use o comando “Ligar/desligar corretor” quando quiser revisar.",
    "common.untitled": "Sem título",
    "common.words": "{n} palavras",
  },
};
