import type { Strings } from "../i18n";

// Snapshots: the panel, the compare tab and their notices. Word amounts come
// from common.unit.* (core), so "{added}" and "{removed}" arrive formatted.
export const snapshotsStrings: Strings = {
  en: {
    "snapshots.cmd.take": "Take a snapshot",
    "snapshots.cmd.open": "Open snapshots",
    "snapshots.cmd.compareLast": "Compare with the last snapshot",
    "snapshots.cmd.browseDeleted": "Browse snapshots of deleted notes",
    "snapshots.deleted.placeholder": "A deleted (or moved while Escrita was off) note",
    "snapshots.deleted.none": "No snapshots of deleted notes.",
    "snapshots.compare.noteGone": "The note is gone. This is its snapshot's text: copy what you need.",
    "snapshots.compare.pick": "Snapshot",
    "snapshots.menu.take": "Take a snapshot",
    "snapshots.view.title": "Snapshots",
    "snapshots.compare.title": "Compare “{title}”",
    "snapshots.kind.manual": "Snapshot",
    "snapshots.kind.publish": "Before publishing",
    "snapshots.kind.restore": "Before restoring",
    "snapshots.kind.daily": "Before the day's first edit",
    "snapshots.kind.stage": "Stage change",
    "snapshots.name.takeTitle": "Take a snapshot",
    "snapshots.name.renameTitle": "Rename snapshot",
    "snapshots.name.label": "Name",
    "snapshots.name.placeholder": "Snapshot",
    "snapshots.name.take": "Take snapshot",
    "snapshots.name.save": "Save",
    "snapshots.cancel": "Cancel",
    "snapshots.empty.noNote": "Open a note to see its snapshots.",
    "snapshots.empty.none": "No snapshots of this note yet.",
    "snapshots.row.delta": "{delta} since then",
    "snapshots.row.same": "same length now",
    "snapshots.row.unknown": "—",
    "snapshots.action.take": "Take a snapshot",
    "snapshots.action.view": "View",
    "snapshots.action.compare": "Compare",
    "snapshots.action.restore": "Restore",
    "snapshots.action.rename": "Rename",
    "snapshots.action.delete": "Delete",
    "snapshots.notice.taken": "Snapshot “{name}” saved.",
    "snapshots.notice.unchanged": "Nothing changed since the last snapshot.",
    "snapshots.notice.promoted": "The last automatic snapshot has the same text; kept it as “{name}”.",
    "snapshots.notice.stageFailed": "Couldn't save the snapshot for the stage change. See the developer console.",
    "snapshots.notice.autoFailed": "Couldn't save the snapshot “{name}”. See the developer console.",
    "snapshots.notice.failed": "Something went wrong with the snapshots. Nothing was changed; see the developer console.",
    "snapshots.notice.restored": "Restored “{name}”. The previous text is in “Before restoring”.",
    "snapshots.notice.identical": "The note already has this text.",
    "snapshots.notice.changed": "The note changed while restoring. Nothing was replaced; try again.",
    "snapshots.notice.blockChanged": "That passage changed after the comparison. Nothing was replaced.",
    "snapshots.notice.missing": "This snapshot's file is gone.",
    "snapshots.notice.deleted": "Moved “{name}” to the trash.",
    "snapshots.notice.noteGone": "The note is gone.",
    "snapshots.notice.sharedFolder": "This note's snapshots folder holds the snapshots of “{other}”, whose name differs only in special spaces or accents. Rename one of the two notes to keep their snapshots apart.",
    "snapshots.confirm.restoreTitle": "Restore “{name}”?",
    "snapshots.confirm.restoreBody": "The whole note, properties included, becomes the snapshot's text. The current text is saved first as “Before restoring”.",
    "snapshots.confirm.deleteTitle": "Delete “{name}”?",
    "snapshots.confirm.deleteBody": "The snapshot file goes to the trash.",
    "snapshots.compare.against": "Compare with",
    "snapshots.compare.current": "Current text",
    "snapshots.compare.view": "Full text",
    "snapshots.compare.inline": "Inline",
    "snapshots.compare.side": "Side by side",
    "snapshots.compare.refresh": "Refresh",
    "snapshots.compare.summary": "+{added}, −{removed}, {percent}% of paragraphs changed",
    "snapshots.compare.identical": "No differences.",
    "snapshots.compare.degraded": "Long text: some changes are shown as whole paragraphs.",
    "snapshots.compare.frontmatter": "Properties changed",
    "snapshots.compare.useOld": "Use the old version",
    "snapshots.compare.unchanged": "{n} unchanged paragraphs",
    "snapshots.compare.moved": "Moved",
  },
  "pt-BR": {
    "snapshots.cmd.take": "Salvar uma versão",
    "snapshots.cmd.open": "Abrir versões",
    "snapshots.cmd.compareLast": "Comparar com a última versão",
    "snapshots.cmd.browseDeleted": "Ver versões de notas excluídas",
    "snapshots.deleted.placeholder": "Uma nota excluída (ou movida com o Escrita desligado)",
    "snapshots.deleted.none": "Nenhuma versão de nota excluída.",
    "snapshots.compare.noteGone": "A nota não existe mais. Este é o texto da versão: copie o que precisar.",
    "snapshots.compare.pick": "Versão",
    "snapshots.menu.take": "Salvar uma versão",
    "snapshots.view.title": "Versões",
    "snapshots.compare.title": "Comparar “{title}”",
    "snapshots.kind.manual": "Versão",
    "snapshots.kind.publish": "Antes de publicar",
    "snapshots.kind.restore": "Antes de restaurar",
    "snapshots.kind.daily": "Antes da primeira edição do dia",
    "snapshots.kind.stage": "Mudança de estágio",
    "snapshots.name.takeTitle": "Salvar uma versão",
    "snapshots.name.renameTitle": "Renomear versão",
    "snapshots.name.label": "Nome",
    "snapshots.name.placeholder": "Versão",
    "snapshots.name.take": "Salvar versão",
    "snapshots.name.save": "Salvar",
    "snapshots.cancel": "Cancelar",
    "snapshots.empty.noNote": "Abra uma nota para ver as versões dela.",
    "snapshots.empty.none": "Esta nota ainda não tem versões salvas.",
    "snapshots.row.delta": "{delta} desde então",
    "snapshots.row.same": "mesmo tamanho hoje",
    "snapshots.row.unknown": "—",
    "snapshots.action.take": "Salvar uma versão",
    "snapshots.action.view": "Ver",
    "snapshots.action.compare": "Comparar",
    "snapshots.action.restore": "Restaurar",
    "snapshots.action.rename": "Renomear",
    "snapshots.action.delete": "Excluir",
    "snapshots.notice.taken": "Versão “{name}” salva.",
    "snapshots.notice.unchanged": "Nada mudou desde a última versão.",
    "snapshots.notice.promoted": "A última versão automática tem o mesmo texto; ela foi mantida como “{name}”.",
    "snapshots.notice.stageFailed": "Não foi possível salvar a versão da mudança de estágio. Veja o console do desenvolvedor.",
    "snapshots.notice.autoFailed": "Não foi possível salvar a versão “{name}”. Veja o console do desenvolvedor.",
    "snapshots.notice.failed": "Algo deu errado com as versões. Nada foi alterado; veja o console do desenvolvedor.",
    "snapshots.notice.restored": "“{name}” restaurado. O texto anterior está em “Antes de restaurar”.",
    "snapshots.notice.identical": "A nota já tem este texto.",
    "snapshots.notice.changed": "A nota mudou durante a restauração. Nada foi substituído; tente de novo.",
    "snapshots.notice.blockChanged": "Esse trecho mudou depois da comparação. Nada foi substituído.",
    "snapshots.notice.missing": "O arquivo desta versão não existe mais.",
    "snapshots.notice.deleted": "“{name}” foi para a lixeira.",
    "snapshots.notice.noteGone": "A nota não existe mais.",
    "snapshots.notice.sharedFolder": "A pasta de versões desta nota guarda as versões de “{other}”, cujo nome só difere em espaços especiais ou acentos. Renomeie uma das duas notas para separar as versões.",
    "snapshots.confirm.restoreTitle": "Restaurar “{name}”?",
    "snapshots.confirm.restoreBody": "A nota inteira, com as propriedades, passa a ter o texto da versão. O texto atual é salvo antes como “Antes de restaurar”.",
    "snapshots.confirm.deleteTitle": "Excluir “{name}”?",
    "snapshots.confirm.deleteBody": "O arquivo da versão vai para a lixeira.",
    "snapshots.compare.against": "Comparar com",
    "snapshots.compare.current": "Texto atual",
    "snapshots.compare.view": "Texto completo",
    "snapshots.compare.inline": "No texto",
    "snapshots.compare.side": "Lado a lado",
    "snapshots.compare.refresh": "Atualizar",
    "snapshots.compare.summary": "+{added}, −{removed}, {percent}% dos parágrafos mudaram",
    "snapshots.compare.identical": "Nenhuma diferença.",
    "snapshots.compare.degraded": "Texto longo: algumas mudanças aparecem como parágrafos inteiros.",
    "snapshots.compare.frontmatter": "Propriedades mudaram",
    "snapshots.compare.useOld": "Usar o texto antigo",
    "snapshots.compare.unchanged": "{n} parágrafos sem mudança",
    "snapshots.compare.moved": "Movido",
  },
};
