import type { Strings } from "../i18n";

// Plurals use ".one" / ".other" suffixes; see plural() in ./format.ts.
export const goalsStrings: Strings = {
  en: {
    "goals.cmd.open": "Open progress",
    "goals.cmd.start": "Start a sprint",
    "goals.cmd.stop": "Stop the sprint",

    "goals.words.one": "{n} word",
    "goals.words.other": "{n} words",
    "goals.days.one": "{n} day",
    "goals.days.other": "{n} days",
    "goals.chapters.one": "{n} chapter",
    "goals.chapters.other": "{n} chapters",

    "goals.status.tooltip": "Open progress",
    "goals.status.chapterBook": "chapter {chapter} · book {book}",
    "goals.status.book": "book {book}",
    "goals.status.selected.one": "{n} word selected",
    "goals.status.selected.other": "{n} words selected",
    "goals.status.today": "{n} / {goal} today",
    "goals.status.todayNoGoal": "{n} today",
    "goals.status.streak.one": "{n} day in a row",
    "goals.status.streak.other": "{n} days in a row",
    "goals.status.stop": "stop",
    "goals.status.stopTooltip": "Stop the sprint",

    "goals.progress.title": "Progress",
    "goals.progress.allWriting": "All writing",
    "goals.tile.today": "Today",
    "goals.tile.cut.one": "{n} cut while revising",
    "goals.tile.cut.other": "{n} cut while revising",
    "goals.tile.goalMet": "Daily goal met",
    "goals.tile.toGo.one": "{n} to go",
    "goals.tile.toGo.other": "{n} to go",
    "goals.tile.book": "Book",
    "goals.tile.bookSub": "{pct}% · {chapters}",
    "goals.tile.noGoal": "{chapters} · no goal yet",
    "goals.tile.streak": "Streak",
    "goals.tile.noStreak": "No streak yet",
    "goals.tile.metOf": "goal met {n} of {days} days",
    "goals.tile.week": "This week",
    "goals.tile.weekSub": "{n} a day on average",

    "goals.chart.label": "Words written per day over the last {n} days",
    "goals.chart.today": "today",
    "goals.legend.met": "Goal met",
    "goals.legend.words": "Words written",
    "goals.legend.goal": "Daily goal",
    "goals.legend.total": "Book total",

    "goals.pace.onTrack": "On track.",
    "goals.pace.behind": "Behind.",
    "goals.pace.need.one": "{days} left until {date}: you need {words} a day.",
    "goals.pace.need.other": "{days} left until {date}: you need {words} a day.",
    "goals.pace.finish": "At your current pace ({avg}/day, 7-day average) you finish on {date}.",
    "goals.pace.finishEarly": "At your current pace ({avg}/day, 7-day average) you finish on {date}, {days} early.",
    "goals.pace.finishLate": "At your current pace ({avg}/day, 7-day average) you finish on {date}, {days} late.",
    "goals.pace.finishOnTime": "At your current pace ({avg}/day, 7-day average) you finish on {date}, right on the deadline.",
    "goals.pace.noPace": "You haven't added to this book in the last 7 days, so there's no pace to project yet.",
    "goals.pace.revising": "This week you cut as much as you added while revising, so there's no pace to project yet.",
    "goals.pace.noDeadline": "Set a deadline to see how many words a day you need.",
    "goals.pace.overdue.one": "The deadline ({date}) has passed, with {n} word to go. Set a new one below.",
    "goals.pace.overdue.other": "The deadline ({date}) has passed, with {n} words to go. Set a new one below.",
    "goals.pace.done": "Goal reached: {total} of {goal} words. Congratulations!",
    "goals.pace.noGoal": "Set a book goal below to see your pacing.",

    "goals.set.daily": "Daily goal",
    "goals.set.book": "Book goal",
    "goals.set.deadline": "Deadline",
    "goals.set.dayEnds": "The day ends at",
    "goals.set.saveError": "Couldn't save to the book note.",
    "goals.set.invalidNumber": "Type a whole number, like 1000. Nothing was changed.",
    "goals.error": "Something went wrong. The developer console has the details.",

    "goals.sprint.title": "Sprint",
    "goals.sprint.minutes": "{n} min",
    "goals.sprint.target": "Target words",
    "goals.sprint.length": "Sprint length",
    "goals.sprint.start": "Start sprint",
    "goals.sprint.stop": "Stop sprint",
    "goals.sprint.running": "{time} left · {words} / {target}",
    "goals.sprint.runningNoTarget": "{time} left · {words}",
    "goals.sprint.started": "Sprint started: {min} min, target {target}.",
    "goals.sprint.startedNoTarget": "Sprint started: {min} min.",
    "goals.sprint.already": "A sprint is already running.",
    "goals.sprint.targetReached": "Sprint target reached: {words}. Keep going!",
    "goals.sprint.done": "Sprint done: {words} in {min} min ({rate} an hour)",
  },
  "pt-BR": {
    "goals.cmd.open": "Abrir progresso",
    "goals.cmd.start": "Começar um sprint",
    "goals.cmd.stop": "Parar o sprint",

    "goals.words.one": "{n} palavra",
    "goals.words.other": "{n} palavras",
    "goals.days.one": "{n} dia",
    "goals.days.other": "{n} dias",
    "goals.chapters.one": "{n} capítulo",
    "goals.chapters.other": "{n} capítulos",

    "goals.status.tooltip": "Abrir progresso",
    "goals.status.chapterBook": "capítulo {chapter} · livro {book}",
    "goals.status.book": "livro {book}",
    "goals.status.selected.one": "{n} palavra selecionada",
    "goals.status.selected.other": "{n} palavras selecionadas",
    "goals.status.today": "{n} / {goal} hoje",
    "goals.status.todayNoGoal": "{n} hoje",
    "goals.status.streak.one": "{n} dia seguido",
    "goals.status.streak.other": "{n} dias seguidos",
    "goals.status.stop": "parar",
    "goals.status.stopTooltip": "Parar o sprint",

    "goals.progress.title": "Progresso",
    "goals.progress.allWriting": "Toda a escrita",
    "goals.tile.today": "Hoje",
    "goals.tile.cut.one": "{n} cortada na revisão",
    "goals.tile.cut.other": "{n} cortadas na revisão",
    "goals.tile.goalMet": "Meta do dia batida",
    "goals.tile.toGo.one": "falta {n}",
    "goals.tile.toGo.other": "faltam {n}",
    "goals.tile.book": "Livro",
    "goals.tile.bookSub": "{pct}% · {chapters}",
    "goals.tile.noGoal": "{chapters} · ainda sem meta",
    "goals.tile.streak": "Sequência",
    "goals.tile.noStreak": "Nenhuma sequência ainda",
    "goals.tile.metOf": "meta batida em {n} de {days} dias",
    "goals.tile.week": "Esta semana",
    "goals.tile.weekSub": "{n} por dia, em média",

    "goals.chart.label": "Palavras escritas por dia nos últimos {n} dias",
    "goals.chart.today": "hoje",
    "goals.legend.met": "Meta batida",
    "goals.legend.words": "Palavras escritas",
    "goals.legend.goal": "Meta diária",
    "goals.legend.total": "Total do livro",

    "goals.pace.onTrack": "No ritmo.",
    "goals.pace.behind": "Atrasado.",
    "goals.pace.need.one": "Falta {days} até {date}: você precisa de {words} por dia.",
    "goals.pace.need.other": "Faltam {days} até {date}: você precisa de {words} por dia.",
    "goals.pace.finish": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}.",
    "goals.pace.finishEarly": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}, {days} antes do prazo.",
    "goals.pace.finishLate": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}, {days} depois do prazo.",
    "goals.pace.finishOnTime": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}, bem no prazo.",
    "goals.pace.noPace": "Você não avançou neste livro nos últimos 7 dias, então ainda não dá para projetar um ritmo.",
    "goals.pace.revising": "Nesta semana, revisando, você cortou tanto quanto escreveu, então ainda não dá para projetar um ritmo.",
    "goals.pace.noDeadline": "Defina um prazo para ver quantas palavras por dia você precisa escrever.",
    "goals.pace.overdue.one": "O prazo ({date}) já passou e ainda falta {n} palavra. Defina um novo abaixo.",
    "goals.pace.overdue.other": "O prazo ({date}) já passou e ainda faltam {n} palavras. Defina um novo abaixo.",
    "goals.pace.done": "Meta alcançada: {total} de {goal} palavras. Parabéns!",
    "goals.pace.noGoal": "Defina uma meta para o livro abaixo para acompanhar o seu ritmo.",

    "goals.set.daily": "Meta diária",
    "goals.set.book": "Meta do livro",
    "goals.set.deadline": "Prazo",
    "goals.set.dayEnds": "O dia termina às",
    "goals.set.saveError": "Não foi possível salvar na nota do livro.",
    "goals.set.invalidNumber": "Digite um número inteiro, como 1000. Nada foi alterado.",
    "goals.error": "Algo deu errado. Os detalhes estão no console do desenvolvedor.",

    "goals.sprint.title": "Sprint",
    "goals.sprint.minutes": "{n} min",
    "goals.sprint.target": "Meta de palavras",
    "goals.sprint.length": "Duração do sprint",
    "goals.sprint.start": "Começar sprint",
    "goals.sprint.stop": "Parar sprint",
    "goals.sprint.running": "faltam {time} · {words} / {target}",
    "goals.sprint.runningNoTarget": "faltam {time} · {words}",
    "goals.sprint.started": "Sprint começou: {min} min, meta de {target}.",
    "goals.sprint.startedNoTarget": "Sprint começou: {min} min.",
    "goals.sprint.already": "Já tem um sprint em andamento.",
    "goals.sprint.targetReached": "Meta do sprint alcançada: {words}. Continue!",
    "goals.sprint.done": "Sprint encerrado: {words} em {min} min ({rate} por hora)",
  },
};
