import type { Strings } from "../i18n";

// Plurals use ".one" / ".other" suffixes; see plural() in src/i18n.ts.
export const goalsStrings: Strings = {
  en: {
    "goals.cmd.open": "Open progress",
    "goals.cmd.start": "Start a sprint",
    "goals.cmd.stop": "Stop the sprint",

    "goals.days.one": "{n} day",
    "goals.days.other": "{n} days",
    "goals.chapters.one": "{n} chapter",
    "goals.chapters.other": "{n} chapters",
    "goals.writingDays.one": "{n} writing day",
    "goals.writingDays.other": "{n} writing days",

    "goals.status.tooltip": "Open progress",
    "goals.status.chapterBook": "chapter {chapter} · book {book}",
    "goals.status.book": "book {book}",
    "goals.status.selected.one": "{n} word selected",
    "goals.status.selected.other": "{n} words selected",
    "goals.status.today": "{n} / {goal} today",
    "goals.status.todayNoGoal": "{n} today",
    "goals.status.streak.one": "{n} day in a row",
    "goals.status.streak.other": "{n} days in a row",
    "goals.status.stop": "stop",
    "goals.status.stopTooltip": "Stop the sprint",
    "goals.status.over": "+{n} over the limit",

    "goals.progress.title": "Progress",
    "goals.progress.allWriting": "All writing",
    "goals.tile.today": "Today",
    "goals.tile.cut.one": "{n} cut while revising",
    "goals.tile.cut.other": "{n} cut while revising",
    "goals.tile.goalMet": "Daily goal met",
    "goals.tile.toGo.one": "{n} to go",
    "goals.tile.toGo.other": "{n} to go",
    "goals.tile.book": "Book",
    "goals.tile.bookSub": "{pct}% · {chapters}",
    "goals.tile.noGoal": "{chapters} · no goal yet",
    "goals.tile.streak": "Streak",
    "goals.tile.noStreak": "No streak yet",
    "goals.tile.metOf": "goal met {n} of {days} days",
    "goals.tile.week": "This week",
    "goals.tile.weekSub": "{n} a day on average",
    "goals.tile.piece": "This piece",
    "goals.tile.pieceSub": "{pct}% of the target",
    "goals.tile.pieceNoTarget": "No target yet",
    "goals.tile.limit": "Limit: {limit}",
    "goals.tile.nearLimit": "Close to the limit ({limit})",
    "goals.tile.limitMark": "Limit",
    "goals.tile.targetMark": "Target",

    "goals.chart.label": "Words written per day over the last {n} days",
    "goals.chart.today": "today",
    "goals.legend.met": "Goal met",
    "goals.legend.words": "Words written",
    "goals.legend.goal": "Daily goal",
    "goals.legend.total": "Book total",
    "goals.legend.pieceTotal": "Piece total",
    "goals.legend.off": "Day off",
    "goals.chart.dayOff": "{date}: day off",

    "goals.pace.onTrack": "On track.",
    "goals.pace.behind": "Behind.",
    "goals.pace.need.one": "{days} left until {date}: you need {words} a day.",
    "goals.pace.need.other": "{days} left until {date}: you need {words} a day.",
    "goals.pace.finish": "At your current pace ({avg}/day, 7-day average) you finish on {date}.",
    "goals.pace.finishEarly": "At your current pace ({avg}/day, 7-day average) you finish on {date}, {days} early.",
    "goals.pace.finishLate": "At your current pace ({avg}/day, 7-day average) you finish on {date}, {days} late.",
    "goals.pace.finishOnTime": "At your current pace ({avg}/day, 7-day average) you finish on {date}, right on the deadline.",
    "goals.pace.noPace": "You haven't added to this book in the last 7 days, so there's no pace to project yet.",
    "goals.pace.revising": "This week you cut as much as you added while revising, so there's no pace to project yet.",
    "goals.pace.noDeadline": "Set a deadline to see how many words a day you need.",
    "goals.pace.overdue.one": "The deadline ({date}) has passed, with {n} word to go. Set a new one below.",
    "goals.pace.overdue.other": "The deadline ({date}) has passed, with {n} words to go. Set a new one below.",
    "goals.pace.done": "Goal reached: {total} of {goal} words. Congratulations!",
    "goals.pace.noGoal": "Set a book goal below to see your pacing.",
    "goals.pace.needWriting.one": "{days} left until {date} ({writing}): you need {words} a day.",
    "goals.pace.needWriting.other": "{days} left until {date} ({writing}): you need {words} a day.",
    "goals.pace.pieceNoTarget": "Set a target below to see your pacing.",
    "goals.pace.pieceDone": "Target reached: {total} of {goal}.",
    "goals.pace.pieceOverdue.one": "The deadline ({date}) has passed, with {left} to go. Set a new one below.",
    "goals.pace.pieceOverdue.other": "The deadline ({date}) has passed, with {left} to go. Set a new one below.",
    "goals.pace.pieceNoPace": "You haven't added to this piece in the last 7 days, so there's no pace to project yet.",
    "goals.pace.pieceNoDeadline": "Set a deadline to see how much you need to write a day.",
    "goals.pace.charsEstimate": "Characters a day are estimated from your words a day and this piece's characters per word.",

    "goals.set.daily": "Daily goal",
    "goals.set.book": "Book goal",
    "goals.set.deadline": "Deadline",
    "goals.set.dayEnds": "The day ends at",
    "goals.set.saveError": "Couldn't save to the book note.",
    "goals.set.target": "Target",
    "goals.set.limit": "Limit",
    "goals.set.unit": "Unit",
    "goals.set.unitWords": "Words",
    "goals.set.unitCharacters": "Characters (with spaces)",
    "goals.set.unitCharactersNoSpaces": "Characters (no spaces)",
    "goals.set.saveErrorNote": "Couldn't save to the note.",
    "goals.set.invalidNumber": "Type a whole number, like 1000. Nothing was changed.",
    "goals.error": "Something went wrong. The developer console has the details.",

    "goals.sprint.title": "Sprint",
    "goals.sprint.minutes": "{n} min",
    "goals.sprint.target": "Target words",
    "goals.sprint.length": "Sprint length",
    "goals.sprint.start": "Start sprint",
    "goals.sprint.stop": "Stop sprint",
    "goals.sprint.running": "{time} left · {words} / {target}",
    "goals.sprint.runningNoTarget": "{time} left · {words}",
    "goals.sprint.started": "Sprint started: {min} min, target {target}.",
    "goals.sprint.startedNoTarget": "Sprint started: {min} min.",
    "goals.sprint.already": "A sprint is already running.",
    "goals.sprint.targetReached": "Sprint target reached: {words}. Keep going!",
    "goals.sprint.done": "Sprint done: {words} in {min} min ({rate} an hour)",
  },
  "pt-BR": {
    "goals.cmd.open": "Abrir progresso",
    "goals.cmd.start": "Começar um sprint",
    "goals.cmd.stop": "Parar o sprint",

    "goals.days.one": "{n} dia",
    "goals.days.other": "{n} dias",
    "goals.chapters.one": "{n} capítulo",
    "goals.chapters.other": "{n} capítulos",
    "goals.writingDays.one": "{n} dia de escrita",
    "goals.writingDays.other": "{n} dias de escrita",

    "goals.status.tooltip": "Abrir progresso",
    "goals.status.chapterBook": "capítulo {chapter} · livro {book}",
    "goals.status.book": "livro {book}",
    "goals.status.selected.one": "{n} palavra selecionada",
    "goals.status.selected.other": "{n} palavras selecionadas",
    "goals.status.today": "{n} / {goal} hoje",
    "goals.status.todayNoGoal": "{n} hoje",
    "goals.status.streak.one": "{n} dia seguido",
    "goals.status.streak.other": "{n} dias seguidos",
    "goals.status.stop": "parar",
    "goals.status.stopTooltip": "Parar o sprint",
    "goals.status.over": "+{n} acima do limite",

    "goals.progress.title": "Progresso",
    "goals.progress.allWriting": "Toda a escrita",
    "goals.tile.today": "Hoje",
    "goals.tile.cut.one": "{n} cortada na revisão",
    "goals.tile.cut.other": "{n} cortadas na revisão",
    "goals.tile.goalMet": "Meta do dia batida",
    "goals.tile.toGo.one": "falta {n}",
    "goals.tile.toGo.other": "faltam {n}",
    "goals.tile.book": "Livro",
    "goals.tile.bookSub": "{pct}% · {chapters}",
    "goals.tile.noGoal": "{chapters} · ainda sem meta",
    "goals.tile.streak": "Sequência",
    "goals.tile.noStreak": "Nenhuma sequência ainda",
    "goals.tile.metOf": "meta batida em {n} de {days} dias",
    "goals.tile.week": "Esta semana",
    "goals.tile.weekSub": "{n} por dia, em média",
    "goals.tile.piece": "Este texto",
    "goals.tile.pieceSub": "{pct}% da meta",
    "goals.tile.pieceNoTarget": "Ainda sem meta",
    "goals.tile.limit": "Limite: {limit}",
    "goals.tile.nearLimit": "Perto do limite ({limit})",
    "goals.tile.limitMark": "Limite",
    "goals.tile.targetMark": "Meta",

    "goals.chart.label": "Palavras escritas por dia nos últimos {n} dias",
    "goals.chart.today": "hoje",
    "goals.legend.met": "Meta batida",
    "goals.legend.words": "Palavras escritas",
    "goals.legend.goal": "Meta diária",
    "goals.legend.total": "Total do livro",
    "goals.legend.pieceTotal": "Total do texto",
    "goals.legend.off": "Folga",
    "goals.chart.dayOff": "{date}: folga",

    "goals.pace.onTrack": "No ritmo.",
    "goals.pace.behind": "Atrasado.",
    "goals.pace.need.one": "Falta {days} até {date}: você precisa de {words} por dia.",
    "goals.pace.need.other": "Faltam {days} até {date}: você precisa de {words} por dia.",
    "goals.pace.finish": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}.",
    "goals.pace.finishEarly": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}, {days} antes do prazo.",
    "goals.pace.finishLate": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}, {days} depois do prazo.",
    "goals.pace.finishOnTime": "No seu ritmo atual ({avg}/dia, média de 7 dias), você termina em {date}, bem no prazo.",
    "goals.pace.noPace": "Você não avançou neste livro nos últimos 7 dias, então ainda não dá para projetar um ritmo.",
    "goals.pace.revising": "Nesta semana, revisando, você cortou tanto quanto escreveu, então ainda não dá para projetar um ritmo.",
    "goals.pace.noDeadline": "Defina um prazo para ver quantas palavras por dia você precisa escrever.",
    "goals.pace.overdue.one": "O prazo ({date}) já passou e ainda falta {n} palavra. Defina um novo abaixo.",
    "goals.pace.overdue.other": "O prazo ({date}) já passou e ainda faltam {n} palavras. Defina um novo abaixo.",
    "goals.pace.done": "Meta alcançada: {total} de {goal} palavras. Parabéns!",
    "goals.pace.noGoal": "Defina uma meta para o livro abaixo para acompanhar o seu ritmo.",
    "goals.pace.needWriting.one": "Falta {days} até {date} ({writing}): você precisa de {words} por dia.",
    "goals.pace.needWriting.other": "Faltam {days} até {date} ({writing}): você precisa de {words} por dia.",
    "goals.pace.pieceNoTarget": "Defina uma meta abaixo para acompanhar o seu ritmo.",
    "goals.pace.pieceDone": "Meta alcançada: {total} de {goal}.",
    "goals.pace.pieceOverdue.one": "O prazo ({date}) já passou e ainda falta {left}. Defina um novo abaixo.",
    "goals.pace.pieceOverdue.other": "O prazo ({date}) já passou e ainda faltam {left}. Defina um novo abaixo.",
    "goals.pace.pieceNoPace": "Você não avançou neste texto nos últimos 7 dias, então ainda não dá para projetar um ritmo.",
    "goals.pace.pieceNoDeadline": "Defina um prazo para ver quanto você precisa escrever por dia.",
    "goals.pace.charsEstimate": "Os caracteres por dia são estimados a partir das suas palavras por dia e da média de caracteres por palavra deste texto.",

    "goals.set.daily": "Meta diária",
    "goals.set.book": "Meta do livro",
    "goals.set.deadline": "Prazo",
    "goals.set.dayEnds": "O dia termina às",
    "goals.set.saveError": "Não foi possível salvar na nota do livro.",
    "goals.set.target": "Meta",
    "goals.set.limit": "Limite",
    "goals.set.unit": "Unidade",
    "goals.set.unitWords": "Palavras",
    "goals.set.unitCharacters": "Caracteres (com espaços)",
    "goals.set.unitCharactersNoSpaces": "Caracteres (sem espaços)",
    "goals.set.saveErrorNote": "Não foi possível salvar na nota.",
    "goals.set.invalidNumber": "Digite um número inteiro, como 1000. Nada foi alterado.",
    "goals.error": "Algo deu errado. Os detalhes estão no console do desenvolvedor.",

    "goals.sprint.title": "Sprint",
    "goals.sprint.minutes": "{n} min",
    "goals.sprint.target": "Meta de palavras",
    "goals.sprint.length": "Duração do sprint",
    "goals.sprint.start": "Começar sprint",
    "goals.sprint.stop": "Parar sprint",
    "goals.sprint.running": "faltam {time} · {words} / {target}",
    "goals.sprint.runningNoTarget": "faltam {time} · {words}",
    "goals.sprint.started": "Sprint começou: {min} min, meta de {target}.",
    "goals.sprint.startedNoTarget": "Sprint começou: {min} min.",
    "goals.sprint.already": "Já tem um sprint em andamento.",
    "goals.sprint.targetReached": "Meta do sprint alcançada: {words}. Continue!",
    "goals.sprint.done": "Sprint encerrado: {words} em {min} min ({rate} por hora)",
  },
};
