import type { Strings } from "../i18n";

// The create-entry modal, plant a thread, close a thread
// and the editor menu items. Keys: universe.create.*
export const universeCreateStrings: Strings = {
  en: {
    "universe.create.title": "New entry",
    "universe.create.name": "Name",
    "universe.create.kind": "Type",
    "universe.create.alias": "Another alias (optional)",
    "universe.create.aliasPlaceholder": "Nickname, the granddaughter…",
    "universe.create.link": "Turn this occurrence into a link",
    "universe.create.whereUniverseTpl": "Creates {path} from {template}, with {type} and {universe}.",
    "universe.create.whereUniverse": "Creates {path}, with {type} and {universe}.",
    "universe.create.whereBookTpl": "Creates {path} from {template}, with {type}. No {universeProp}.",
    "universe.create.whereBook": "Creates {path}, with {type}. No {universeProp}.",
    "universe.create.dupName": "\"{name}\" is already the name of {entry} ({kind}).",
    "universe.create.dupAlias": "\"{name}\" is already an alias of {entry} ({kind}).",
    "universe.create.fileExists": "A note already exists at {path}.",
    "universe.create.open": "Open {name}",
    "universe.create.justLink": "Just link here",
    "universe.create.createAnyway": "Create another anyway",
    "universe.create.cancel": "Cancel",
    "universe.create.create": "Create",
    "universe.create.menu.close": "Close thread…",
    "universe.create.menu.reopen": "Reopen thread",

    "universe.create.notice.noUniverse": "\"{name}\" is not part of a universe. Add it from the universe panel or set a default universe folder.",
    "universe.create.notice.perBook": "Per book: entries live inside a book. \"{name}\" is a standalone note.",
    "universe.create.notice.created": "{name} created in {folder}.",
    "universe.create.notice.failed": "Couldn't create the entry.",
    "universe.create.notice.linkFailed": "The text changed, so no link was added. Nothing else was altered.",

    "universe.create.plant.done": "Thread planted. It shows up in Open threads.",
    "universe.create.plant.refused": "A thread can't go here (properties, code or a multi-line comment).",

    "universe.create.close.title": "Close \"{text}\"",
    "universe.create.close.answer": "Answered in (optional)",
    "universe.create.close.placeholder": "Title of a work…",
    "universe.create.close.preview": "In {note}, the marker becomes",
    "universe.create.close.confirm": "Close",
    "universe.create.close.done": "Thread closed in {note}.",
    "universe.create.close.unknown": "\"{target}\" is not a known work. The thread was closed with the link anyway.",
    "universe.create.close.changed": "The thread moved or changed. Nothing was altered.",
    "universe.create.reopen.done": "Thread reopened in {note}.",
  },
  "pt-BR": {
    "universe.create.title": "Nova entrada",
    "universe.create.name": "Nome",
    "universe.create.kind": "Tipo",
    "universe.create.alias": "Outro apelido (opcional)",
    "universe.create.aliasPlaceholder": "Mari, a neta…",
    "universe.create.link": "Transformar esta ocorrência em link",
    "universe.create.whereUniverseTpl": "Cria {path} a partir de {template}, com {type} e {universe}.",
    "universe.create.whereUniverse": "Cria {path}, com {type} e {universe}.",
    "universe.create.whereBookTpl": "Cria {path} a partir de {template}, com {type}. Sem {universeProp}.",
    "universe.create.whereBook": "Cria {path}, com {type}. Sem {universeProp}.",
    "universe.create.dupName": "\"{name}\" já é o nome de {entry} ({kind}).",
    "universe.create.dupAlias": "\"{name}\" já é apelido de {entry} ({kind}).",
    "universe.create.fileExists": "Já existe uma nota em {path}.",
    "universe.create.open": "Abrir {name}",
    "universe.create.justLink": "Só linkar aqui",
    "universe.create.createAnyway": "Criar outra assim mesmo",
    "universe.create.cancel": "Cancelar",
    "universe.create.create": "Criar",
    "universe.create.menu.close": "Fechar o fio…",
    "universe.create.menu.reopen": "Reabrir o fio",

    "universe.create.notice.noUniverse": "\"{name}\" não faz parte de um universo. Adicione-o pelo painel do universo ou defina um universo padrão para a pasta.",
    "universe.create.notice.perBook": "Por livro: entradas ficam dentro de um livro. \"{name}\" é uma nota solta.",
    "universe.create.notice.created": "{name} criada em {folder}.",
    "universe.create.notice.failed": "Não deu para criar a entrada.",
    "universe.create.notice.linkFailed": "O texto mudou, então o link não foi adicionado. Nada mais foi alterado.",

    "universe.create.plant.done": "Fio plantado. Ele aparece em \"Fios abertos\".",
    "universe.create.plant.refused": "Um fio não pode ficar aqui (propriedades, código ou comentário de várias linhas).",

    "universe.create.close.title": "Fechar \"{text}\"",
    "universe.create.close.answer": "Respondido em (opcional)",
    "universe.create.close.placeholder": "Título de uma obra…",
    "universe.create.close.preview": "Em {note}, o marcador vira",
    "universe.create.close.confirm": "Fechar",
    "universe.create.close.done": "Fio fechado em {note}.",
    "universe.create.close.unknown": "\"{target}\" não é uma obra conhecida. O fio foi fechado com o link assim mesmo.",
    "universe.create.close.changed": "O fio mudou de lugar ou de texto. Nada foi alterado.",
    "universe.create.reopen.done": "Fio reaberto em {note}.",
  },
};
