import type { Strings } from "../i18n";

// The migration preview, progress and notices. Keys: universe.migrate.*
export const universeMigrateStrings: Strings = {
  en: {
    "universe.migrate.title": "Move {book}'s entries to {universe}",
    "universe.migrate.intro.one": "{n} note changes folder. Obsidian updates the links across the vault.",
    "universe.migrate.intro.other": "{n} notes change folder. Obsidian updates the links across the vault.",
    "universe.migrate.groupCount": "{moved} of {total}",
    "universe.migrate.clash": "already exists in {folder} · stays where it is",
    "universe.migrate.addedType": "+ {prop}: {value}",
    "universe.migrate.more": "+ {n} more",
    "universe.migrate.addType.one": "Add {prop} where it's missing, from the source folder ({n} note)",
    "universe.migrate.addType.other": "Add {prop} where it's missing, from the source folder ({n} notes)",
    "universe.migrate.addUniverse": "Add {prop}: \"{link}\" to the book note (it has none yet)",
    "universe.migrate.emptyFolders": "Empty folders stay. Delete them if you like.",
    "universe.migrate.cancel": "Cancel",
    "universe.migrate.move.one": "Move {n} note",
    "universe.migrate.move.other": "Move {n} notes",
    "universe.migrate.foot": "Moves one note at a time. A name clash never overwrites: the note stays and shows in the final notice. Properties are only added, never changed, and only with the box ticked.",
    "universe.migrate.progressTitle": "Moving {book}'s entries",
    "universe.migrate.progress": "{done} of {total} · {name}",
    "universe.migrate.noCancel": "It can't be cancelled midway. Every note already moved has its links right.",
    "universe.migrate.done.one": "{n} note moved to {universe}.",
    "universe.migrate.done.other": "{n} notes moved to {universe}.",
    "universe.migrate.clashed.one": "{n} stayed in {folder} because the name already exists: {names}.",
    "universe.migrate.clashed.other": "{n} stayed in {folder} because the name already exists: {names}.",
    "universe.migrate.failed.one": "{n} couldn't be moved: {names}.",
    "universe.migrate.failed.other": "{n} couldn't be moved: {names}.",
    "universe.migrate.noFolders": "{book} has no entry folders ({folders}). Nothing to move.",
    "universe.migrate.wrongMode": "Moving entries only works in universe mode. Change it in Settings › Escrita › Universe.",
    "universe.migrate.noBook": "Open a book note or one of its chapters first.",
  },
  "pt-BR": {
    "universe.migrate.title": "Mover as entradas de {book} para {universe}",
    "universe.migrate.intro.one": "{n} nota muda de pasta. Os links em todo o cofre são atualizados pelo Obsidian.",
    "universe.migrate.intro.other": "{n} notas mudam de pasta. Os links em todo o cofre são atualizados pelo Obsidian.",
    "universe.migrate.groupCount": "{moved} de {total}",
    "universe.migrate.clash": "já existe em {folder} · fica onde está",
    "universe.migrate.addedType": "+ {prop}: {value}",
    "universe.migrate.more": "+ {n}",
    "universe.migrate.addType.one": "Pôr {prop} onde falta, pela pasta de origem ({n} nota)",
    "universe.migrate.addType.other": "Pôr {prop} onde falta, pela pasta de origem ({n} notas)",
    "universe.migrate.addUniverse": "Pôr {prop}: \"{link}\" na nota do livro (ainda não tem)",
    "universe.migrate.emptyFolders": "As pastas vazias ficam. Apague se quiser.",
    "universe.migrate.cancel": "Cancelar",
    "universe.migrate.move.one": "Mover {n} nota",
    "universe.migrate.move.other": "Mover {n} notas",
    "universe.migrate.foot": "Move uma nota por vez. Conflito de nome nunca sobrescreve: a nota fica e aparece no aviso final. Propriedades só são acrescentadas (nunca trocadas), e só com a caixa marcada.",
    "universe.migrate.progressTitle": "Movendo as entradas de {book}",
    "universe.migrate.progress": "{done} de {total} · {name}",
    "universe.migrate.noCancel": "Não dá para cancelar no meio. Cada nota movida já está com os links certos.",
    "universe.migrate.done.one": "{n} nota movida para {universe}.",
    "universe.migrate.done.other": "{n} notas movidas para {universe}.",
    "universe.migrate.clashed.one": "{n} ficou em {folder} porque o nome já existe: {names}.",
    "universe.migrate.clashed.other": "{n} ficaram em {folder} porque o nome já existe: {names}.",
    "universe.migrate.failed.one": "{n} não foi movida: {names}.",
    "universe.migrate.failed.other": "{n} não foram movidas: {names}.",
    "universe.migrate.noFolders": "{book} não tem pastas de entradas ({folders}). Nada para mover.",
    "universe.migrate.wrongMode": "Mover entradas só no modo universo. Mude em Configurações › Escrita › Universo.",
    "universe.migrate.noBook": "Abra a nota de um livro ou um dos capítulos primeiro.",
  },
};
