import type { Strings } from "../i18n";

// The universe module: commands, the settings section and the module's own notices.
// Keys: universe.cmd.*, universe.settings.*, universe.kind.*, universe.notice.*.
// (view-strings, create-strings and migrate-strings hold the rest.)
export const universeStrings: Strings = {
  en: {
    "universe.cmd.open": "Open the universe panel",
    "universe.cmd.showThreads": "Show open threads",
    "universe.cmd.plantThread": "Plant a thread",
    "universe.cmd.createEntry": "Create universe entry",
    "universe.cmd.closeThread": "Close thread",
    "universe.cmd.migrate": "Move this book's entries to the universe",

    "universe.kind.character": "Character",
    "universe.kind.place": "Place",
    "universe.kind.object": "Object",
    "universe.kind.group": "Group",
    "universe.kind.event": "Event",

    "universe.notice.noteCreated": "Created {path}.",
    "universe.notice.noteExists": "{path} already exists.",
    "universe.notice.noteFailed": "Couldn't create the universe note.",

    "universe.settings": "Universe",
    "universe.settings.desc": "Characters, places and other entries your stories share. Changing the mode never moves or edits notes.",
    "universe.settings.mode.off": "Off",
    "universe.settings.mode.perBook": "Per book",
    "universe.settings.mode.universe": "Universe",
    "universe.settings.note": "Universe note",
    "universe.settings.note.desc": "Works join the universe with {example}. A folder with the same name beside the note holds the entries.",
    "universe.settings.note.create": "Create",
    "universe.settings.folders": "Folders in the universe",
    "universe.settings.folders.desc": "Works in these folders are part of the universe without needing the property. One per line.",
    "universe.settings.form": "Form property",
    "universe.settings.form.desc": "Groups the Works tab. Values, separated by commas, in this order: short story, essay, novella, novel, poem, fragment.",
    "universe.settings.formFolders": "Form by folder",
    "universe.settings.formFolders.example": "Short stories: short story\nEssays: essay",
    "universe.settings.defaultFolders.example": "Short stories\nNovels",
    "universe.settings.formFolders.desc": "Works in these folders take this form when they have no form property. One per line, as Folder: form.",
    "universe.settings.form.desc.perBook": "Names the property that tells a short story from a novel.",
    "universe.settings.form.values": "Form values",
    "universe.settings.threadWord": "Thread word",
    "universe.settings.threadWord.desc": "{example} marks a loose end. Works in every mode.",
    "universe.settings.closedWord": "Closed word",
    "universe.settings.closedWord.desc": "Written after the thread word when a thread is closed: {example}.",
    "universe.settings.types": "Entry types",
    "universe.settings.types.desc": "The type comes from the property, not from the folder; the folder is only where new entries are created. Template: {{title}}, {{date}} and {{time}} are filled in.",
    "universe.settings.types.bookDesc": "Folders inside the book: {example}…",
    "universe.settings.types.property": "Property",
    "universe.settings.types.value": "Value",
    "universe.settings.types.folder": "Folder",
    "universe.settings.types.template": "Template",
    "universe.settings.types.label": "Name in menus",
    "universe.settings.types.none": "(none)",
    "universe.settings.types.note": "Five fixed types, like the stages: the names change, the list doesn't. The timeline (phase 2) reads \"event\".",
    "universe.settings.bookExample": "Book",
    "universe.settings.mode.pointer": "Turn the universe on or off, per book or shared, on the Features page at the top of these settings.",
    "universe.settings.names": "Names",
    "universe.settings.underline": "Underline names in the editor",
    "universe.settings.underline.desc": "A thin line under the names and aliases of entries. Names are never marked as spelling errors, on or off.",
    "universe.settings.titles": "Extra titles",
    "universe.settings.titles.desc": "Words skipped before the first name: \"Dona Benta\" gives the alias \"Benta\". Built in: {list}. One per line.",
    "universe.settings.titles.also": "(and {list} in English)",
    "universe.settings.titles.none": "(none)",
    "universe.settings.props": "Entry properties",
    "universe.settings.props.desc": "The names of the properties that adjust an entry. Click to see them.",
    "universe.settings.props.show": "Show",
    "universe.settings.props.hide": "Hide",
    "universe.settings.props.caseSensitive": "Exact capitalization (a 'PORTO' heading doesn't count)",
    "universe.settings.props.caseSensitive.label": "Case-sensitive property",
    "universe.settings.props.ignore": "Phrases that don't count (\"rosa dos ventos\")",
    "universe.settings.props.ignore.label": "Ignore property",
    "universe.settings.props.firstName": "First name as an alias (yes/no)",
    "universe.settings.props.firstName.label": "First name property",
  },
  "pt-BR": {
    "universe.cmd.open": "Abrir o painel do universo",
    "universe.cmd.showThreads": "Mostrar threads abertas",
    "universe.cmd.plantThread": "Plantar uma thread",
    "universe.cmd.createEntry": "Criar entrada do universo",
    "universe.cmd.closeThread": "Fechar a thread",
    "universe.cmd.migrate": "Mover as entradas deste livro para o universo",

    "universe.kind.character": "Personagem",
    "universe.kind.place": "Lugar",
    "universe.kind.object": "Objeto",
    "universe.kind.group": "Grupo",
    "universe.kind.event": "Evento",

    "universe.notice.noteCreated": "{path} criada.",
    "universe.notice.noteExists": "{path} já existe.",
    "universe.notice.noteFailed": "Não deu para criar a nota do universo.",

    "universe.settings": "Universo",
    "universe.settings.desc": "Personagens, lugares e outras entradas que suas histórias compartilham. Trocar de modo nunca move nem edita notas.",
    "universe.settings.mode.off": "Desligado",
    "universe.settings.mode.perBook": "Por livro",
    "universe.settings.mode.universe": "Universo",
    "universe.settings.note": "Nota do universo",
    "universe.settings.note.desc": "As obras entram no universo com {example}. Ao lado da nota, uma pasta de mesmo nome guarda as entradas.",
    "universe.settings.note.create": "Criar",
    "universe.settings.folders": "Pastas no universo",
    "universe.settings.folders.desc": "Obras nestas pastas fazem parte do universo sem precisar da propriedade. Uma por linha.",
    "universe.settings.form": "Propriedade de forma",
    "universe.settings.form.desc": "Agrupa a aba Obras. Valores, separados por vírgula, nesta ordem: conto, ensaio, novela, romance, poema, fragmento.",
    "universe.settings.formFolders": "Forma por pasta",
    "universe.settings.formFolders.example": "Contos: conto\nEnsaios: ensaio",
    "universe.settings.defaultFolders.example": "Contos\nRomances",
    "universe.settings.formFolders.desc": "Obras nestas pastas recebem esta forma quando não têm a propriedade. Uma por linha, como Pasta: forma.",
    "universe.settings.form.desc.perBook": "Nome da propriedade que distingue um conto de um romance.",
    "universe.settings.form.values": "Valores de forma",
    "universe.settings.threadWord": "Palavra das threads",
    "universe.settings.threadWord.desc": "{example} marca uma ponta solta. Vale em qualquer modo.",
    "universe.settings.closedWord": "Palavra de thread fechada",
    "universe.settings.closedWord.desc": "Escrita depois da palavra das threads quando uma thread é fechada: {example}.",
    "universe.settings.types": "Tipos de entrada",
    "universe.settings.types.desc": "O tipo vem da propriedade, não da pasta; a pasta é só onde as entradas novas nascem. Modelo: {{title}}, {{date}} e {{time}} são preenchidos.",
    "universe.settings.types.bookDesc": "Pastas dentro do livro: {example}…",
    "universe.settings.types.property": "Propriedade",
    "universe.settings.types.value": "Valor",
    "universe.settings.types.folder": "Pasta",
    "universe.settings.types.template": "Modelo",
    "universe.settings.types.label": "Nome no menu",
    "universe.settings.types.none": "(nenhum)",
    "universe.settings.types.note": "Cinco tipos fixos, como os estágios: os nomes mudam, a lista não. A fase 2 (linha do tempo) lê \"evento\".",
    "universe.settings.bookExample": "Livro",
    "universe.settings.mode.pointer": "Ligue ou desligue o universo, por livro ou compartilhado, na página Recursos, no topo destas configurações.",
    "universe.settings.names": "Nomes",
    "universe.settings.underline": "Sublinhar nomes no editor",
    "universe.settings.underline.desc": "Um traço fino sob nomes e apelidos de entradas. Os nomes nunca são marcados como erro de ortografia, ligado ou não.",
    "universe.settings.titles": "Títulos extras",
    "universe.settings.titles.desc": "Palavras puladas antes do primeiro nome: \"Dona Benta\" dá o apelido \"Benta\". Já inclusos: {list}. Um por linha.",
    "universe.settings.titles.also": "(e {list} em inglês)",
    "universe.settings.titles.none": "(nenhum)",
    "universe.settings.props": "Propriedades da entrada",
    "universe.settings.props.desc": "Os nomes das propriedades que ajustam uma entrada. Clique para ver.",
    "universe.settings.props.show": "Mostrar",
    "universe.settings.props.hide": "Ocultar",
    "universe.settings.props.caseSensitive": "Maiúsculas exatas (um título \"PORTO\" não conta)",
    "universe.settings.props.caseSensitive.label": "Propriedade de maiúsculas",
    "universe.settings.props.ignore": "Expressões que não contam (\"rosa dos ventos\")",
    "universe.settings.props.ignore.label": "Propriedade de ignorar",
    "universe.settings.props.firstName": "Primeiro nome como apelido (sim/não)",
    "universe.settings.props.firstName.label": "Propriedade de primeiro nome",
  },
};
