import type { Strings } from "../i18n";

// BUILDER A owns this file: the universe panel and the Open threads view. Keys: universe.view.*
export const universeViewStrings: Strings = {
  en: {
    "universe.view.title": "Universe",
    "universe.view.threadsTitle": "Open threads",
    "universe.view.off": "The universe panel is off. Turn on a shared universe mode in the settings.",
    "universe.view.tab.entries": "Entries",
    "universe.view.tab.threads": "Threads",
    "universe.view.tab.works": "Works",

    "universe.view.count.entries.one": "{n} entry",
    "universe.view.count.entries.other": "{n} entries",
    "universe.view.count.works.one": "{n} work",
    "universe.view.count.works.other": "{n} works",
    "universe.view.count.inWorks.one": "in {n} work",
    "universe.view.count.inWorks.other": "in {n} works",
    "universe.view.count.threads.one": "{n} thread",
    "universe.view.count.threads.other": "{n} threads",
    "universe.view.count.threadsOpen.one": "{n} open thread",
    "universe.view.count.threadsOpen.other": "{n} open threads",
    "universe.view.count.open.one": "{n} open",
    "universe.view.count.open.other": "{n} open",
    "universe.view.count.closed.one": "{n} closed",
    "universe.view.count.closed.other": "{n} closed",
    "universe.view.count.words.one": "{n} word",
    "universe.view.count.words.other": "{n} words",
    "universe.view.sub.bookEntries": "Book entries · {n}",
    "universe.view.sub.join": "{a} · {b}",

    "universe.view.search": "Search names and aliases",
    "universe.view.search.aria": "Search entries",
    "universe.view.noMatch": "No entry matches that search.",
    "universe.view.kind.character": "Characters",
    "universe.view.kind.place": "Places",
    "universe.view.kind.object": "Objects",
    "universe.view.kind.group": "Groups",
    "universe.view.kind.event": "Events",
    "universe.view.newIn": "New entry · {kind}",
    "universe.view.toggleGroup": "Show or hide {kind}",

    "universe.view.empty.entries": "No entries yet. Select a name in the text and choose {command} in the menu, or start here.",
    "universe.view.newEntry": "New entry",
    "universe.view.empty.noNote": "The universe note doesn't exist: {path}. It names the universe and is the link works use.",
    "universe.view.createNote": "Create the note",
    "universe.view.openSettings": "Open settings",
    "universe.view.noteCreated": "Created {path}.",
    "universe.view.noteFailed": "Couldn't create the universe note.",
    "universe.view.notInUniverse": "“{title}” isn't part of a universe.",
    "universe.view.addTo": "Add to {universe}",
    "universe.view.linkRefused": "The cursor is in the properties, code or a comment, so no link was inserted. Click in the text and try again.",
    "universe.view.addFailed": "Couldn't add the note to the universe. Check its properties (the YAML may be broken).",
    "universe.view.addedTo": "Added “{title}” to {universe}.",
    "universe.view.alreadyIn": "“{title}” already names a universe. Nothing was changed.",
    "universe.view.notInBook": "“{title}” isn't part of a book.",
    "universe.view.noBook": "Open a note that belongs to a book to see its entries.",
    "universe.view.pickUniverse": "Choose a universe",
    "universe.view.activeNote": "active note",

    "universe.view.menu.open": "Open",
    "universe.view.menu.openSide": "Open to the side",
    "universe.view.menu.insertLink": "Insert link in note",
    "universe.view.menu.reveal": "Show in file explorer",
    "universe.view.noEditor": "Open a note in the editor first, then insert the link.",

    "universe.view.thread.since": "since {date}",
    "universe.view.thread.answeredBy": "→ {note}",
    "universe.view.thread.answeredIn": "answered in {note}",
    "universe.view.thread.closed": "closed",
    "universe.view.thread.closeAria": "Close the thread",
    "universe.view.thread.reopenAria": "Reopen the thread",
    "universe.view.thread.go": "Go to the marker",
    "universe.view.foot.show": "Show",
    "universe.view.foot.hide": "Hide closed",
    "universe.view.foot.none": "No closed threads",
    "universe.view.empty.threads": "No open threads. To leave a loose end for another story, write on a line:",
    "universe.view.empty.threadsCommand": "Or use the command “{command}”.",
    "universe.view.empty.threadsOff": "No open threads in your tracked works. To leave a loose end, write on a line:",

    "universe.view.close.title": "Close “{text}”",
    "universe.view.close.answer": "Answered in (optional)",
    "universe.view.close.hint": "In {note}, the marker becomes {marker}",
    "universe.view.close.cancel": "Cancel",
    "universe.view.close.confirm": "Close",
    "universe.view.notice.stale": "The thread changed since the list was read. Nothing was changed; the list was refreshed.",
    "universe.view.notice.closed": "Thread closed in {note}.",
    "universe.view.notice.reopened": "Thread reopened in {note}.",
    "universe.view.notice.unknownAnswer": "“{name}” isn't a known work. The thread was closed with the link anyway.",
    "universe.view.notice.missing": "{path} is gone.",

    "universe.view.empty.works": "No works in this universe yet. A work is a book, or a note with a status.",
    "universe.view.noForm": "No form",
    "universe.view.form.shortStory": "Short stories",
    "universe.view.form.essay": "Essays",
    "universe.view.form.novella": "Novellas",
    "universe.view.form.novel": "Novels",
    "universe.view.form.poem": "Poems",
    "universe.view.form.fragment": "Fragments",
    "universe.view.noWords": "—",
    "universe.unlinked.title": "Unlinked mentions",
    "universe.unlinked.counting": "counting…",
    "universe.unlinked.empty": "No unlinked mentions in this note.",
    "universe.unlinked.create": "Create link",
    "universe.unlinked.goTo": "Go to the mention of {name}",
    "universe.unlinked.changed": "The text changed there, so no link was written.",
    "universe.unlinked.failed": "Couldn't write the link.",

    "universe.appears.title": "Appears in",
    "universe.appears.mentions.one": "{n} mention",
    "universe.appears.mentions.other": "{n} mentions",
    "universe.appears.tip": "{mentions} in {works}",
    "universe.appears.counting": "counting…",
    "universe.appears.none": "no works yet",
    "universe.appears.other": "Other notes",
    "universe.appears.first": "first in ch. {ref}",
    "universe.appears.last": "last in ch. {ref}",
  },
  "pt-BR": {
    "universe.view.title": "Universo",
    "universe.view.threadsTitle": "Fios abertos",
    "universe.view.off": "O painel do universo está desligado. Ligue um modo de universo compartilhado nas configurações.",
    "universe.view.tab.entries": "Entradas",
    "universe.view.tab.threads": "Fios",
    "universe.view.tab.works": "Obras",

    "universe.view.count.entries.one": "{n} entrada",
    "universe.view.count.entries.other": "{n} entradas",
    "universe.view.count.works.one": "{n} obra",
    "universe.view.count.works.other": "{n} obras",
    "universe.view.count.inWorks.one": "em {n} obra",
    "universe.view.count.inWorks.other": "em {n} obras",
    "universe.view.count.threads.one": "{n} fio",
    "universe.view.count.threads.other": "{n} fios",
    "universe.view.count.threadsOpen.one": "{n} fio aberto",
    "universe.view.count.threadsOpen.other": "{n} fios abertos",
    "universe.view.count.open.one": "{n} aberto",
    "universe.view.count.open.other": "{n} abertos",
    "universe.view.count.closed.one": "{n} fechado",
    "universe.view.count.closed.other": "{n} fechados",
    "universe.view.count.words.one": "{n} palavra",
    "universe.view.count.words.other": "{n} palavras",
    "universe.view.sub.bookEntries": "Entradas do livro · {n}",
    "universe.view.sub.join": "{a} · {b}",

    "universe.view.search": "Buscar nomes e apelidos",
    "universe.view.search.aria": "Buscar entradas",
    "universe.view.noMatch": "Nenhuma entrada combina com a busca.",
    "universe.view.kind.character": "Personagens",
    "universe.view.kind.place": "Lugares",
    "universe.view.kind.object": "Objetos",
    "universe.view.kind.group": "Grupos",
    "universe.view.kind.event": "Eventos",
    "universe.view.newIn": "Nova entrada · {kind}",
    "universe.view.toggleGroup": "Mostrar ou esconder {kind}",

    "universe.view.empty.entries": "Nenhuma entrada ainda. Selecione um nome no texto e escolha {command} no menu, ou comece por aqui.",
    "universe.view.newEntry": "Nova entrada",
    "universe.view.empty.noNote": "A nota do universo não existe: {path}. Ela dá nome ao universo e é o link que as obras usam.",
    "universe.view.createNote": "Criar a nota",
    "universe.view.openSettings": "Abrir configurações",
    "universe.view.noteCreated": "{path} criada.",
    "universe.view.noteFailed": "Não foi possível criar a nota do universo.",
    "universe.view.notInUniverse": "“{title}” não faz parte de um universo.",
    "universe.view.addTo": "Adicionar ao {universe}",
    "universe.view.linkRefused": "O cursor está nas propriedades, em código ou em um comentário, então o link não foi inserido. Clique no texto e tente de novo.",
    "universe.view.addFailed": "Não foi possível adicionar a nota ao universo. Confira as propriedades (o YAML pode estar quebrado).",
    "universe.view.addedTo": "“{title}” adicionada ao {universe}.",
    "universe.view.alreadyIn": "“{title}” já indica um universo. Nada foi alterado.",
    "universe.view.notInBook": "“{title}” não faz parte de um livro.",
    "universe.view.noBook": "Abra uma nota que pertença a um livro para ver as entradas dele.",
    "universe.view.pickUniverse": "Escolher um universo",
    "universe.view.activeNote": "nota ativa",

    "universe.view.menu.open": "Abrir",
    "universe.view.menu.openSide": "Abrir ao lado",
    "universe.view.menu.insertLink": "Inserir link na nota",
    "universe.view.menu.reveal": "Mostrar no explorador",
    "universe.view.noEditor": "Abra uma nota no editor primeiro e depois insira o link.",

    "universe.view.thread.since": "desde {date}",
    "universe.view.thread.answeredBy": "→ {note}",
    "universe.view.thread.answeredIn": "respondido em {note}",
    "universe.view.thread.closed": "fechado",
    "universe.view.thread.closeAria": "Fechar o fio",
    "universe.view.thread.reopenAria": "Reabrir o fio",
    "universe.view.thread.go": "Ir para o marcador",
    "universe.view.foot.show": "Mostrar",
    "universe.view.foot.hide": "Esconder fechados",
    "universe.view.foot.none": "Nenhum fechado",
    "universe.view.empty.threads": "Nenhum fio aberto. Para deixar uma ponta solta para outra história, escreva numa linha:",
    "universe.view.empty.threadsCommand": "Ou use o comando “{command}”.",
    "universe.view.empty.threadsOff": "Nenhum fio aberto nas obras acompanhadas. Para deixar uma ponta solta, escreva numa linha:",

    "universe.view.close.title": "Fechar “{text}”",
    "universe.view.close.answer": "Respondido em (opcional)",
    "universe.view.close.hint": "Em {note}, o marcador vira {marker}",
    "universe.view.close.cancel": "Cancelar",
    "universe.view.close.confirm": "Fechar",
    "universe.view.notice.stale": "O fio mudou desde que a lista foi lida. Nada foi alterado; a lista foi atualizada.",
    "universe.view.notice.closed": "Fio fechado em {note}.",
    "universe.view.notice.reopened": "Fio reaberto em {note}.",
    "universe.view.notice.unknownAnswer": "“{name}” não é uma obra conhecida. O fio foi fechado com o link assim mesmo.",
    "universe.view.notice.missing": "{path} não existe mais.",

    "universe.view.empty.works": "Nenhuma obra neste universo ainda. Uma obra é um livro, ou uma nota com status.",
    "universe.view.noForm": "Sem forma",
    "universe.view.form.shortStory": "Contos",
    "universe.view.form.essay": "Ensaios",
    "universe.view.form.novella": "Novelas",
    "universe.view.form.novel": "Romances",
    "universe.view.form.poem": "Poemas",
    "universe.view.form.fragment": "Fragmentos",
    "universe.view.noWords": "—",
    "universe.unlinked.title": "Menções sem link",
    "universe.unlinked.counting": "contando…",
    "universe.unlinked.empty": "Nenhuma menção sem link nesta nota.",
    "universe.unlinked.create": "Criar link",
    "universe.unlinked.goTo": "Ir para a menção de {name}",
    "universe.unlinked.changed": "O texto mudou ali, então nenhum link foi escrito.",
    "universe.unlinked.failed": "Não foi possível escrever o link.",

    "universe.appears.title": "Aparece em",
    "universe.appears.mentions.one": "{n} menção",
    "universe.appears.mentions.other": "{n} menções",
    "universe.appears.tip": "{mentions} em {works}",
    "universe.appears.counting": "contando…",
    "universe.appears.none": "nenhuma obra ainda",
    "universe.appears.other": "Outras notas",
    "universe.appears.first": "primeira no cap. {ref}",
    "universe.appears.last": "última no cap. {ref}",
  },
};
