import type { Strings } from "../i18n";

export const outlineStrings: Strings = {
  en: {
    "outline.viewTitle": "Outline",
    "outline.command.open": "Open outline",
    "outline.command.board": "Open outline as a board",
    "outline.command.createBook": "Create a book",
    "outline.command.addBeat": "Add a beat to this chapter",
    "outline.command.renumber": "Renumber chapters of this book",

    "outline.chapters.one": "{n} chapter",
    "outline.chapters.other": "{n} chapters",
    "outline.beats.one": "{n} beat",
    "outline.beats.other": "{n} beats",
    "outline.progress": "{words} / {goal}",
    "outline.outlineOnly": "outline only",
    "outline.placeholderBadge": "{n} {marker}",
    "outline.placeholderTip": "Placeholders in this chapter",
    "outline.writtenTip": "Written",
    "outline.newChapter": "New chapter…",
    "outline.newChapterHint": "(Enter)",
    "outline.titlePlaceholder": "Chapter title",
    "outline.summaryPlaceholder": "Summary",
    "outline.beatPlaceholder": "What happens in this scene?",
    "outline.numberTip": "Open · drag to reorder",
    "outline.letterTip": "Go to this beat",
    "outline.board": "Open as board (Canvas)",
    "outline.bookSelect": "Book",

    "outline.hint.enter": "new line",
    "outline.hint.tab": "makes it a beat",
    "outline.hint.shiftTab": "makes it a chapter",
    "outline.hint.backspace": "on an empty line deletes it",
    "outline.hint.drag": "drag the numbers to reorder; files renumber",

    "outline.empty.title": "No book yet",
    "outline.empty.desc": "A book is a note with a folder of the same name next to it. Inside that folder, a “{folder}” folder holds one note per chapter.",
    "outline.empty.example": "Novels/My Book.md\nNovels/My Book/{folder}/01 Arrival.md\nNovels/My Book/{folder}/02 The locked door.md",
    "outline.empty.create": "Create a book",
    "outline.pick": "Choose a book",

    "outline.menu.open": "Open",
    "outline.menu.openTab": "Open in new tab",
    "outline.menu.moveUp": "Move up",
    "outline.menu.moveDown": "Move down",
    "outline.menu.delete": "Delete chapter",
    "outline.menu.goToBeat": "Go to beat",
    "outline.menu.removeBeat": "Remove beat (keeps the prose)",

    "outline.delete.title": "Delete chapter?",
    "outline.delete.desc": "“{title}” has {words}. It will be moved to the trash.",
    "outline.delete.confirm": "Move to trash",
    "outline.cancel": "Cancel",

    "outline.blocked.firstChapter": "The first chapter can't become a beat: there is no chapter above it.",
    "outline.blocked.notEmptyTab": "Only an empty chapter can become a beat. This one has text or beats.",
    "outline.blocked.notEmptyDelete": "This chapter has text or beats. Use its menu to delete it.",
    "outline.blocked.written": "This beat already has prose. Only unwritten beats can become chapters.",
    "outline.blocked.noChapters": "Create a chapter first.",
    "outline.beatChanged": "The chapter changed on disk, so nothing was done. The outline is up to date now; try again.",
    "outline.renumbered": "Chapters renumbered.",
    "outline.error": "Escrita couldn't do that: {msg}",

    "outline.ghostLabel": "Beat {letter} · from outline",

    "outline.boardTitle": "Replace board?",
    "outline.boardExists": "“{file}” already exists and wasn't made by Escrita. Replace it?",
    "outline.boardReplace": "Replace",

    "outline.create.title": "Create a book",
    "outline.create.name": "Title",
    "outline.create.folder": "Folder",
    "outline.create.folderDesc": "Where the book note and its folder go. Leave empty for the vault root.",
    "outline.create.submit": "Create",
    "outline.create.needTitle": "Give the book a title.",
    "outline.create.exists": "“{path}” already exists.",
    "outline.create.notBook": "“{path}” wasn't recognized as a book. Check the chapters folder setting.",

    "outline.err.exists": "“{name}” already exists",
    "outline.err.duplicate": "two chapters would be named “{name}”",
    "outline.err.notFound": "chapter “{name}” not found",

    "outline.more": "More actions",
    "outline.menu.addBeat": "Add a beat",
    "outline.menu.newChapterAfter": "New chapter after this one",
    "outline.menu.toBeat": "Make it a beat of the previous chapter",
    "outline.menu.toChapter": "Make it a chapter",
    "outline.menu.addBeatAfter": "Add a beat after this one",
    "outline.hint.touch": "Use the ⋯ buttons for more actions; files renumber when chapters move.",

    "outline.note.noBeats": "No beats in this note yet.",
    "outline.note.addFirst": "Add the first beat",
    "outline.note.limitOnly": "(limit)",
    "outline.note.limit": "limit {n}",
    "outline.note.over": "{n} over the limit",
    "outline.note.touchHint": "Use the ⋯ buttons for more actions.",
    "outline.note.changed": "The note changed on disk, so nothing was done. The outline is up to date now; try again.",
    "outline.noStatus": "no status",
    "outline.colorBy": "Color by",
    "outline.colorBy.status": "Status",
    "outline.colorBy.pov": "POV",
    "outline.chips.stages": "Filter by stage",
    "outline.chips.povs": "Filter by POV",
    "outline.chips.more": "+{n}",
    "outline.chips.less": "fewer",
    "outline.filter.showing": "Showing {shown} of {total} · drag and renumber paused",
    "outline.filter.showing.short": "Showing {shown} of {total}",
    "outline.filter.clear": "Clear",
    "outline.menu.colorOf": "Color of {name}",
    "outline.menu.openEntry": "Open the entry",
    "outline.color.red": "Red",
    "outline.color.orange": "Orange",
    "outline.color.yellow": "Yellow",
    "outline.color.green": "Green",
    "outline.color.cyan": "Cyan",
    "outline.color.blue": "Blue",
    "outline.color.purple": "Purple",
    "outline.color.pink": "Pink",
    "outline.bar.label": "Chapter length",
    "outline.bar.own": "chapter target",
  },
  "pt-BR": {
    "outline.viewTitle": "Esboço",
    "outline.command.open": "Abrir esboço",
    "outline.command.board": "Abrir esboço como quadro",
    "outline.command.createBook": "Criar um livro",
    "outline.command.addBeat": "Adicionar um beat a este capítulo",
    "outline.command.renumber": "Renumerar os capítulos deste livro",

    "outline.chapters.one": "{n} capítulo",
    "outline.chapters.other": "{n} capítulos",
    "outline.beats.one": "{n} beat",
    "outline.beats.other": "{n} beats",
    "outline.progress": "{words} / {goal}",
    "outline.outlineOnly": "só esboço",
    "outline.placeholderBadge": "{n} {marker}",
    "outline.placeholderTip": "Marcadores neste capítulo",
    "outline.writtenTip": "Escrito",
    "outline.newChapter": "Novo capítulo…",
    "outline.newChapterHint": "(Enter)",
    "outline.titlePlaceholder": "Título do capítulo",
    "outline.summaryPlaceholder": "Resumo",
    "outline.beatPlaceholder": "O que acontece nesta cena?",
    "outline.numberTip": "Abrir · arraste para reordenar",
    "outline.letterTip": "Ir para este beat",
    "outline.board": "Abrir como quadro (Canvas)",
    "outline.bookSelect": "Livro",

    "outline.hint.enter": "nova linha",
    "outline.hint.tab": "vira beat",
    "outline.hint.shiftTab": "vira capítulo",
    "outline.hint.backspace": "numa linha vazia apaga",
    "outline.hint.drag": "arraste os números para reordenar; os arquivos são renumerados",

    "outline.empty.title": "Nenhum livro ainda",
    "outline.empty.desc": "Um livro é uma nota com uma pasta de mesmo nome ao lado. Dentro dessa pasta, uma pasta “{folder}” guarda uma nota por capítulo.",
    "outline.empty.example": "Romances/Meu Livro.md\nRomances/Meu Livro/{folder}/01 Chegada.md\nRomances/Meu Livro/{folder}/02 A porta fechada.md",
    "outline.empty.create": "Criar um livro",
    "outline.pick": "Escolha um livro",

    "outline.menu.open": "Abrir",
    "outline.menu.openTab": "Abrir em nova aba",
    "outline.menu.moveUp": "Mover para cima",
    "outline.menu.moveDown": "Mover para baixo",
    "outline.menu.delete": "Excluir capítulo",
    "outline.menu.goToBeat": "Ir para o beat",
    "outline.menu.removeBeat": "Remover beat (mantém o texto)",

    "outline.delete.title": "Excluir capítulo?",
    "outline.delete.desc": "“{title}” tem {words}. Ele vai para a lixeira.",
    "outline.delete.confirm": "Mover para a lixeira",
    "outline.cancel": "Cancelar",

    "outline.blocked.firstChapter": "O primeiro capítulo não pode virar beat: não há capítulo acima dele.",
    "outline.blocked.notEmptyTab": "Só um capítulo vazio pode virar beat. Este tem texto ou beats.",
    "outline.blocked.notEmptyDelete": "Este capítulo tem texto ou beats. Use o menu dele para excluí-lo.",
    "outline.blocked.written": "Este beat já tem texto. Só beats ainda não escritos podem virar capítulos.",
    "outline.blocked.noChapters": "Crie um capítulo primeiro.",
    "outline.beatChanged": "O capítulo mudou no disco, então nada foi feito. O esboço já está atualizado; tente de novo.",
    "outline.renumbered": "Capítulos renumerados.",
    "outline.error": "O Escrita não conseguiu fazer isso: {msg}",

    "outline.ghostLabel": "Beat {letter} · do esboço",

    "outline.boardTitle": "Substituir quadro?",
    "outline.boardExists": "“{file}” já existe e não foi criado pelo Escrita. Substituir?",
    "outline.boardReplace": "Substituir",

    "outline.create.title": "Criar um livro",
    "outline.create.name": "Título",
    "outline.create.folder": "Pasta",
    "outline.create.folderDesc": "Onde ficam a nota do livro e a pasta dele. Deixe vazio para a raiz do cofre.",
    "outline.create.submit": "Criar",
    "outline.create.needTitle": "Dê um título ao livro.",
    "outline.create.exists": "“{path}” já existe.",
    "outline.create.notBook": "“{path}” não foi reconhecido como livro. Confira a configuração da pasta de capítulos.",

    "outline.err.exists": "“{name}” já existe",
    "outline.err.duplicate": "dois capítulos ficariam com o nome “{name}”",
    "outline.err.notFound": "capítulo “{name}” não encontrado",

    "outline.more": "Mais ações",
    "outline.menu.addBeat": "Adicionar um beat",
    "outline.menu.newChapterAfter": "Novo capítulo depois deste",
    "outline.menu.toBeat": "Transformar em beat do capítulo anterior",
    "outline.menu.toChapter": "Transformar em capítulo",
    "outline.menu.addBeatAfter": "Adicionar um beat depois deste",
    "outline.hint.touch": "Use os botões ⋯ para mais ações; os arquivos são renumerados quando os capítulos mudam de lugar.",

    "outline.note.noBeats": "Esta nota ainda não tem beats.",
    "outline.note.addFirst": "Adicionar o primeiro beat",
    "outline.note.limitOnly": "(limite)",
    "outline.note.limit": "limite {n}",
    "outline.note.over": "{n} acima do limite",
    "outline.note.touchHint": "Use os botões ⋯ para mais ações.",
    "outline.note.changed": "A nota mudou no disco, então nada foi feito. O esboço já está atualizado; tente de novo.",
    "outline.noStatus": "sem status",
    "outline.colorBy": "Colorir por",
    "outline.colorBy.status": "Status",
    "outline.colorBy.pov": "POV",
    "outline.chips.stages": "Filtrar por estágio",
    "outline.chips.povs": "Filtrar por POV",
    "outline.chips.more": "+{n}",
    "outline.chips.less": "menos",
    "outline.filter.showing": "Mostrando {shown} de {total} · arrastar e renumerar pausados",
    "outline.filter.showing.short": "Mostrando {shown} de {total}",
    "outline.filter.clear": "Limpar",
    "outline.menu.colorOf": "Cor de {name}",
    "outline.menu.openEntry": "Abrir a entrada",
    "outline.color.red": "Vermelho",
    "outline.color.orange": "Laranja",
    "outline.color.yellow": "Amarelo",
    "outline.color.green": "Verde",
    "outline.color.cyan": "Ciano",
    "outline.color.blue": "Azul",
    "outline.color.purple": "Roxo",
    "outline.color.pink": "Rosa",
    "outline.bar.label": "Tamanho do capítulo",
    "outline.bar.own": "meta do capítulo",
  },
};
