import type { Strings } from "../i18n";

export const publishStrings: Strings = {
  en: {
    "publish.command": "Publish this note",
    "publish.unpublishCommand": "Unpublish this note",
    "publish.menu": "Publish…",
    "publish.menuUnpublish": "Unpublish",
    "publish.title": "Publish “{title}”",
    "publish.date": "Publication date",
    "publish.dateHint": "Keeps the note's date when it has one. You can pick a future date.",
    "publish.dateUnparsed": "The note's date “{value}” isn't in YYYY-MM-DD form. It's kept as it is unless you pick a date here.",
    "publish.anyway": "Publish anyway",
    "publish.anywayHint": "Blockers are things readers would notice, like hidden text or a leftover placeholder. Escrita can't know every case, so you can override them.",
    "publish.button": "Publish",
    "publish.cancel": "Cancel",
    "publish.published": "Published “{title}” with date {date}.",
    "publish.unpublished": "Unpublished “{title}”: status is now “{status}”.",
    "publish.notPublished": "This note isn't published.",
    "publish.noStatus": "Set the status property in Escrita's settings first.",
    "publish.error": "Couldn't publish. Nothing was changed; see the developer console.",
    "publish.errorUnpublish": "Couldn't unpublish. See the developer console.",
    "publish.level.blocker": "Blocker",
    "publish.level.warning": "Warning",
    "publish.level.passed": "Passed",
    "publish.noNote": "no note",
    "publish.jump": "Go to line {line}",
    "publish.summary.clean": "Ready to publish.",
    "publish.summary.warnings": "Ready, with warnings.",
    "publish.summary.blockers": "Fix the blockers first, or publish anyway.",
    "publish.check.unclosedComment.bad": "Unclosed %% comment: everything after line {line} is hidden",
    "publish.check.unclosedComment.ok": "Every %% comment is closed",
    "publish.check.unclosedHtmlComment.bad": "Unclosed <!-- comment on line {line}",
    "publish.check.unclosedHtmlComment.ok": "Every <!-- --> comment is closed",
    "publish.check.placeholders.bad": "Placeholders left: {n}",
    "publish.check.placeholders.ok": "No placeholders left",
    "publish.check.unwrittenBeats.bad": "Unwritten beats: {n}",
    "publish.check.unwrittenBeats.ok": "No unwritten beats",
    "publish.check.emptyBody.bad": "The note has no text",
    "publish.check.emptyBody.ok": "The note has text ({n} words)",
    "publish.check.recommended.bad": "Missing properties: {names}",
    "publish.check.recommended.ok": "Recommended properties are filled in",
    "publish.check.overLimit.bad": "Over the limit: {count} of {limit} ({over} over)",
    "publish.check.overLimit.ok": "Within the limit: {count} of {limit}",
  },
  "pt-BR": {
    "publish.command": "Publicar esta nota",
    "publish.unpublishCommand": "Despublicar esta nota",
    "publish.menu": "Publicar…",
    "publish.menuUnpublish": "Despublicar",
    "publish.title": "Publicar “{title}”",
    "publish.date": "Data de publicação",
    "publish.dateHint": "Mantém a data da nota quando ela já tem uma. Dá para escolher uma data futura.",
    "publish.dateUnparsed": "A data da nota “{value}” não está no formato AAAA-MM-DD. Ela é mantida como está, a menos que você escolha uma data aqui.",
    "publish.anyway": "Publicar mesmo assim",
    "publish.anywayHint": "Bloqueios são coisas que o leitor notaria, como texto escondido ou um marcador esquecido. O Escrita não conhece todos os casos, então você pode ignorá-los.",
    "publish.button": "Publicar",
    "publish.cancel": "Cancelar",
    "publish.published": "“{title}” publicado com data {date}.",
    "publish.unpublished": "“{title}” despublicado: o status agora é “{status}”.",
    "publish.notPublished": "Esta nota não está publicada.",
    "publish.noStatus": "Primeiro, defina a propriedade de status nas configurações do Escrita.",
    "publish.error": "Não foi possível publicar. Nada foi alterado; veja o console do desenvolvedor.",
    "publish.errorUnpublish": "Não foi possível despublicar. Veja o console do desenvolvedor.",
    "publish.level.blocker": "Bloqueio",
    "publish.level.warning": "Aviso",
    "publish.level.passed": "Ok",
    "publish.noNote": "sem nota",
    "publish.jump": "Ir para a linha {line}",
    "publish.summary.clean": "Pronto para publicar.",
    "publish.summary.warnings": "Pronto, com avisos.",
    "publish.summary.blockers": "Resolva os bloqueios antes, ou publique mesmo assim.",
    "publish.check.unclosedComment.bad": "Comentário %% sem fechamento: tudo depois da linha {line} fica oculto",
    "publish.check.unclosedComment.ok": "Todos os comentários %% estão fechados",
    "publish.check.unclosedHtmlComment.bad": "Comentário <!-- sem fechamento na linha {line}",
    "publish.check.unclosedHtmlComment.ok": "Todos os comentários <!-- --> estão fechados",
    "publish.check.placeholders.bad": "Marcadores pendentes: {n}",
    "publish.check.placeholders.ok": "Nenhum marcador pendente",
    "publish.check.unwrittenBeats.bad": "Beats não escritos: {n}",
    "publish.check.unwrittenBeats.ok": "Todos os beats foram escritos",
    "publish.check.emptyBody.bad": "A nota não tem texto",
    "publish.check.emptyBody.ok": "A nota tem texto ({n} palavras)",
    "publish.check.recommended.bad": "Propriedades faltando: {names}",
    "publish.check.recommended.ok": "Propriedades recomendadas preenchidas",
    "publish.check.overLimit.bad": "Acima do limite: {count} de {limit} ({over} a mais)",
    "publish.check.overLimit.ok": "Dentro do limite: {count} de {limit}",
  },
};
